== La Vida de Ambrose Rigge

Lo siguiente es un relato verdadero de la primera manifestación
del amor de Dios en Cristo Jesús hacia mí. Hasta donde puedo recordar,
cuando tenía cerca de diez o doce años,
el Señor tocó mi corazón con un sentido de mi fin,
tema que a menudo consideraba profundamente cuando
estaba en la escuela gratuita entre mis compañeros.
A menudo pensaba en mi Creador, y en Su gran obra en la creación,
y que todos debían darle cuenta a Él por sus obras, ya fueran buenas o malas.
Sin embargo, al estar diariamente en contacto con mis compañeros de juego,
fui llevado al desenfreno y al juego, y a muchos placeres juveniles,
en medio de los cuales a menudo era golpeado por la vara de Dios,
aunque yo en ese entonces no Lo conocía. Sin embargo,
una cosa me consolaba un poco durante este tiempo, y era,
que yo aborrecía los juramentos vanos e irreverentes y las embriagueces,
en los cuales vi que muchos de mis compañeros se habían hundido.
En verdad, en mi corazón había un aborrecimiento de esas cosas.

Habiendo sido educado para leer las Escrituras desde niño,
esperaba encontrar algo de vida en ellas;
pero siendo ajeno a Aquel en quién estaba y es la vida,
todavía permanecía en tinieblas y en la región de sombra de muerte.
Sin embargo,
encontré que las Escrituras declaraban que el día del Señor ardería como un horno,
en el cual todos los soberbios, y todos los que hacían maldad, serían como estopa,
y que el día que estaba viniendo no les dejaría ni raíz ni rama (Malaquías 4),
y muchas palabras similares, que creía que eran verdad,
y que de alguna manera llegarían a suceder.
Y aunque yo no fui vencido por los peores males, aun así,
sentía diariamente al pecado reinando y gobernando en mí,
y llevándome cautivo a varios deseos y placeres vanos,
que se convirtieron en mi gran carga.
Bajo un sentido de esto, a menudo gemía y clamaba al Señor por libertad.
Pero estando todavía en el reino y poder de las tinieblas,
no veía manera de alcanzar libertad,
y por lo tanto permanecía bajo la esclavitud de corrupción.

Cuando aprendí a escribir, me deleitaba mucho escribiendo los sermones de los sacerdotes,
y cuando volvía a casa me ponía a memorizarlos,
de modo que reuní mucho en mi conocimiento,
pero seguía estando ajeno a la vida de Cristo que mi alma anhelaba,
y así estaba "`sin Dios en el mundo.`"^
footnote:[Efesios 2:12]
Andaba errante de monte en collado,
y sin embargo no podía hallar ningún lugar donde sentar la planta de mi pie.
Permanecí en esta condición hasta los dieciséis años,
corriendo de un sumo sacerdote a otro,
esperando recibir de ellos eso de lo que mi alma estaba sedienta,
pero siempre me iba insatisfecho.

Estos eran para mí "`médicos nulos,`"^
footnote:[Job 13:4]
aunque me decían que me aplicara las promesas a mí mismo y que tuviera fe.
Aun así,
tanto ellos como yo no conocíamos la "`Palabra de fe,`" que el apóstol predicaba,
la cual está "`cerca en el corazón,`"^
footnote:[Romanos 10:8]
la cual produce fe cuando es oída. En verdad,
yo no conocía la semilla a la que le fue hecha la promesa de vida,
y encontré algo gobernando en mí, a lo que no le había sido dada ninguna promesa.
Y así me di cuenta de que cualquier recubrimiento que me
fuera aplicado mientras que la corrupción no fuese limpiada,
no tenía ningún valor en cuanto a mi cura; porque,
desde la coronilla de mi cabeza hasta la planta de mi pie,
estaba lleno de hinchazón y de podridas llagas,^
footnote:[Isaías 1:6]
de modo que a menudo era aborrecible para mí mismo.

Sin saber cómo ser sanado, seguí buscando,
y me encontré con algunos libros que se adecuaban un poco
a mi condición. Comencé a deleitarme en la lectura de estos,
y a partir de ellos reuní una forma de oración que a menudo usaba en privado,
con muchos clamores fervientes al Señor de que,
si Él tenía alguna bendición que concederme en la tierra,
que me mostrara el camino de la Verdad.
Porque veía claramente que muchos de los sacerdotes eran tan malos como yo,
y algunos peores,
de modo que no podía esperar ningún buen fruto a partir de esos árboles malos.
Así que me aparté de ellos, y fui en búsqueda de otros un poco más refinados,
pensando en encontrar más satisfacción de parte de ellos,
pero seguía sin encontrar ninguna.
Era sensible de que mis heridas se hacían cada vez más podridas,
y que lo que el mejor de estos sacerdotes podía hacer para ayudarme,
no me aliviaba en lo absoluto, ni era para nada adecuado a mi enfermedad.

Así mi alma a menudo gemía
al Señor en secreto por el conocimiento de Su camino,
no deseando ni riquezas ni honor en el mundo,
sino solo que pudiera conocer al buen Médico que
podía sanarme por completo en todos los aspectos,
lo cual tenía más valor para mí que todos los tesoros de Egipto.
A pesar de que algunos placeres juveniles prevalecían sobre mí
(que a menudo me levantaban por encima del testigo de Dios en mí),
yo también experimentaba reprensiones secretas que
me causaban tristeza en medio de mi gozo.
Y a pesar de que era como un novillo salvaje e indómito,
siempre era preservado de las maldades más grandes,
por Aquel a quién ahora experimento como mi fuerza.
Gloria, honor y alabanzas vivas al Señor Dios, y al Cordero para siempre.

Pero después de mi larga aflicción en la noche de oscuridad e ignorancia,
en la que había trabajado y nada había pescado,
le plació al Señor en Su infinita bondad y entrañable
misericordia para conmigo y muchos más,
enviar a nuestras tierras a Su verdadero y fiel mensajero, George Fox,
quien nos declaró el evangelio eterno.
Él dijo que teníamos una luz, a la cual hacíamos bien en estar atentos,
hasta que el día esclareciera,
y el lucero de la mañana se levantara en nuestros corazones;^
footnote:[2 Pedro 1:19]
lo cual fue buenas noticias para nosotros que por tanto tiempo habíamos
estado asentados en tinieblas y en la ceguera de nuestra mente.
En aquel día yo creí y recibí este testimonio, no porque era su testimonio únicamente,
sino porque en verdad era el testimonio de la Palabra de Dios,
que se volvió viva y poderosa en mí, y más cortante que toda espada de dos filos,
para cortar al hombre de pecado que por mucho tiempo había reinado en mi corazón;
y en verdad hubo una gran guerra muy larga antes de que el hombre fuerte fuera vencido,
para que uno más fuerte que él pudiera reinar.
Muchas y extrañas eran sus asechanzas,
y fuertes eran sus tentaciones para destruir esa pequeña medida de fe
que el Señor había forjado en mi corazón por el oír de la Palabra viva.
Pero a través de la fuerza de esta Palabra,
llegué a experimentar una medida de victoria sobre él y sobre su poder
(por el cual por mucho tiempo me había llevado cautivo a su voluntad);
y encontré que a medida que le prestaba atención a la Palabra de Fe,
que estaba cerca en mi corazón,
el día en verdad comenzaba a resplandecer cada vez más desde lo alto,
y el lucero de la mañana aparecía en mi corazón. Entonces
las densas tinieblas de la noche comenzaron a desvanecerse,
y la estrella de la mañana iba delante de mí,
hasta que me llevó a Aquel a quién había traspasado.
Y entonces un día de amargura vino sobre mí,
y me afligí como quien se aflige por un primogénito,
y el Señor "`ajustó el juicio a cordel`" en mí, "`y a nivel la justicia;`"^
footnote:[Isaías 28:17]
de modo que, por la mañana, decía "`¡Quién diera que fuese la tarde!
Y a la tarde ¡Quién diera que fuese la mañana!`"^
footnote:[Deuteronomio 28:67]
por la presencia formidable del Señor, y por el resplandor de Su majestad,
el cual se había levantado para castigar la tierra.
Pero en medio de todo, se me dijo, "`La caña cascada no quebraré,
y el pábilo que humea no apagaré, hasta que saque a victoria el juicio.`"^
footnote:[Mateo 12:20]
Creyendo en esto, esperé largamente en el Señor en el camino de Sus juicios,^
footnote:[Isaías 26:8]
hasta que sentí Su misericordia brotando hacia mí,
la cual en verdad fue manifestada en mí.

Entonces me convertí en un extraño para mis relaciones más cercanas;
porque mi padre y mi madre me abandonaron,
mis amigos y familiares se mantuvieron alejados de mí, maravillados,
y me convertí en un objeto de burla para muchos.
Fui golpeado terriblemente por aquellos que antes me habrían abrazado,
debido a que ahora temía al Señor, y temblaba ante Su Palabra.
Sí, y finalmente fui echado de todo lo que le brindaba comodidad a mi hombre externo,
de modo que durante un tiempo no tuve dónde recostar mi cabeza.
Por lo tanto, caminaba por lugares solitarios,
estando rodeado de muchas y terribles tentaciones, tanto interna como externamente;
en medio de lo cual, el Señor me habló para mi consuelo, y dijo, "`No temas,
yo estaré contigo y te cuidaré,`" lo cual refrescó mi alma y sostuvo mi espíritu.
Pero algunas veces, cuando miraba hacia afuera la prosperidad de los impíos,
mis pies casi se deslizaban, al considerar las muchas tribulaciones que me rodeaban.
Pero el buen Pastor me regresaba al camino con Su cayado,
y me hacía descansar entre las ovejas de Su prado,
donde encontraba delicados pastos y corrientes de
agua vivas que renovaban mis fuerzas como la mañana.
Y con el tiempo me volví fuerte en espíritu, y en la fe del Hijo de Dios,
por la cual obtuve victoria y libertad en mi propio corazón,
sobre eso que por mucho tiempo tuvo victoria sobre mí. Sin embargo, como dije antes,
mi padre y mi madre se mantenían lejos de mí,
y me convertí en un extraño para los hijos de mi madre;
pero el Señor se preocupaba por mí y me daba cada
vez más de Su buen Espíritu para dirigir mis pasos,
de modo que mis pies no se deslizaron.

A menudo, cuando estaba solo, la tentación era grande sobre mí, y me rodeaba fuertemente.
Sin embargo, me determinaba en mi pecho a seguir al Cordero a donde sea que fuera;
diciendo que cualesquiera que fueran los sufrimientos que me sobrevinieran,
nunca negaría la Verdad que el Señor me había manifestado tan claramente.
Entonces decidí ir a Londres y tomar algún empleo ahí entre los Amigos,
y en verdad algo en mí estaba muy apresurado por hacer esto.
Pero el Señor no quiso permitírmelo en ese tiempo,
sino que me aconsejó que me quedara y esperara hasta que Él me llamara.
Así que esperé por un tiempo, y finalmente la palabra del Señor vino a mí, y dijo,
"`Tú irás al sur para ser testigo de Mi nombre, por el cual sufrirás muchas cosas,
pero Yo estaré contigo.`"

Esto me pareció difícil al principio; y me hubiera gustado mucho más quedarme en casa.
Así que guardé esta palabra y la sopesé por un tiempo antes de contársela a alguien;
sin embargo, nunca llegué a la conclusión de desobedecer la palabra del Señor,
sin importar lo mucho que sufriera,
si veía que Él seguía requiriendo esto de mí. Finalmente
me sentía muy oprimido en espíritu día y noche,
de modo que ni mi sueño, ni ningún otro disfrute me era placentero,
hasta que cedí completamente a dejar todo para seguir la dirección
del Señor. Y cuando respondí plenamente a Sus requerimientos,
sentí Su brazo extendido sobre mí, y la luz de Su rostro me cubría;
de modo que dejar a mi padre y madre, mis amigos y conocidos, y toda mi tierra nativa,
fue muy poco en comparación al gozo que estaba puesto delante de mí.

Entonces un compañero de viaje fue preparado para mí, a saber,
Thomas Robertson de Westmoreland,
a quien Dios hizo que estuviera dispuesto a dejar a su esposa y a sus tiernos bebes,
para ir conmigo a la siega del Señor. Hicimos nuestro
viaje cerca del tiempo llamado la Pascua,
en el año 1655, y a través de muchos oprobios y una dura travesía a pie,
llegamos a Londres.
Después de quedarnos por un corto tiempo, sentimos ir más allá en dirección al sur.
Así que temprano por la mañana entramos en un bote y navegamos por el Támesis,
hacia Gravesend.
En el bote había muchos pasajeros con nosotros, quienes al percibir lo que éramos,
nos escarnecieron excesivamente y nos trataron vergonzosamente,
hasta que de repente vino un gran barco desplazándose
a toda vela con el viento a su favor,
y estaba a punto de atropellar nuestro barco.
Esto los aterrorizó tanto, que su risa se convirtió en miedo y horror,
lo cual los hizo temblar más que nosotros,
quienes antes habían reprochado bajo ese nombre.^
footnote:[El nombre Cuáqueros (Quakers) viene de la palabra "`quake`" en inglés,
que significa temblar.]
El peligro era tan inminente,
que el que dirigía el bote con gran dificultad logró salvarse a sí mismo.
Sin embargo, el Señor nos libró, y nos llevó a salvo a la orilla de Gravesend.

Desde Gravesend viajamos a Rochester,
donde el Señor puso en nuestro corazón que fuéramos a una reunión de bautistas.
Allí fuimos arrestados por soldados, y llevados ante el gobernador, quien nos examinó,
y al darse cuenta de que éramos compatriotas del norte,
dijo que no podíamos ir más allá sin un certificado,
y nos puso en prisión. Pero había ahí uno de nuestros propios compatriotas,
que era un soldado en ese lugar,
que dio testimonio de nuestra honestidad en nuestra propia región,
y entonces fuimos puestos en libertad.
Aún así, estábamos muy tentados a volver a nuestra propia región,
porque ellos nos hablaron de muchos peligros que nos vendrían si seguíamos adelante.
Sin embargo, no consultamos con carne y sangre,
sino que seguimos adelante en el nombre y poder de Dios, hasta que llegamos a Dover,
donde había una puerta abierta para nosotros,
y el Señor también abrió nuestras bocas para que declaráramos el evangelio eterno,
aunque en debilidad, miedo y en mucho temblor.
Por esto muchos fueron convertidos de las tinieblas a la luz,
y de la potestad de Satanás a Dios, para recibir remisión de pecados,
y herencia entre los santificados.^
footnote:[Hechos 26:18]

De ahí vinimos a Folkstone, donde algunos nos recibieron y creyeron,
y fueron reunidos para Dios.
Entonces fuimos a Hyde y a Rumney, donde varios recibieron nuestro testimonio,
a quienes les fue revelado el brazo del Señor,
a través del cual fueron recogidos de las montañas estériles a
los valles de humillación. En Lydd encontramos a Samuel Fisher,
un pastor de la congregación de los Bautistas,
con quién tuvimos una larga conversación. Él era un gran erudito,
y había sido anteriormente un sacerdote de la parroquia,
pero era uno que esperaba la venida del reino de Dios en poder.
Él recibió nuestro testimonio,
y estaba dispuesto a volverse un necio para poder llegar a ser sabio para salvación;
y de un maestro se volvió un estudiante, y, por lo tanto,
recibió sabiduría y entendimiento espiritual para convertirse en un predicador de justicia,
en la cual vivió y murió.

Después de su convencimiento vinimos a Staplehurst,
donde encontramos una congregación de "`Buscadores,`" así llamados,
entre quienes tuvimos un buen servicio.
Muchos de estos fueron convencidos, junto con su maestro, su esposa e hijos,
los cuales todos vivieron y murieron en la fe.
La cosecha se hizo tan grande, y los obreros eran tan pocos,
que tuvimos que separarnos uno del otro;
tomando cada uno ese cuidado y servicio que antes hacíamos entre los dos.
Pero después de que sentimos que habíamos cumplido con nuestro deber en ese condado,
vino a nuestro corazón pasar a través de los condados
del oeste a casi doscientas millas de distancia,
a proclamar el día aceptable del Señor en pueblos, ciudades y aldeas,
a lo cual nos entregamos.
Habiéndonos despedido uno del otro,
Thomas Robertson estaba a dos o tres días de viaje más adelante que yo;
pero ambos siendo extranjeros y peregrinos en la tierra,
y no teniendo a nadie que nos dirigiera sino solo el Señor,
pasamos por muchas dificultades externas.
Con todo,
fuimos suplidos con coraje y fuerza para soportar cualquier
cosa que el Señor pusiera ante nosotros.

Thomas Robertson pasó antes que yo por el condado de Sussex,
y solo por casualidad oí de él cuando estaba cerca de Chichester,
en una casa al lado del camino,
en la cual me detuve para tomar un poco de agua y calmar mi sed.
Una mujer empezó a contarme de un hombre que se había
detenido allí hacía dos o tres días,
y por su descripción entendí que era mi compañero.
Después de haber tomado agua, entré en la ciudad en el séptimo día en la noche,
y en el primer día, me sentí movido a ir a la reunión de los Bautistas,
donde declaré la palabra de la Verdad (aunque en medio de gran oposición),
cuyo testimonio algunos recibieron, y algunos rechazaron.

Pero después de poco de tiempo, el alcalde de la ciudad, habiendo oído de mí,
envió al alguacil para que me llevara ante él. Cuando me acerqué
a él sin hacer acepción de personas quitándome mi sombrero,
él se puso muy furioso, y mandó a buscar a uno llamado juez, quien, cuando vino,
me quitó el sombrero él mismo, y les ordenó a los hombres que me registraran,
diciendo que yo era un Jesuita, o uno que venía de Roma.
Ellos me hubieran enviado a la cárcel de inmediato,
pero el Señor les dio un giro a sus corazones;
de modo que después de hablar un poco me soltaron.
Luego de esto tuve una reunión en la posada,
y en la mañana siguiente dejé la ciudad y fui a Hampshire, y de ahí a Wiltshire,
y pasé a través de todo ese condado y llegué cerca
de Bristol antes de ver el rostro de un Amigo.
La fuerza de mi cuerpo estaba muy cerca de agotarse debido al viaje,
pero al reunirme con algunos Amigos, fui revivido y fortalecido,
y habiéndome quedado allí un poco de tiempo,
sentí la carga en espíritu de seguir adelante.
Yo entonces llegué a Bristol, y desde ahí a Exeter,
donde encontré a dos hermanos de mi condado en prisión. Yendo a visitarlos,
me encontré con mi compañero Thomas Robertson después de un largo viaje,
y nos quedamos en esa ciudad por un corto tiempo declarando la Verdad.
Pero las personas allí cerraron sus oídos y endurecieron
sus corazones contra la verdad y contra nosotros,
de modo que sacudimos el polvo de su ciudad como un testimonio contra ellos,
y nos fuimos nuevamente por Bristol, donde tuvimos algún servicio.

Desde ahí fuimos a Reading,
y nos quedamos por un poco de tiempo antes de ser movidos a ir a Basingstoke en Hampshire,
donde, a través de cierta dificultad,
obtuvimos una reunión. Pero antes de que todas las personas se reunieran,
el principal sacerdote y los gobernantes vinieron
e hicieron que nos arrastraran fuera de la reunión,
y entonces nos leyeron el juramento de abjuración; y debido a que,
por causa de conciencia, no podíamos jurar,
nos llevaron directamente a la prisión. Pero antes de ponernos en la celda,
nos separaron uno del otro, nos registraron y nos quitaron nuestro dinero,
lino y tinteros.
Ellos luego trataron de idear alguna manera de mantenernos separados,
pero al no tener dos celdas suficientemente malas,
nos echaron juntos en una celda sucia y angosta, y nos encerraron,
poniendo a dos hombres violentos con alabardas^
footnote:[Un arma que consiste en una hoja de hacha con
una punta afilada puesta en el extremo de una lanza,
normalmente alrededor de 1.5 a 1.8 metros de largo.]
para vigilarnos en la prisión durante toda la noche.
En la mañana los guardias fueron relevados y nosotros
fuimos encerrados sin ninguna libertad,
y se dio una orden de que, si alguno de nuestros amigos venía,
incluso a los terrenos que están antes de la puerta de la prisión a visitarnos,
fuera multado.
Ahí nos mantuvieron cerca de tres días antes de llevarnos nuestro dinero.
En todo ese tiempo no pudimos pedir ningún alimento o alguna cosa necesaria,
debido a que no teníamos nada de dinero,
y no podíamos comer el pan de ningún hombre de balde.
Cuando la gente de la ciudad clamó contra ellos, nos trajeron nuestro dinero;
pero entonces el carcelero demandó ocho peniques la noche
por una cama asquerosa que estaba en la habitación,
y cuando no pudimos satisfacer su deseo, él hizo que nos la quitaran.
Así que tomamos algo de paja,
y nos acostamos sobre ella durante todo el tiempo que estuvimos
allí. El carcelero tenía tableros clavados en las ventanas,
para que no pudiéramos ver la luz, y en la noche no nos permitía tener una vela o fuego.
Todo esto lo soportamos con paciencia hasta que se cansaron de su crueldad;
y por estas cosas varias personas, tanto en el pueblo como en el campo,
fueron convencidas de la Verdad, y permanecieron en ella.
Allí nos mantuvieron cerca de tres meses,
y luego en sus sesiones tribunales nos pusieron en libertad.

Cuando sentimos que habíamos cumplido con nuestro deber en ese pueblo,
fuimos movidos a pasar por Southampton, donde el Señor nos abrió una puerta,
y Su Palabra fue poderosa en nosotros para convertir
un remanente de las tinieblas a la luz,
el cual hasta el día de hoy todavía camina en ella.
Luego Thomas Robertson me dejó y se fue a Portsmouth, y allí dio testimonio de la verdad.
Muy pronto lo seguí hasta allá, me quedé cerca de diez días, y tuve un buen servicio.
En el primer día de la semana fui movido a ir a la
casa del campanario a testificar contra su adoración,
ante lo cual los sacerdotes y gobernadores fueron ofendidos; y en el segundo día,
mientras salía del pueblo, fui arrestado por soldados y llevado ante el gobernador,
quien deseaba enjuiciarme como un vagabundo,
pero no pudo encontrar evidencia suficiente para hacerlo,
así que me envió fuera de la ciudad con un alguacil.
Pero después de poco tiempo regresé,
y entonces recibieron la palabra de Dios con alegría,
y se estableció una reunión en esa ciudad.
Luego, con mucha dificultad fui a la Isla de Wight,
donde algunos fueron añadidos al rebaño del Señor,
y el Señor me libró de las manos de hombres perversos.
De ahí fui a Hampshire, y pasé de pueblo en pueblo, y de aldea en aldea.
El Señor estuvo conmigo,
e hizo que Su Palabra fuera poderosa en mi boca para volver a muchos a la justicia,
en la cual llegaron a ser establecidos.

Después de haber estado con estas personas por un tiempo, fui a Sussex,
donde tuve un buen servicio, y muchas personas fueron llevadas a la verdad.
Muchos recibieron la palabra de Dios con gozo, y se reunían frecuentemente;
y en estas reuniones Dios manifestaba Su presencia y poder en gran medida,
de modo que mi alma era refrescada entre ellos.
Pero después de poco tiempo, fui movido a regresar otra vez a Hampshire,
a regar las plantas tiernas en ese lugar.
Cuando hice esto, me sentí constreñido en espíritu a ir a Dorsentshire,
a Weymouth y a Melcomb-Regis;
y allí fui movido a ir a una casa de campanario a declarar contra un sacerdote asalariado.
Por hacer esto, fui arrestado y llevado a una asquerosa prisión bajo el suelo,
donde no tenía ni cama, ni fuego, ni nada donde sentarme excepto una piedra;
y había un montón de excremento en una esquina de la celda,
y algo de paja asquerosa donde algunos marineros se habían acostado.
Ahí me mantuvieron dos o tres días;
pero desde mi celda podía mirar hacia arriba y ver a las personas en la calle,
y ahí tuve un buen servicio, y prediqué la Verdad la cual ablandó muchos corazones.

Desde ahí fui enviado a Dorchester, a la cárcel del condado,
donde había una terrible enfermedad que algunos llamaban la plaga,
la cual mató a la mayoría de los prisioneros.
Pero el Señor estaba conmigo en ese lugar y me guardó en su puño,
de modo que ni un solo cabello de mi cabeza fue herido.
Ahí me mantuvieron por once semanas, donde encontré mucho servicio para el Señor,
convenciendo y confirmando a muchos en la Verdad,
en la cual ahora han encontrado descanso para sus almas.

Cuando llegué a esa prisión, encontré a mi querido hermano Humphrey Smith,
quién se había contagiado en la prisión y estaba cerca de morir.
El Señor me permitió serle de gran ayuda,
porque él no estaba dispuesto a recibir nada que no viniera de mí,
y el Señor lo levantó de nuevo.
Joseph Coale y William Bayly también eran prisioneros en ese lugar,
pero todos fuimos preservados y librados por el brazo fuerte y poderoso de Dios.
Porque con el tiempo el Señor me libró de ese encarcelamiento, y mientras estuve allí,
me preservó de esa violenta enfermedad que mató a muchos en un corto tiempo,
asegurándome que ni un solo cabello de mi cabeza perecería sin Él,
cuya promesa fue cumplida completamente.
Porque, aunque corrí muchos riesgos de enfermarme en esa prisión,
aparte de la contagiosa enfermedad, aun así,
nunca estuve mejor o más sano que cuando estuve ahí;
bendito y alabado sea el nombre del Señor para siempre.

Cuando fui puesto en libertad, volví a trabajar en la viña del Señor,
y llegué a Weymouth y Melcomb-Regis, desde donde había sido enviado a prisión,
y allí hice un buen servicio para el Señor entre
Su rebaño. Al sentirme libre de ese lugar,
me fui en paz, y llegué a Corsetown en la Isla de Purbeck, donde fui resistido,
y por la fuerza de hombres armados fui mantenido fuera del pueblo,
porque los habitantes decían que tenían miedo de mí,
ya que sabían que venía de estar entre tantas personas infectadas en la prisión.
No estando dispuesto a poner a ninguna persona en peligro entre ellos,
me fui y llegué a Poole, donde fui recibido con alegría,
y allí continué algunos días en la labor del evangelio,
confirmando aquellos que habían oído la palabra de Dios y creído. Desde ahí pasé a Ringwood,
donde encontré a unos pocos que creyeron en la verdad.
Me esforcé entre ellos para establecerlos en la fe,
la cual había sido engendrada en sus corazones por la Palabra de Dios.
Luego fui a Southampton, donde había laborado anteriormente,
y me refresqué mucho entre las plantas tiernas de Dios,
las cuales se regocijaron y alabaron a Dios por haberme
librado de esa peligrosa prisión mencionada anteriormente.
Prediqué la palabra de Dios con ánimo pronto,
y tuve muchas reuniones grandes y preciosas allí, y en el condado vecino;
y la Palabra del Señor creció, y muchos llegaron a creer en la Verdad.

En Southampton fui movido a ir a la casa de campanario, donde un tal Nathaniel Robinson,
un sacerdote independiente, estaba hablando sobre una adivinación de su propio cerebro.
Después de que había terminado,
le pedí que me escuchara decir unas pocas palabras en el temor de Dios;
pero él huyó y me dejó a merced de sus violentos oyentes,
quienes con violencia me arrastraron fuera de su sinagoga.
Entonces el mencionado Nathaniel Robinson hizo que
los gobernadores de ese lugar me enviaran a prisión,
donde me mantuvieron bajo un estricto estado de confinamiento;
y cuando alguno de mis Amigos venía del campo a visitarme, abusaban de ellos,
y los trataban vergonzosamente en su posada,
y en las calles también. Un tal Edward Southwood, siendo un soldado en el ejército,
y teniendo el permiso de sus oficiales vino a visitarme;
fue detenido por ellos en la posada, le quitaron sus armas,
y no le permitían venir a la prisión. Pero el Señor
lo preservó de toda la crueldad de ellos,
y le dio paciencia para soportar lo que se les permitió infligirle.
Ellos solo permitieron que muy pocos vinieran a mí, de hecho,
apenas aquellos que iban para llevarme las cosas necesarias;
todo lo cual sufrí hasta que el Señor me puso en libertad de todas sus crueldades.

Entonces comencé nuevamente a trabajar en la siega del Señor,
y en verdad Él estaba conmigo,
y me dio poder para soportar cualquier cosa que Él permitiera que me aconteciera.
Fui movido a ir a la Isla de Wight, y me propuse abordar un barco en Portsmouth,
pero fui detenido por el gobernador.
Entonces volví otra vez a Southampton, y de ahí fui a Hurstcastle,
donde tuve una conversación con algunos Bautistas; y ellos,
entendiendo cuál era el lugar al que pretendía ir, después de haber zarpado,
me traicionaron y me entregaron a un oficial,
quien hizo que el capitán de la nave me llevara a la orilla otra vez.

Ahí estaba sin ninguna esperanza de encontrar un pasaje,
y me vi obligado a regresar a través del bosque esa noche con mucha lluvia hasta Limington.
Pero allí procuré un pasaje en un pequeño bote que salía con antorchas.
En la noche, como a las diez u once, arribamos a la Isla, y me alojé en una posada.
En la mañana fui a Newport, su pueblo principal,
donde los profesantes de religión eran ricos y estaban llenos,
y rechazaron el consejo de Dios,
y menospreciaron a Su mensajero enviado a ellos con mucho amor.
Declaré la palabra de Verdad entre ellos tal como fue impuesta sobre mí,
pero antes de salir de la Isla,
fui arrestado por los soldados y llevado al castillo en Cowes,
donde el gobernador me envió fuera de la Isla.
Pero no sintiéndome libre de mi deber en ese lugar, regresé después de poco de tiempo,
y laboré entre un pequeño remanente que había sido reunido,
entre quienes sufrí muchas aflicciones.
En esa Isla fui encarcelado en una prisión asquerosa y fría,
que estaba en la calle principal de su pueblo más grande, donde tuve un buen servicio.
Y cuando ellos se dieron cuenta de esto, me pusieron en otra prisión,
en una celda trasera, donde no podía ni ver la calle,
ni ninguna persona podía venir a mí; y allí me mantuvieron un tiempo.
A pesar de todo, el Señor finalmente me libró, y se estableció una reunión en la Isla.

Alrededor de ese tiempo fue hecha una ley contra vagabundos
que era ejecutada perversamente contra los Amigos.
Muchos fueron tomados en sus propias casas o moradas,
y por esta ley sufrieron muchos hombres que tenían buenas propiedades, y algunos,
se decía, fueron arrestados en la parroquia misma en que nacieron.
Cuando entré a Southampton,
e iba a ver a algunos Amigos que habían sido puestos en la cárcel,
fui arrestado por los oficiales,
y de forma muy abusiva fui arrojado de cabeza en una jaula.
Sin ninguna averiguación adicional,
el alcalde aprobó una orden de azotarme en un poste para azotes en el mercado,
la cual fue ejecutada por el verdugo de manera cruel.
Después de esto,
ellos me echaron en una carretilla y entre dos hombres me llevaron por las calles,
y entonces me lanzaron en una carroza,
y me sacaron por la puerta en la fría nieve y el clima helado,
y no me dejaron ni obtener comida ni el menor refrigerio.
Entonces me llevaron a la siguiente parroquia esa noche;
la orden que tenían requería que fuera llevado de parroquia
en parroquia hasta que llegara a la mía.

Después de que me había ido, el alcalde, cuyo nombre era Peter Seale,
profirió una amenaza contra mí, diciendo que, si alguna vez regresaba,
sería azotado por segunda vez, y quemado en el hombro con una letra R^
footnote:[Por "`Rogue`" en inglés que significa vagabundo o vagante]
del tamaño de un chelín;
pero los otros magistrados no estaban dispuestos
a unirse a él en la obra que había comenzado.
Al poco tiempo fui movido por el Señor a ir a Southampton otra vez, lo cual hice,
y tuve varias reuniones, y ningún hombre puso sus manos sobre mí;
y entonces en mi libertad volví a irme,
y trabajé en la obra del Señor. Luego sentí ir otra vez a Southampton.
Solo había estado allí por un poco de tiempo cuando el alguacil
me tomó y me llevó ante el alcalde antes mencionado,
que estaba furioso,
y me amenazó con ejecutar toda la severidad de la
ley sobre mí. Con el fin de cumplir su objetivo,
mandó a buscar a un juez del pueblo, pero este hombre siendo más moderado,
y no estando involucrado en los procedimientos anteriores,
lo desalentó de tal manera que se vio obligado a abandonar su obra,
y después de mucha alharaca me dejó ir.
Pero poco tiempo después, este alcalde fue infectado con disentería,
que ninguno de sus médicos pudo curar, así que muy pronto terminó sus días en miseria.
La mano del Señor también cayó sobre el alguacil,
que era el agente principal del alcalde en estos malvados procedimientos,
de modo que se vio obligado a salir del pueblo y también murió miserablemente.

Entonces tuve paz y libertad por un tiempo considerable,
hasta que el Rey Carlos II fue restaurado, ya que en el mismo año en que fue coronado,
fui arrestado en el camino a Petersfield en Hampshire,
y traído ante Humphrey Bennet y John Norton, llamados jueces,
donde me leyeron el juramento de lealtad.
Y debido a que por causa de conciencia no pude jurar,
ellos me condenaron y me enviaron a la prisión común de Winchester,
y me quitaron mi caballo.
Allí me mantuvieron hasta las sesiones de la corte,
donde me dieron la sentencia de __premunire__^
footnote:[Premunire era un juicio legal diseñado para privar de sus derechos
a los que se negaban a jurar lealtad de manera formal al Rey de Inglaterra.
Los que estaban bajo sentencia de __premunire__ eran considerados traidores de su patria.
Perdían todos sus derechos a tener propiedades o posesiones,
eran removidos de debajo de la protección del rey, y, a menudo,
eran encarcelados de por vida.]
por el juez Foster y Tyrrell, y me pusieron en prisión sin ninguna libertad,
y en la cárcel sufrí muchos abusos de parte de los
prisioneros y también por la complicidad del carcelero;
sin embargo, el rey me dio libertad por una proclamación,
y se les requirió a ellos que me devolvieran mi caballo,
y entonces viajé en el servicio de la Verdad por diferentes
condados por una temporada considerablemente larga,
hasta la primavera.

En el año 1662, estaba en una reunión en la casa del Capitán Thomas Luxford,
en Hurst Pierpoint en Sussex; y por la instigación de Leonard Letchford,
el sacerdote de ese lugar, fui arrestado y llevado ante Nisell Rivers, Walter Burrill,
y Richard Bridger, llamados jueces, quienes me leyeron el juramento de lealtad.
Y debido a que no podía jurar por causa de conciencia,
me enviaron a la prisión de Horsham, el día 28 del tercer mes, 1662,
donde permanecí hasta las sesiones de la corte,
donde recibí la sentencia _premunire_ por el juez Samuel Brown.

Por la instigación del sacerdote Leonard Letchford antes mencionado,
me mantuvieron prisionero sin ninguna libertad, y permanecí así por más de diez años,
sufriendo muchos abusos terribles en la prisión de parte de varios carceleros crueles;
pero la mano del Señor los alcanzó,
y cortó a varios de ellos mientras aún era prisionero allí. Estaba
entregado libremente a sufrir allí todos los días de mi vida,
si era la voluntad de Dios permitirlo,
ya que no veía ninguna manera de ser librado por el hombre,
en quién no puse mi confianza; más bien, con una confianza dada por Dios,
estaba determinado a esperar pacientemente todos los días de mi tiempo prefijado.

En el sexto día del mes séptimo, 1664, tomé a Mary Luxford como mi esposa,
quien era la segunda hija de Thomas Luxford, y de Elizabeth su esposa,
de Hurst-Pierpoint en el condado de Sussex.
Nos casamos en la prisión de Horsham,
después de haber estado bajo la sentencia de _premunire_ por dos
años y de haber sido mantenido como prisionero sin libertad,
en cuya prisión continué por ocho años y cuatro meses después de nuestro matrimonio,
todo lo cual ella soportó con mucha paciencia.
Ella era de padres honestos y respetables,
quienes la educaron estrictamente conforme a esa religión que ellos creían ser la verdadera,
y ella vivió en mucha sujeción a sus padres.
Aunque ellos creyeron y recibieron la verdad antes de ella,
ella tenía un respeto tan reverente hacia ellos,
que no quería presentarse delante de ellos con alguna vestimenta que sabía que no aprobaban,
y era modesta y cortés con los Amigos.
Pero poco tiempo después ella y su hermana menor
Cordelia estuvieron dispuestas a ir a una reunión,
donde ambas fueron convencidas y recibieron la verdad con amor;
y por ella recibieron poder para echar fuera las obras infructuosas
de las tinieblas y vestirse de las armas de la luz,
y muy pronto ellas fueron capacitadas para apagar los dardos de fuego del diablo,
que no eran pocos en aquellos días. En medio de todo,
el Señor misericordiosamente las guardó en la fe
y paciencia a través de muchas tribulaciones.

Y como el Señor, por Su mano, nos juntó,
así nos preservó juntos por el espacio de veinticuatro años en mucho amor y unidad,
como una ayuda idónea uno del otro.
Ella era una mujer bendita, y amaba al Señor y Su Verdad,
y caminó en ella hasta el fin de sus días. Ella aborrecía todo mal,
tanto en palabra como en obra, y andaba delante del Señor en mucha inocencia,
amando la paz y la unidad; porque era una mujer de un espíritu manso y quieto,
que amaba la justicia donde sea que apareciera.
Padecía muchas debilidades corporales, sin embargo, era madre de cinco niños sanos.

A ella le gustaba mucho leer noche y día, siempre que tuviera algo de fuerza física;
y cuando se acercaba el final de sus días,
ella estaba consciente de que su tiempo no sería largo, y me mencionó algo de ello,
porque estaba muy afectada por una continua tos tísica.
Cerca del final del décimo mes, 1688, ella se enfermó,
y fue empeorando a pesar de los muchos remedios que se buscaron para ella.
Ella soportó su enfermedad con mucha quietud y paciencia,
hasta el sexto día del siguiente mes once,
y luego partió de esta vida como una cordera en mis manos,
y fue a su descanso eterno en el seno del amor del Padre,
en cuyo amor se había deleitado en permanecer durante su vida.
Su recuerdo vive con todos los que realmente la conocían;
porque ella fue un buen ejemplo para muchos;
y dejó un testimonio de su inocencia e integridad detrás de ella,
cuya recompensa está ahora con ella.
Estaba en mi corazón escribir este breve testimonio de ella.

El primer hijo que tuvo murió, pero cuatro todavía viven y han crecido.
Los educamos en la Verdad en sus primeros años, y velamos sobre ellos en amor,
hasta que conocieron el poder de Dios en sí mismos, al cual nosotros los encomendamos,
y por el cual han sido preservados hasta este día, para mi gran consuelo.
Muchos días y años, con las rodillas dobladas y en secreto,
he orado a Dios delante del trono de Su gracia,
para que los guarde con Su poder del mal de este mundo,
y que dirija sus pasos en el camino de justicia,
que en una gran medida Él me ha concedido.
Bendito y alabado sea el nombre del Señor para siempre.
Que el Señor los preserve hasta el fin de sus días, en fe y en bien hacer.
Amén.

Pero volviendo a mi encarcelamiento--finalmente,
cuando menos esperaba mi libertad, el Señor hizo que sucediera,
y abrió el corazón del rey para que concediera mi libertad mediante una patente,
bajo el sello real,
junto con muchos más que estaban sufriendo en ese
momento por el testimonio de una buena conciencia.
En el tiempo de mi encarcelamiento, el sacerdote antes mencionado, Leonard Letchford,
demandó a mi esposa por su apellido de soltera por los diezmos de la tierra,
por los cuales había mantenido a su padre en prisión varios años,
y entonces la puso en prisión también. Y en la sesión
de la corte obtuvo un falso veredicto contra ella,
consiguió una orden y tomó los bienes que yo había comprado y por los que había trabajado
con mis propias manos mientras estaba en prisión. No nos dejó ni una cama para acostarnos,
ni ningún otro elemento necesario para ayudarnos en nuestro confinamiento,
incluso tomó la olla que habíamos tomado prestada
mientras éramos prisioneros para hervir nuestra carne.
Todo esto lo hubiera podido recuperar fácilmente a través de la ley,
cuando finalmente fui librado de la prisión, pero encomendé plenamente mi causa a Dios,
a quién le pertenece toda venganza.

En poco tiempo, mi suegro Thomas Luxford también fue puesto en libertad, a quién,
el antes mencionado Leonard Letchford,
había mantenido muchos años en prisión. Este sacerdote se jactaba
de habernos encerrado tan fuertemente que ni el rey podría librarnos.
Y si a nosotros apenas se nos concedía un poco de libertad, una vez al año,
para visitar a nuestras familias,
él buscaba la manera de multar al alguacil por haberlo permitido,
y así incitaba al carcelero a mantenernos confinados siempre.
También envió muchas solicitudes a los peores jueces,
a quienes él consideraba que estaban más perversamente prejuiciados contra nosotros,
tratando de añadir aflicción a nuestras cadenas;
pero vivió para vernos a ambos liberados de prisión para su gran tormento,
como él luego lo expresó de muchas maneras.

Después de salir de la prisión de Horsham,
me quedé con mi familia en ese pueblo como un año, y luego me mudé a Gatton en Surrey,
donde permanecí cerca de catorce años. Allí Robert Pepys,
el sacerdote de ese lugar me excomulgó, junto con mi esposa y empleados,
por no asistir a la casa del campanario, y después me demandó por diezmos.
Y por el valor de veinte chelines, emitió contra mí una denuncia de rebelión,
y entonces se apoderó de mis bienes hasta el valor de sesenta libras.
Me topé con muchos otros sufrimientos y pruebas allí,
pero el Señor estaba conmigo y de todos ellos me libró;
y Él me permitió hacer un muy buen servicio para Él en los alrededores del territorio,
y muchos fueron llevados al Señor, y establecidos en la fe del evangelio.

[.asterism]
'''

[.offset]
+++[+++Lo siguiente son extractos de dos tratados escritos por Ambrose Rigge
y publicados junto con varias epístolas no mucho después de su muerte:]

[.blurb]
=== Unas Pocas Palabras Respecto al Hombre en Su Estado Caído y Degenerado

Todos los hombres son por naturaleza hijos de ira, como está escrito (Efesios 2:3),
están caídos de Dios y de Su poder, y son plantas degeneradas de una vid extraña,^
footnote:[Jeremías 2:21]
que producen diariamente frutos malos en los que Dios no se deleita.
El corazón del hombre es corrupto, su mente es corrupta,
y cada parte y miembro de su cuerpo, desde la cabeza hasta la planta de sus pies,
está lleno de heridas, hinchazón y podridas llagas;^
footnote:[Isaías 1:6]
todo designio de su corazón es de continuo solamente el mal.^
footnote:[Génesis 6:5, 8:21]

Por lo tanto,
el hombre en la caída es un vaso completamente inútil para el uso o servicio del Señor,
y el Señor no tiene ninguna complacencia en él en ese estado,
porque es un esclavo de satanás,
llevado cautivo a su voluntad a deshonrar a su Hacedor en todas sus palabras y obras;
de modo que todo lo que hace y lo que produce en esta condición
solo sirve para promover el reino de satanás. A lo malo llama bueno,
y a lo bueno malo, pone la luz por tinieblas, y las tinieblas por luz,
y es tan falto de verdadero entendimiento como las bestias que perecen.
Es totalmente inconsciente de su Creador, y de Su camino, verdad y vida,
porque estas cosas se disciernen espiritualmente.
Es ajeno a la vida de Dios, al pacto de la promesa y anda sin Dios en el mundo,
en sus caminos y obras de tinieblas.
En verdad él "`trae la iniquidad con cuerdas de vanidad,`"^
footnote:[Isaías 5:18]
y se la bebe como el buey bebe agua, hasta que se llena, y la vomita otra vez.
En este estado él es comparado a un perro,
cuya naturaleza es vomitar lo que con codicia se traga; y a un cerdo,
cuya naturaleza es revolcarse en el lodo, como la cosa más placentera para su naturaleza,
hasta que se ha ensuciado completamente y se ha vuelto aborrecible a la vista.
Así es el hombre por naturaleza,
el cual se revuelve en el pecado y en la corrupción hasta
que se vuelve aborrecible ante los ojos del Señor,
y no está en condiciones de hacer ningún servicio para él,
hasta que vuelve a ser limpiado.
Por lo tanto, el Señor clamó a la casa de Israel, "`Lavaos y limpiaos;
quitad la iniquidad de vuestras obras de delante de Mis ojos,`" Isaías 1:16,
y luego dice, "`Venid a mí,`" verso 18.

En esta condición, la sabiduría del hombre es terrenal, carnal, animal y diabólica;^
footnote:[Santiago 3:15]
sin embargo por esta misma sabiduría caída busca
comprender los misterios celestiales de la eternidad,
sumergirse en los secretos del Todopoderoso,
erigir un modo de adoración en su propia voluntad y establecer una justicia propia.
Él orará, leerá, cantará y realizará muchos deberes en su propio celo ferviente,
aunque sin ningún entendimiento o conocimiento verdadero de Dios su Creador.

En este estado estaban los judíos que mataron y persiguieron al Señor de vida,
en su oscuridad e incredulidad, en una justicia propia que era como trapos de inmundicia,
y que nunca pudo cubrirlos de la ira del Todopoderoso.
Y a estos Cristo les dio muchas parábolas, diciendo "`que el que no naciere de nuevo,
no puede ver el reino de Dios`"^
footnote:[Juan 3:3]
y "`si no os convertís y os hacéis como niños, no entraréis en el reino de los cielos.`"^
footnote:[Mateo 18:3 LBLA]
Aunque ellos estaban pintados como una pared blanqueada, aun así,
eran necios y corruptos, y estaban ciegos y desnudos;
y por lo tanto el ay era pronunciado frecuentemente contra ellos,
a pesar de todo su celo y profesión de Dios y de Sus palabras.

Por lo tanto, oh hombre natural, quienquiera que seas tú, ya seas profesante o profano,
no hay diferencia entre tu profesión de religión y tu profanidad mientras
que continúes en tú estado no transformado y no hayas sido regenerado
ni creado nuevamente en esa imagen y naturaleza celestial que puede hacer
la voluntad y obra que es agradable a Dios.
Si quieres ser sabio, primero debes hacerte ignorante,
para que puedas llegar a ser sabio;^
footnote:[1 Corintios 3:18]
pero tú difícilmente soportarías esto,
porque estás enaltecido en el orgullo de tu corazón
en lo que piensas que haces para Dios.
Pero Dios no puede recibir un sacrificio aceptable de tus manos; porque,
aunque "`dieras tu primogénito por tu rebelión,
o el fruto de tus entrañas por el pecado de tu alma,`"^
footnote:[Miqueas 6:7]
sería "`como si degollaras un perro, y ofrecieras sangre de cerdo,`"^
footnote:[Isaías 66:3]
mientras tu corazón siga corrupto por el engaño del pecado.
Es contra _esto_ que Dios tiene una controversia,
y Él no hará paz hasta que la pared de separación sea derribada;
porque el pecado es lo que ha hecho la separación entre Dios y tu padre Adán,
y es la naturaleza que está en todos sus descendientes.

Por lo tanto,
este es mi consejo y recomendación para ustedes que
están en el estado no regenerado ni transformado,
alejados de Dios y ajenos en sus mentes a Su pacto de vida:
Si encuentran algún deseo en ustedes de volver al Señor que los ha hecho,
de que Él los salve del ardor de Su ira para siempre,
entonces __dejen sus propias palabras, obras y caminos,
y no se apresuren a correr antes de que su Hacedor
los guíe por la mano en la luz de Su Verdad,__
con la cual Cristo los ha alumbrado,^
footnote:[Juan 1:9]
la cual resplandece en su oscuro corazón,^
footnote:[2 Corintios 4:6]
para que no permanezcan en tinieblas, sino que reciban la luz de la vida.^
footnote:[Juan 8:12]

Escuchen la voz de Aquel que está a sus puertas y llama,
y desea que lo reciban en su corazón, el cual es Su trono,
sobre el cual Él debe sentarse como Rey.
Allí en sus corazones Él debe hacer la voluntad del Padre,
que es "`santificarlos por completo, espíritu, alma y cuerpo,`"^
footnote:[1 Tesalonicenses 5:23]
sin lo cual nunca podrán ser un vaso de honor para Él,
que manifieste Su alabanza y gloria en la tierra.
En verdad Cristo debe forjar Su propia justicia en ustedes por Su propia mano de poder,
y esta justicia debe cubrirlos eternamente.
Así que ustedes deben morir en Su cruz a su justicia propia y a
su injusticia (que ambas brotan de la semilla de enemistad,
en la cual Dios no tiene complacencia) antes de que puedan experimentar la paz de Dios,
que sobrepasa todo entendimiento, guardando sus corazones y sus mentes.
Ustedes verán que todo esto es verdad en el día de su visitación,
independientemente de cómo los falsos profetas ahora los persuadan de lo contrario.

Es algo duro para ustedes que todavía viven en la
plenitud de deleites y en los placeres de la carne,
hablar de morir a su justicia propia y a su injusticia
antes de que puedan vivir para Dios.
Pero, aunque sea como una copa amarga,
aun así deben estar dispuestos a beberla antes de que puedan probar la copa de bendición,
que es la comunión de la sangre de Cristo.^
footnote:[1 Corintios 10:16]
Ustedes deben sufrir con Aquel que murió en la cruz,
antes de que puedan experimentar la virtud de Su resurrección.
Deben despojarse del viejo hombre junto con sus hechos,
antes de que puedan revestirse del nuevo.^
footnote:[Colosenses 3:9; Efesios 4:22-24]
Deben limpiarse de la vieja levadura de malicia, y el odre viejo debe ser quebrantado,
antes de que puedan celebrar la fiesta de los panes
sin levadura como una pascua al Señor.^
footnote:[1 Corintios 5:7-8]

Estos son los pasos del rebaño,
en los cuales deben andar antes de que la justicia de Cristo se vuelva su justicia.
_En verdad,
ustedes deben comprar la Verdad con la pérdida de todo lo que es contrario a ella,
si alguna vez quieren realmente comprarla._
Esta es la Palabra del Señor Dios para ustedes,
que debe ser cumplida ya sea en o sobre ustedes.
Que ningún hombre los engañe con palabras vanas como por ejemplo
decirles que "`Dios no los ve así como están en pecado,
sino que solo los ve en Cristo.`"
¡Oh almas pobres, miserables y engañadas!
Este en verdad es el "`engaño de iniquidad,`"^
footnote:[2 Tesalonicenses 2:10]
que haría a Dios tan injusto como los hombres,
viendo al hombre como si estuviera en Cristo mientras todavía vive en
pecado y transgresión. No les presten atención a estas vanidades ilusorias,
no sea que abandonen su misericordia para siempre.^
footnote:[Jonás 2:8]
Porque por estas cosas ha venido la ira de Dios sobre los hijos de desobediencia.^
footnote:[Efesios 5:6; Colosenses 3:6]

"`El que dijere al malo: Justo eres, los pueblos lo maldecirán,
y le detestarán las naciones,`" Proverbios 24:24. Yo les digo,
Dios los mira tal como son; y Él no los justificará en pecado,
ni los tendrá por inocentes en transgresión, sino que "`herirá la cabeza de Sus enemigos,
la testa cabelluda del que camina en sus pecados,`" Salmos 68:21. Por lo tanto vuelvan,
vuelvan al Señor por medio de un pronto arrepentimiento, y "`besen al Hijo,
para que no se enoje, y caigan del camino de vida; cuando se encendiere un poco su furor.
Bienaventurados todos los que en Él confían,`" Salmo 2:12.^
footnote:[Reina Valera de Gómez]
No debo recubrirlos con lodo suelto, como los falsos profetas han hecho por muchos años,
clamando "`paz, paz`" mientras ustedes permanecen en impiedad,
a quienes el Señor les dice, "`No hay paz.`"^
footnote:[Jeremías 6:14, 8:11; Ezequiel 13:10, 16; Isaías 48:22; 57:21]

Y si ustedes todavía se alimentan de las algarrobas de los cerdos,
revolcándose en el cieno entre ellos,
y satisfaciéndose a sí mismos con una profesión de las palabras de los
santos conforme están escritas externamente en la letra de la Escritura,
mientras siguen siendo ajenos a esa vida en la que
vivieron los que las escribieron--entonces ¡oh,
sepan que esto no es más que la paja en comparación con el trigo!
Porque el trigo es la posesión interna de la vida y justicia del Hijo de Dios.
Por lo tanto, vuelvan a la casa de su Padre, a esa luz en la que Dios habita,
1 Timoteo 6:16. Entonces Él se encontrará con ustedes, los recibirá,
se regocijará con ustedes, y los satisfará con suficiente pan,^
footnote:[Lucas 15:17-20]
sí,
con el becerro gordo (Su propio becerro crucificado) del cual ustedes
se alimentarán y nunca más tendrán hambre.

El Señor me pidió que pusiera esto delante de todos
los que todavía están en Babilonia y Egipto,
para que puedan huir de ella y escapar de sus pecados, y no reciban parte de sus plagas,
como está escrito, Apocalipsis 18:4. Por lo tanto que su risa se convierta en lloro,
y su gozo en tristeza, "`pues Dios se ha vestido con ropas de venganza,
y se cubrió de celo como de manto,`" Isaías 59:17;
y ninguna cosa inmunda permanecerá delante de Él. Él pagará
a cada hombre conforme al fruto de sus hechos.
Por lo tanto, mientras tengan un poco de tiempo, valórenlo,
no sea que pase el día de Su visitación, y el día de ira venga sobre ustedes,
así como un ladrón en la noche.^
footnote:[1 Tesalonicenses 5:2]

[.signed-section-signature]
Ambrose Rigge

[.asterism]
'''

[.blurb]
=== La Gracia Interna y Espiritual de Dios Exaltada como el Único Maestro del Hombre.

A toda la humanidad que está sobre la faz de la tierra le
corresponde buscar esas cosas que conducen a su eterna paz,
felicidad, tranquilidad y descanso con Dios,
cuando el tiempo en este mundo ya no sea más. Sin embargo,
tales son las asechanzas y estratagemas de la serpiente
y adversario de la felicidad del hombre,
(el cual prevaleció sobre Adán y Eva en el principio,
logrando quebrantar el pacto de vida que Dios había hecho con ellos),
que él prevalece sobre la mayoría de su posteridad en este día, haciendo que desprecien,
desestimen y tengan por poco eso que debería "`traer su salvación,`"^
footnote:[Tito 2:11 Reina Valera 1602 Purificada]
y llevarlos al conocimiento del camino que conduce a ella,
lo cual es la gracia interna y espiritual de Dios que fue
manifestada y dada a conocer por el segundo Adán,
Cristo Jesús.^
footnote:[Juan 1:17]

Esta es la raíz, sustancia y vida de toda religión verdadera en el mundo,
y sin ella no hay ninguna religión verdadera en la tierra;
porque Dios la ha dado para que traiga salvación hasta los fines de la tierra,
y para que sea un maestro perfecto y suficiente para toda la humanidad.^
footnote:[2 Corintios 12:9]
Esta gracia era el maestro de los santos en la ministración del evangelio,
y lo que "`traía su salvación.`"^
footnote:[Tito 2:11 LBLA]
Y mientras que las naciones y pueblos no escuchen
y aprendan de este maestro interno y espiritual,
nunca aprenderán de Él a renunciar a la impiedad y a los deseos mundanos,
ni a vivir de manera sobria y justa en este mundo.
Este es el Cristo de Dios, manifestado espiritualmente en la carne mortal,
para deshacer las obras del diablo; y todos los que no quieran escucharlo, recibirlo,
seguirlo y obedecerlo, nunca recibirán poder para convertirse en siervos o hijos de Dios,
sino que permanecerán todos sus días en hiel de amargura y en prisión de maldad,
amontonando ira para el día de la ira y de la revelación del justo juicio de Dios.

Cristo manifestado de esta manera,
se convierte en el autor de eterna salvación en todos los que creen,
y es ese gran misterio que había estado escondido
de nuestros antepasados por muchas generaciones.
Dondequiera que sea recibido, escuchado y obedecido,
Él manifiesta Su fuerza y poder en el alma,
que es mayor que la fuerza y poder del enemigo.
Allí Él ata al hombre fuerte (que por mucho tiempo ha dominado los corazones de muchos),
lo echa fuera,
establece Su trono y gobierna hasta que haya puesto a todos Sus enemigos bajo Sus pies;
y de esta manera Cristo se convierte en la esperanza de gloria de todo Su pueblo,
Colosenses 1:27. Pero el que no lo reciba,
escuche y obedezca en Su manifestación espiritual, ni se entregue a ser gobernado por Él,
no puede ser Su discípulo,
ni recibir poder de Él para convertirse en hijo y siervo del Dios vivo.

Aunque muchos profesen Su nombre en palabras,
y tengan la apariencia de cristianos en la carne, aun así,
son ajenos a la verdadera vida cristiana, y están sin Dios en el mundo,
muertos en delitos y pecados, y nunca podrán levantarse de la tumba de corrupción,
a menos de que crean y esperen la manifestación de Su poder
"`que hace todas sus obras en ellos y por ellos,`"^
footnote:[Isaías 26:12]
cuyo poder solo es experimentado a través de Su luz y gracia interna.
Es solo por medio de esto que el hombre puede volverse hechura de Dios,
creado nuevamente en Cristo Jesús para buenas obras.^
footnote:[Efesios 2:10]
Esta es la nueva creación, en la que el hombre recibe la imagen de Dios, es decir,
la imagen de justicia que se perdió en el primer Adán.

Porque el apóstol dice, "`Como el cuerpo sin espíritu está muerto,
así también la fe sin obras está muerta,`" Santiago
2:26. Porque es por medio de las obras de justicia,
engendradas en el hombre por Jesucristo (el cual es la Justicia de Dios),
que se manifiesta la fe que salva.
Y ningún hombre puede tener verdadera fe en Cristo, si no manifiesta,
las obras de la justicia de Cristo en su vida y conducta.
Porque el fruto y efecto de la fe salvadora en el
hombre es una justicia y santidad interna,
por la cual el corazón, el alma y el espíritu del hombre son santificados para Dios;
y sin esta santidad ningún hombre verá al Señor.^
footnote:[Hebreos 12:14]
Por lo tanto, el hombre debe seguir a Cristo en la obra de Su Justicia, y aprender de Él,
y llevar Su cruz--no una cruz de oro, plata, madera o piedra,
sino eso que crucifica sus amados deseos y placeres,
sin la cual el hombre nunca podrá llevar Su corona.
Porque aunque el hombre por su propio poder no puede lograr su propia salvación, aun así,
a medida que cree y sigue a Aquel que Dios ha dado por Jefe y por Maestro a Su pueblo,^
footnote:[Isaías 55:4]
recibirá poder de Él para hacer cualquier cosa que Él mande,
y será salvado por Él del pecado y la transgresión; pues Su nombre es Jesús,
porque Él salva a Su pueblo _de_ sus pecados,
Mateos 1:21. Y cualquiera que no sea salvado por Él de sus pecados aquí en esta vida,
nunca podrá escapar de la ira y del furor del Todopoderoso en la por venir,
ni de esa muerte que es la paga del pecado.^
footnote:[Romanos 6:23]

Ahora bien, el medio que Dios ha designado para traer Su salvación a toda la humanidad,
es Su gracia y verdad internas y espirituales que vienen por medio de Jesucristo,
Juan 1:17. A medida que toda la humanidad escuche y obedezca a este maestro interno,
será salva por medio de Él;^
footnote:[Efesios 2:8]
porque Él tiene la virtud y el poder para generar justicia en el hombre,
y para deshacer toda injusticia.

Es como la pequeña levadura escondida en la harina,
de la que Cristo habló en Mateos 13:33; que cuando sea recibida y obedecida,
leuda toda la masa del hombre hasta convertirla en sinceridad y verdad.
Ella es la perla preciosa, escondida en el campo (el cual es el mundo,
puesto en el corazón del hombre^
footnote:[Eclesiastés 3:11 Reina Valera de Gómez]);
allí el hombre prudente cava profundamente, y hallándola,
vende y deja todos sus deseos para comprarla.
_El hombre solo puede comprar esta perla al negar
y perder todo lo que es contrario a ella;_
el oro no la comprará, y la plata es escoria en comparación con ella;
su precio es mayor a los rubíes; y por eso el hombre sabio dijo, "`compra la verdad,
y no la vendas.`"^
footnote:[Proverbios 23:23. Véase también Apocalipsis 3:18]
Y ningún hombre realmente puede decir, "`Mi Amado es mío,
y yo soy Suyo,`" a menos que compre este tesoro por medio de dejar todo lo que
es contrario a él. Esta es una palabra dura para la mayor parte de la humanidad,
ya que tiene muchas posesiones, amados deseos y placeres vanos que dejar,
que son tan importantes y queridos para ella como su mano u ojo derecho.
En verdad, esto hizo que el joven, del cual Cristo habló en Mateos 19, se fuera triste,
porque tenía muchas posesiones; respecto a lo cual el Hijo del Hombre dijo,
"`difícilmente entrará un rico en el reino de los cielos,`" y,
"`es más fácil pasar un camello por el ojo de una aguja,
que entrar un rico en el reino de Dios.`"^
footnote:[Mateo 19:23-24]

Aquí es revelado el misterio de la piedad,
que el hombre natural no puede ver ni percibir,
porque está escondido de los sabios y entendidos
del mundo y es revelado a los niños y a los pequeñitos.
Los hombres importantes y orgullosos de este mundo son demasiado grandes
para entrar por esta puerta o para andar en este camino estrecho,
y la predicación de la cruz de nuestro Señor Jesús es locura para ellos.
Pero todos los verdaderos discípulos y seguidores de Jesucristo deben tomar la cruz,
y ser crucificados por ella al mundo, y el mundo para ellos.^
footnote:[Gálatas 6:14]

Por lo tanto, dejen de lado todas sus cruces imaginarias de oro, plata madera o piedra;
porque no tienen ningún valor,
ni ninguna virtud en ellas para crucificar ni un solo deseo que combata en sus miembros.
Porque, aunque ustedes puedan llevar estas cruces falsas en sus pechos, aun así,
sus amados deseos yacen allí también sin ser crucificados,
los cuales batallan contra sus almas,
y prevalecen tanto que dan a luz el pecado en palabra y acción; y el pecado,
siendo consumado, da a luz la muerte, Santiago 1:15.

La verdadera cruz de Cristo es el poder de Dios que obra en todos los que creen.^
footnote:[Romanos 1:16; 1 Corintios 1:18]
"`Por cuanto agradó al Padre que en Él habitase toda plenitud,
y por medio de Él reconciliar consigo todas las cosas,
así las que están en la tierra como las que están en los cielos,
haciendo la paz mediante la sangre de Su cruz,`" Colosenses 1:19-20. Eso,
a través de lo cual los antiguos Cristianos fueron crucificados al mundo,
y el mundo para ellos, era la cruz de Cristo llevada espiritualmente.^
footnote:[Gálatas 6:14]
Pero desde que la verdadera vida y Espíritu del cristianismo
han sido dejados de lado y apagados,
el conocimiento de esta cruz se ha perdido.
Y aunque muchos han levantado una imagen de ella,
se han vuelto ajenos y enemigos a la verdadera cruz de Cristo,
como los Judíos y Fariseos lo eran en el día del evangelio.

El conocimiento del misterio de la salvación de Dios
debe ser abierto y manifestado por el don de Dios,
es decir, por Su gracia y Espíritu, a medida que es recibido y obedecido;
"`Porque ¿quién de los hombres sabe las cosas del hombre,
sino el espíritu del hombre que está en él? Así tampoco nadie conoció las cosas de Dios,
sino el Espíritu de Dios,`" 1 Corintios 2:11. Con este Espíritu
en su interior el profeta Isaías buscó al Señor,
Isaías 26:9. Y con el Espíritu de la Verdad en el
interior toda la humanidad debe buscar al Señor,
si es que quiere encontrarlo y conocer Su obra.
Esta era la ceguera de los judíos en su día, a saber, su resistencia al Espíritu de Dios,
Hechos 7:51. A pesar de que ellos mantenían su adoración
de templo con sus ofrendas y sacrificios,
aun así, por resistir al Espíritu de Dios en sí mismos,
se volvieron más ciegos que el hombre con un espíritu inmundo que le dijo a Cristo:
"`Sé quién eres, el Santo de Dios.`"^
footnote:[Marcos 1:23-24; Mateo 8:29.]

_La causa principal de todo error en el mundo es el
haber dejado el Espíritu de Verdad en el interior,_
el Consolador que ha sido enviado según la promesa de Cristo.^
footnote:[Juan 14:16-17, 26.]
Este Consolador cuando es escuchado, recibido y obedecido, lleva a toda verdad,
y es un guía perfecto designado por Dios para toda la humanidad,
para llevarlos al conocimiento de la salvación de Dios.

Cristo en el interior, la esperanza de gloria,
fue un misterio que había estado oculto por los siglos y edades,
pero que ha sido manifestado a los santos en el día del evangelio.^
footnote:[Colosenses 1:26-27]
Y cuando los sabios judíos profesantes habían rechazado Su aparición externa
en la carne (a quienes Él vino primero y se ofreció a Sí mismo),
Él se manifestó como "`una luz para los gentiles,
para salvación hasta lo postrero de la tierra.`"^
footnote:[Hechos 13:47; Isaías 49:6]
Y ahora,
es esta aparición interna y espiritual de Cristo a la que los principales
sacerdotes y cristianos mundanos se oponen y rechazan en nuestro día,
al no estar dispuestos a que Él gobierne espiritualmente
en los corazones y conciencias de Su pueblo.
En lugar de ello, llaman a la luz verdadera (que es Su vida y aparición espiritual,
Juan 1:4) una "`linterna oscura,`" o una "`conciencia natural;`"
y así invalidan Su Palabra viva por su religión tradicional,
que está establecida en la voluntad e ingenio del hombre.
Y así, cada día, crucifican de nuevo para sí mismos al Señor de Gloria,
exponiéndole a vituperio;^
footnote:[Hebreos 6:6]
porque en verdad, cada palabra y obra impía es como una lanza que hiere al Señor.

Pero ningún hombre que no haya sido bautizado en la muerte de Cristo,^
footnote:[Romanos 6:3]
es decir, que no esté muerto al pecado, puede ser un verdadero cristiano.
Este es el verdadero bautismo espiritual,
del cual el bautismo con agua de Juan era solo una figura y sombra,
que sirvió para preparar el camino.
Tampoco ahora es un Cristiano evangélico el que lo es exteriormente;
ni es el bautismo el que se hace exteriormente en la carne;
sino que es Cristiano el que lo es en lo interior,
y el bautismo es el del corazón y en espíritu.^
footnote:[Una referencia a Romanos 2:28-29,
donde Pablo usa estas mismas palabras en relación a la circuncisión interna y externa.]
Porque ni el bautismo (como una experiencia externa), ni la falta de bautismo vale nada,
sino una nueva creación,^
footnote:[Una referencia a Gálatas 6:15,
donde de nuevo las mismas palabras son usadas en relación a la circuncisión.]
creada nuevamente en Cristo Jesús para buenas obras, para que vivamos en ellas.^
footnote:[Efesios 2:10]
Esto es Cristianismo en su antigua gloria y pureza,
el cual es restaurado y experimentado al recibir,
oír y obedecer la gracia interna y espiritual "`que trae salvación.`"^
footnote:[Tito 2:11-12]
Y a menos que los Cristianos externos empiecen a
escuchar y a obedecer esta gracia interna y espiritual,
nunca podrán conocer o experimentar la salvación de Dios;
porque todo lo que es externo es apenas una cáscara y sombra,
y es como la paja para el trigo.
Porque,
así como la aparición y manifestación de Cristo en la sustancia
de la ministración del evangelio es interna y espiritual,
así es Su bautismo, y también Su cena, y todas Sus ordenanzas;
de modo que todos los que verdaderamente "`comen Su carne y beben Su sangre,
permanecen en Él,
y Él en ellos,`" Juan 6:56. Porque es el Espíritu el que
da vida a todos los que son vivificados por Él;
la carne para nada aprovecha, versículo 63.

Las palabras que Cristo hablaba eran espíritu y vida,
y Él hablaba de cosas espirituales en un misterio.
Los judíos murmuraban por esto, y muchos de los discípulos se ofendieron,
mirando lo externo,
como muchos que no disciernen Su carne o sangre hacen en nuestro día. Y aunque
los hijos de Israel en el desierto comieron del maná que caía cada día del cielo,
aun así, debido a que era solo un pan externo, ellos morían, Juan 6:49. Por lo tanto,
en la dispensación del Evangelio,
no es el pan externo el que nutre el alma y le da vida eterna, sino el maná espiritual,
que se recibe cuando el Hijo de Dios permanece en el hombre, y el hombre en Él,
versículos 56-57. Los que comen Su carne y beben Su sangre de esta manera,
tienen vida eterna, y Él los resucitará en el día postrero,
versículo 54. Esta es la sustancia o cumplimiento
de todos las sombras y representaciones externas;
porque la carne, el pan,
o la copa externos para nada aprovechan en cuanto a la alimentación del alma.
Pero donde Cristo haya aparecido y se encuentre levantado en el espíritu,
Su pan y copa espiritual anuncian Su resurrección en el alma.
Aquí aquellos que son vivificados y resucitados por Él,
viven por toda palabra que sale de Su boca.
Y cuando de este modo son hechos partícipes de Su resurrección,
la segunda muerte no tiene potestad sobre ellos.

Esto fue representado cuando Moisés levantó la serpiente en el desierto,^
footnote:[Juan 3:14, Números 21:9]
porque así es necesario que el Hijo del Hombre sea levantado en el alma,
para que todos los que hayan sido mordidos por la
serpiente espiritual puedan verlo a Él y ser sanados.
Porque,
aunque Él fue convertido en un sacrificio a Dios por los pecados de todo el mundo,
para que a través de Su resurrección y vida el mundo entero pueda ser salvo, aun así,
ningún hombre tiene parte con Él, o con Su resurrección,
si en este mundo no es lavado por Él de su inmundicia.
Porque la purificación, que todo verdadero creyente cristiano reconoce,
es por la sangre de Jesucristo que limpia a los hombres de sus pecados;
y nadie experimenta el beneficio de esto, sino aquellos que caminan en la luz.
"`Si decimos que tenemos comunión con Él, y andamos en tinieblas, mentimos,
y no practicamos la verdad; pero si andamos en luz, como Él está en luz,
tenemos comunión unos con otros,
y la sangre de Jesucristo Su Hijo nos limpia de todo pecado.`"^
footnote:[1 Juan 1:6-7]
Aquí está el pacto en el que el beneficio,
la virtud y la eficacia de la sangre de Jesús se conocen y experimentan hasta este día,
y así será a lo largo de todas las generaciones.
Y por esta razón la luz verdadera, o gracia de Dios,
ha "`alumbrado a todo hombre que viene a este mundo,`"^
footnote:[Juan 1:9 Reina Valera de Gómez]
para que todos puedan recibirla y andar en ella,
y de este modo ser hechos testigos vivos de la sangre de
Jesucristo que los limpia de todos sus pecados.

Si los hijos e hijas de los hombres hubieran experimentado este lavamiento,
no tendrían la necesidad de imaginar un purgatorio externo para limpiarlos de sus pecados;
porque la sangre de Jesucristo (conocida y experimentada
en espíritu) es suficiente para santificar y hacer que todos
los que andan en la luz sean verdaderamente limpios en cuerpo,
alma y espíritu.
Porque como el relámpago que sale del oriente y se muestra hasta el occidente,
así es el resplandor del Sol de justicia en el alma del hombre.
Pero hasta que el día amanezca y el lucero de la mañana se levante en el corazón,
nunca podrá experimentarse el levantamiento del glorioso
Sol de justicia que trae salvación en sus alas.
Y en verdad, antes de que Su levantamiento sea conocido y experimentado,
toda predicación es vana, la fe del hombre es vana,
y las personas permanecen en sus pecados.
Porque sin esta obra interna,
ningún hombre puede llegar a ser semejante a Él en su muerte,
ni volverse partícipe de Su resurrección; sino que vive y muere en sus pecados,
y a donde Cristo va, este hombre no puede ir.^
footnote:[Juan 8:21-24]

Por lo tanto, que todos reciban la advertencia,
y presten atención a la luz verdadera y gracia interna y espiritual de Dios,
y se entreguen a sus enseñanzas,
para que puedan recibir entendimiento de Dios para
conocer los misterios del reino de justicia.
Porque estas cosas están escondidas de los sabios y de los entendidos del mundo,
que se glorían en lo que estudian con sus cerebros,
en las artes humanas y en la literatura,
y en los conocimientos naturales que se encuentran en la voluntad y sabiduría del hombre.
Pero la sabiduría divina nunca ha sido dada a los
hijos de los hombres mediante cosas como estas.
La verdadera sabiduría es el don de Dios,
dado por el Espíritu a los que aman y temen al Señor. Los
secretos del Señor son manifestados diariamente a estos,
y ellos no carecen del conocimiento de los misterios del reino de justicia,
sino que pueden declarar a otros lo que Dios ha hecho por sus almas,
y lo que han probado y palpado de la Palabra de vida eterna.^
footnote:[1 Juan 1:1]
Estos son "`ministros competentes del nuevo pacto, no de la letra, sino del Espíritu.`"^
footnote:[2 Corintios 3:6]

Y hasta el momento en que las naciones y todas las personas se vuelvan a este don de
Dios (que ha sido sembrado universalmente en todo tipo de suelo) y lo reciban,
nunca podrán ver o andar en el camino de vida.
Porque el hombre no puede experimentar la vida que viene
de la gracia sin primero someterse voluntariamente a ella,
y ser bautizado espiritualmente por ella en la muerte de Cristo.
Aquí se encuentra el verdadero Cristiano que lo es en lo interior,
cuya alabanza no viene de los hombres, sino de Dios.^
footnote:[Romanos 2:28-29]
Porque el verdadero bautismo cristiano es una muerte al pecado,
y un nuevo nacimiento para la justicia, y solo aquellos que son bautizados así,
son verdaderos cristianos.
Acerca de esto, el Hijo de Dios le dijo a Nicodemo, que "`el que no naciere de nuevo,
no puede ver el reino de Dios,`" Juan 3:3. Y versículo 5,
que "`el que no naciere de agua y del Espíritu,
no puede entrar en el reino de Dios,`" es decir,
del agua espiritual por medio de la cual el Espíritu Santo limpia
a los verdaderos creyentes y los lleva a andar en vida nueva.

Ahora bien, todos ustedes que viven contentos en señales visibles y externas,
y desprecian y descuidan la substancia--es decir,
la gracia interna y espiritual que debe traer su salvación--el enemigo los ha engañado,
evitando que oigan, reciban y obedezcan a su verdadero maestro.
Por esto ustedes siempre están aprendiendo,
pero nunca pueden llegar al conocimiento del Espíritu de la Verdad en sus corazones,
que es dado por Dios para guiarlos a toda verdad.^
footnote:[Juan 16:13]
Este es el Consolador que Cristo prometió que permanecería para siempre;^
footnote:[Juan 14:16-17]
que Cristo dijo que había morado con Sus discípulos, y que estaría en ellos.^
footnote:[Juan 14:17]
Este Consolador, el Espíritu de Verdad, se ha levantado en nuestro día,
y se ha manifestado en todos los creyentes verdaderos con el siguiente propósito:
"`Deshacer las obras del diablo.`"^
footnote:[1 Juan 3:8]

Pero ¡oh, que todos los Cristianos externos tengan cuidado,
no sea que rechacen a Cristo en Su aparición interna,
como los judíos externos lo rechazaron en Su aparición externa!
Porque si ellos hieren y crucifican al Espíritu de Cristo en sí mismos,
serán tan culpables de Su sangre como los antiguos judíos. ¡De qué menosprecio, rechazo,
sí,
hasta blasfemia de la aparición interna y espiritual de Cristo han sido
culpables los cristianos de nombre! ¡Y cómo le han dado de puñetazos,
lo han apedreado y encarcelado a Él en Sus siervos por hablar a través de ellos!
En verdad, ellos han crucificado a Cristo nuevamente,
y lo han expuesto a vituperio por sus obras impías y palabras duras.

¡Oh, Señor! ¡ruego que abras sus ojos,
para que miren a Aquel que han traspasado espiritualmente con sus afiladas lanzas,
y que permitas que un día de lloro y lamentación venga sobre ellos,
como fue profetizado por Zacarías.^
footnote:[Zacarías 12:10-14]
Porque el cristianismo externo ahora, donde sea que la vida,
Espíritu y poder internos de Cristo no sean recibidos ni experimentados,
no tiene más valor ante los ojos de Dios que las ofrendas y sacrificios
de los judíos mientras seguían contaminados internamente.
Porque es el sacrificio de un espíritu quebrantado y de
un corazón contrito el que el Señor no desprecia.^
footnote:[Salmos 51:17]
El lino blanco interno es lo que es hermoso ante Sus ojos,
y Sus hijos e hijas son "`todos gloriosos en su interior.`"^
footnote:[Salmos 45:13 Reina Valera de Gómez]
Tienen hambre y sed de una justicia interna, es decir,
de la justicia que viene por la fe.

"`Porque cerca de ustedes está la Palabra, en su corazón y en su boca,
para que puedan oírla, y cumplirla.`"^
footnote:[Romanos 10:8, Deuteronomio 30:12-14]
Esta era la Palabra de Fe que los verdaderos ministros del evangelio creían,
recibían y entonces predicaban.
Y el que no reciba esta Palabra interna, no podrá experimentar la salvación de Dios,
porque es "`la Palabra implantada la que puede salvar el alma,`" Santiago
1:21. Y hasta que las personas escuchen y cumplan esta Palabra,
sus edificios están sobre la arena, y no permanecerán en un día de tormenta.
Porque la fe verdadera y salvadora, en todos los que viven y permanecen en ella,
se obtiene y recibe por el oír de esta Palabra,
y sin esta fe es imposible agradar a Dios,
Hebreos 11:6. Fue de este modo que los antiguos recibieron fe, y caminaron en ella,
e hicieron muchos actos valientes,
tanto en el tiempo del primer pacto como en el del segundo,
y experimentaron una victoria sobre el mundo.
Sí, fueron hechos más que vencedores sobre la muerte, el infierno y la tumba,
y obtuvieron un buen testimonio, aunque no recibieron la promesa, Hebreos 11:39.

Y ahora debo dejar este testimonio al mundo, ya que no sé cuántos días me quedan en él:
que Dios ha enviado a Su buen Espíritu a los corazones
de los hijos de los hombres para que sea su guía,
líder y capitán en todas las cosas relacionadas a Su reino.
Y la felicidad o miseria eternas del hombre depende de recibir y obedecer,
o resistir y desobedecer a este Espíritu;
porque nada menos que el Espíritu de la Verdad puede darle a la
humanidad el conocimiento de los misterios de la salvación de Dios;
y todo conocimiento que carezca de este Espíritu es terrenal y carnal,
y nunca puede darle vida al alma.

[.signed-section-signature]
Ambrose Rigge

[.signed-section-context-close]
Riegate, el 30 del Tercer mes, 1691.

[.asterism]
'''

__Como muchos otros fieles seguidores de Cristo,
la vida de Ambrose Rigge estuvo acompañada de mucha tribulación y persecución.
En una epístola escrita a los Amigos en el norte de Inglaterra,
escribió una vez: "`Queridos amigos,
aunque no he visto sus rostros externamente por muchos años,
no quisiera que por eso pensaran que estoy muerto; porque bendito el Señor,
todavía vivo por la fe del Hijo de Dios, y mi vida está escondida con Cristo en Dios.
Pero consideren, he estado en once prisiones en este condado,
en una de ellas fui retenido más de diez años y cuatro meses,
aparte de haber sido premunired dos veces, y una vez azotado,
y muchos otros sufrimientos muy largos para relatarlos aquí; pero bendito sea el Señor,
mis labores, viajes y sufrimientos no han sido en vano,
porque por ellos muchos han sido regresados al verdadero rebaño del Pastor,
donde Dios los ha hecho descansar en reposo y paz.`"
Habiendo caminado así, en una vida de fiel labor en el servicio de Dios y del hombre,
mediante el cual muchos fueron convertidos a la justicia;
y habiendo soportado la persecución y aflicción con una impresionante fidelidad y paciencia,
por las cuales su paz era incrementada; en el período de su última enfermedad,
esperaba su partida como el fin de todas sus aflicciones, diciendo,
"`Voy a donde los cansados están en descanso.`"
Y habiéndose acostumbrado a la paciencia en la aflicción,
ella no lo abandonó en esta última prueba.
Soportó su enfermedad con mucha paciencia y entrega a la voluntad divina,
y su amor y estima por la Verdad pura permaneció con él hasta el final,
declarando lo siguiente un poco antes de su partida,
"`Si los amigos se mantienen aferrados a la Raíz de la Vida en sí mismos,
serán el pueblo más feliz en el mundo.`"
Dejó esta vida el 20 del mes once de 1704, con más de setenta años.__
