== Prefacio

El libro que está en tus manos fue compilado,
editado e impreso por William Backhouse y James Janson,
dos miembros de la Sociedad de Amigos (Cuáqueros), en el año 1813.
Se elaboró e imprimió una segunda edición en 1815,
que cambió tan sólo unas cuantas citas de las Escrituras,
al pasarlas de la Versión Vulgata a la Versión Inglesa Autorizada (KJV).

Este libro es único entre las publicaciones de la Sociedad de Amigos,
en el sentido de que no proviene de la mano de un Cuáquero,
sino que es más bien una compilación de extractos escritos por tres escritores llamados
"`místicos,`" que vivieron y murieron en el seno de la Iglesia Católica Romana.
Ahora, los primeros Amigos eran una Sociedad decididamente Protestante,
después de haber encontrado grandes motivos (con
muchos otros) para separarse de la iglesia de Roma,
en muchos puntos específicos de doctrina y práctica (como la infalibilidad Papal,
las inquisiciones, las sangrientas cruzadas, la persecución contra los disidentes,
las oraciones a y por los muertos, la venta de indulgencias,
la doctrina de la transubstanciación, el purgatorio,
junto con varias ceremonias supersticiosas y manifiestas
formas de corrupción). Sin embargo,
en opinión de este editor,
sería imprudente rechazar o descartar todos los escritos de tantos
buscadores piadosos y sinceros de la Verdad que vivieron,
amaron a Cristo, escribieron, sufrieron y murieron,
en épocas y en lugares donde la iglesia permanecía completamente bajo el dominio papal.
Algunos de estos fieles y honestos buscadores de la Verdad fueron Francis Fenelon,
arzobispo de Cambray, Jeanne Guyón (ambos de Francia), y Miguel de Molinos (de España),
los cuales a finales de 1600 y principios de 1700, fueron perseguidos,
castigados o desterrados por la iglesia de Roma,
por sostener creencias y publicar obras que enfatizaban la gran
necesidad de experimentar la vida interna de Cristo en el alma,
así como la muerte interna del yo en Su cruz.
Y aunque ciertamente,
se puede afirmar que hay diferencias en ciertos puntos de doctrina o práctica,
tanto entre estos tres escritores,
como también entre sus escritos en general comparados con los de los primeros Cuáqueros,
yo considero que difícilmente se puede negar,
con respecto a un gran número de doctrinas y realidades
fundamentales relacionadas con la naturaleza,
experiencia y efecto del evangelio del Señor Jesucristo,
que todos ellos hablaron con una sola voz (y creo que con un solo Espíritu).

El lector cuidadoso encontrará que las perspectivas de Fenelon, Guyón y Molinos,
representadas en este tratado,
concuerdan en dulce armonía con las doctrinas de los primeros
Amigos en muchos (aunque quizás no en todos) temas importantes,
tales como: la Luz de Cristo que alumbra a todo hombre que viene al mundo;
la experiencia interna de la venida de Cristo y de Su reino en el corazón;
la obra purificadora de la gracia en el alma del creyente;
la fe viva que es un don de Dios;
la necesidad de volverse internamente a la luz y gracia de Cristo,
el verdadero Maestro del hombre; la importancia de velar,
esperar y estar en una continua comunión con Cristo en el corazón a través de la oración;
el hecho de que todos los hombres son llamados a esta comunión interna con Dios,
y no sólo unos cuantos predestinados;
la necesidad de guardar el corazón en todo momento "`porque de él mana la vida;`"^
footnote:[Proverbios 4:23]
las maneras y las razones por las que Dios utiliza las pruebas,
los tiempos de sequedad y las tribulaciones para purificar y pulir a Sus vasijas;
la necesidad de negar al yo en todo momento;
la necesidad de experimentar una verdadera crucifixión de
la vida del yo por medio de la obediencia al poder del Espíritu,
y de la rendición al Señor en todas las pruebas y dificultades;
y la posibilidad de perfección,
o de una experiencia de unión a Dios de este lado de la tumba, etc.

La siguiente cita de Gerhard Tersteegen (que no era ni Católico ni Cuáquero),
me parece digna de ser insertada aquí para respaldar la
publicación de este tratado por la Sociedad de Amigos.

[.embedded-content-document.letter]
--

Entre esas almas escogidas y devotas a Dios,
hay que incluir también a los que por lo general
se reconocen como "`Místicos,`" (esto es,
secreto u oculto,) cuyos escritos, al igual que las Sagradas Escrituras,
contienen una definición real del verdadero Cristianismo interno y de la genuina divinidad.
Es cierto que la mayor parte de ellos vivieron y fueron
conocidos por sus escritos en la iglesia Romana;
sin embargo, al dar testimonio de la verdad, debo decir,
que los sinceros entre ellos fueron más evangélicos
y reformados que la mayoría de los Protestantes.
Quiero decir, que eran verdaderos Cristianos en lo interno,
que no se mantenían aferrados a lo externo,
sino que servían y adoraban a Dios en espíritu y en verdad,
al desprender sus afectos y confianza de todas las cosas creadas,
de sí mismos y de todas sus propias obras,
mediante la verdadera fe y unirse a Dios en Cristo.
Y aunque no apruebo ni defiendo todos los pormenores,
ni los eventos externos que aparecen en tales escritos, aun así es cierto,
que en una sola página de los escritos de los verdaderos
místicos se puede encontrar más unción divina,
más luz, consejo, consuelo y paz para un alma que está buscando a Dios,
de lo que a menudo se encuentra en los muchos volúmenes
débiles y aguados de las escuelas de teología,
como coinciden en testificar muchos teólogos iluminados entre los protestantes.

¿Pero cuál es la razón por la que tales obras de
gran valor son a menudo tan poco estimadas y usadas?
¿No es porque la curiosidad inquisitiva no encuentra alimento en ellas?
¿No es porque la naturaleza del viejo hombre y la
vida del yo son atacadas con demasiada severidad?
¿Y acaso no es porque no son atractivos para la razón y la especulación del hombre
(como los otros libros que se acomodan al paladar del viejo Adán),
sino que insisten en la negación y muerte del yo?

--

[.signed-section-signature]
Jason Henderson

[.signed-section-context-close]
Diciembre 2022
