== Introducción

Nuestro bendito Redentor dijo, que "`los que adoran al Padre,
es necesario que lo adoren en espíritu y en verdad.`"^
footnote:[Juan 4:24]
Ahora, el propósito de esta obra es explicar, de una forma sencilla y clara,
cómo se puede llevar a cabo de manera aceptable esta única y verdadera adoración,
y cómo se puede alcanzar adecuadamente la oración interna y espiritual.
Pocos autores han escrito con tanta claridad sobre este tema,
como aquellos de cuyas obras se ha compilado este pequeño volumen;
y por eso los hemos escogido.
A la vez,
se ha considerado necesario simplificar y hacer más comprensibles algunos de sus términos,
para que sean más entendidos de manera general.

Si bien, algunos recibirán este pequeño tratado como un mensajero de buenas nuevas,
sin duda habrá otros que no se sentirán tan dispuestos a confiar en la
sencilla forma de acercarse a su Creador que se presenta aquí. Sin embargo,
no juzguen según las apariencias, sino que dejando de lado todo razonamiento al respecto,
prueben con humildad y sencillez, y sientan por sí mismos,
si lo que se afirma aquí no resulta ser algo más que un sueño vacío de la imaginación,
o una fábula artificiosa.
Y si hacen esto con un corazón sincero,
tendrán que reconocer (para su gran consuelo) que éstas son Verdades sustanciales,
eficaces e indiscutibles; y que este es, ciertamente,
el verdadero camino para ser purificados de las impurezas,
para ser instruidos en los misterios celestiales, para saborear el vino del reino,
y para participar de ese pan que alimenta para vida eterna.

William Backhouse & James Janson

1815
