[short="Dios Mora en el Corazón"]
== Capítulo I. El Espíritu de Dios Mora en el Corazón del Hombre

La Escritura afirma que el Espíritu de Dios mora dentro de nosotros,
que la "`manifestación del Espíritu nos es dada para provecho,`"^
footnote:[1 Corintios 12:7]
y que ésta es "`la Luz verdadera que alumbra a todo hombre que viene a este mundo.`"^
footnote:[Juan 1:9]
"`Esta es la gracia de Dios que se ha manifestado para salvación a todos los hombres;
enseñándonos que, renunciando a la impiedad y a los deseos mundanos,
vivamos en este siglo sobria, justa y piadosamente.`"
Pero tomamos muy poco en cuenta a este Maestro interno,
que es como el alma de nuestra alma;
lo único por lo que somos capaces de formar buenos pensamientos y deseos.

Dios nunca cesa de reprendernos por el mal y de influenciarnos hacia lo que es bueno;
pero el ruido del mundo externo y de nuestras propias pasiones internas,
nos ensordecen y nos impiden escucharlo.

Por eso debemos retirarnos de todos los objetos externos,
y silenciar todos los deseos e imaginaciones errantes de la mente,
para que en ese profundo silencio de toda nuestra alma,
podamos prestarle atención a la voz inefable del Divino Maestro.
Debemos escuchar con oído atento, porque Su voz es un silbo apacible y delicado.
En realidad, no es una voz pronunciada con palabras,
como cuando un hombre habla con su amigo,
sino una percepción interna infundida por las operaciones
e influencias secretas del Espíritu Divino,
que nos atrae y nos capacita para la obediencia, la paciencia, la mansedumbre,
la humildad y para todas las demás virtudes Cristianas,
en un lenguaje perfectamente comprensible para el alma atenta.
¡Pero cuán pocas veces guarda suficiente silencio el alma para que Dios le hable!
Las murmuraciones de nuestros deseos vanos y el amor al yo,
estorban todas las enseñanzas del Espíritu Divino.
¿Nos debe sorprender entonces que tantas personas--devotas en apariencia,
pero demasiado llenas de su propia sabiduría y confianza
en sus propias virtudes--no puedan escucharlas;
y que consideren esta Palabra interna como un engaño de fanáticos?
Ay, ¿qué pretenden con sus vanos razonamientos?
La palabra externa, incluso la del Evangelio, no será más que un sonido vacío,
para el hombre que no posee esta Palabra viva y fructífera en el interior,
para interpretarla y abrirla al entendimiento.

Jesucristo dice: "`He aquí, yo estoy a la puerta y llamo;
si alguno oye mi voz y abre la puerta, entraré a él, y cenaré con él, y él conmigo.`"^
footnote:[Apocalipsis 3:20]
Sus llamados son las advertencias e instrucciones de Su Espíritu,
que nos tocan y que operan dentro de nosotros.
Y prestar atención a esas advertencias y seguirlas, es lo que significa abrirse a Él.

Dios también les habla a los pecadores no arrepentidos; pero éstos,
absortos en la afanosa búsqueda de sus placeres mundanos,
y en la gratificación de sus pasiones malvadas, no pueden escucharlo.
Su Palabra dentro de ellos es menospreciada como una fábula.
¡Pero ay de los que reciben su consolación en esta vida!
Llegará el momento cuando sus vanos deleites serán avergonzados.

Él habla en los pecadores que están en el camino de la conversión.
Éstos sienten arrepentimiento en sus consciencias,
y este arrepentimiento es la voz de Dios que los reprueba internamente por sus pecados.
Cuando son verdaderamente conmovidos, no les parece difícil comprender esa voz secreta,
pues ella los penetra hasta el corazón. Pablo habla
de esa espada de dos filos dentro de ellos,
que corta hasta partir el alma de sí misma: "`Porque la palabra de Dios es viva y eficaz,
y más cortante que toda espada de dos filos;
y penetra hasta partir el alma y el espíritu, las coyunturas y los tuétanos,
y discierne los pensamientos y las intenciones del corazón.`"^
footnote:[Hebreos 4:12]

Él habla en personas que son iluminadas e instruidas,
cuya vida externa parece estar adornada con muchas virtudes;
pero estas personas por lo general--al estar tan llenas de sí mismas y de su propio
conocimiento--se prestan demasiada atención como para ser capaces de escuchar a Dios.
Dios, que sólo desea comunicarse a Sí mismo,
no encuentra lugar (por así decirlo) para darse a
conocer en almas tan llenas de sí mismas,
y tan sobrealimentadas con su propia sabiduría y con sus propias virtudes.
Él esconde Sus secretos de los sabios y de los entendidos,
y los revela a los humildes y a los sencillos.
Nuestro bendito Redentor dijo: "`Te alabo, Padre, Señor del cielo y de la tierra,
porque escondiste estas cosas de los sabios y de los entendidos,
y las revelaste a los niños.`"^
footnote:[Mateo 11:25]
Él se complace en morar con los humildes y con los que son como niños,
y a éstos les revela Sus secretos inefables.
Ciertamente, éstos son los que se encuentran especialmente más calificados para recibir,
en mayor medida, el don de fe;
porque estando dispuestos a que el orgullo de la razón humana sea puesto en el polvo,
no obstruyen la entrada de este don con vanos argumentos;
sino que creen con sencillez y confianza.
