== Capítulo 2. Acerca de la Fe

Existen dos tipos o grados de fe.
La primera es aquella por la que la mente da su consentimiento
a la verdad de algo basado en el testimonio de otro.
La segunda proviene de una naturaleza más sublime, es de origen Divino,
y es un don del Espíritu Santo.
Por medio de la primera,
creemos en la existencia de Dios y en las verdades
que Él nos ha revelado en las Sagradas Escrituras.
Esto es algo esencial en el comienzo de un camino espiritual;
porque "`es necesario que el que se acerca a Dios crea que le hay;
y que es galardonador de los que le buscan diligentemente.`"^
footnote:[Hebreos 11:6 RV1602]
Y si depositamos toda nuestra confianza en Él,
y nos esforzamos en obedecerlo en todas las cosas,
nos encontraremos en un estado de preparación para
recibir esa __fe viva y verdadera__ que es "`don de Dios.`"^
footnote:[Efesios 2:8; Hebreos 12:2]

Sólo a través de esta fe viva somos capaces de vencer a todos nuestros enemigos espirituales,
y de entender claramente esos misterios que son incomprensibles para la razón humana.
Pues la razón, nacida del hombre, es débil e incierta y se equivoca fácilmente;
pero la verdadera fe, nacida de Dios, no se puede equivocar.
Por lo tanto, la razón siempre debe seguir y someterse a esa fe viva,
y no adelantársele o buscar controlarla.

Es pues, por la fe, que siendo "`justificados,
tenemos paz para con Dios por medio de nuestro Señor Jesucristo.`"^
footnote:[Romanos 5:1]
Y cuando este don precioso nos ha sido concedido, produce en nosotros esperanza,^
footnote:[Romanos 5:2]
amor,^
footnote:[1 Pedro 1:8]
confianza,^
footnote:[Efesios 3:12]
gozo^
footnote:[Romanos 5:2], y purifica^
footnote:[Hechos 15:9]
el corazón. Entonces seremos capaces de sentir total dependencia en la bondad, poder,
justicia y misericordia de Dios, y total confianza en Sus promesas;
así como experimentar y comprender más completamente
las operaciones de Su Espíritu en la mente.

La fe es un requisito para llevar a cabo adecuadamente
todos nuestros deberes para con Dios.
De hecho, sin ella es imposible agradarlo;^
footnote:[Hebreos 11:6]
sin ella no nos sentiríamos persuadidos a buscarle,
o a creer en la influencia de Su Espíritu Santo sobre nuestras almas.
La fe es lo que nos sustenta en nuestro camino a la paz,
y nos capacita para perseverar a través de las dificultades
y de los asedios que podamos encontrar en nuestro camino.
Es por este santo don que podemos sufrir los dolores
de la sequedad y la falta de consuelo sin desmayar;
siendo así fortalecidos y "`sostenidos como viendo al Invisible.`"^
footnote:[Hebreos 11:27]
Y sólo por medio de la fe, podemos alcanzar la práctica de la oración verdadera,
interna y espiritual.
