[short="Acerca de la Oración"]
== Capítulo 3. Acerca de la Oración

La oración es la comunión del alma con Dios.^
footnote:[Dios es Espíritu;
y el alma también. Los cuerpos pueden experimentar interacción y comunión;
las almas también. Cuando las almas han sido transformadas a un estado de pureza,
entonces tienen comunión con su Hacedor.
Esta era la felicidad del Paraíso. El pecado la interrumpió,
por lo que la santidad debe restaurarla.
Cuando el alma está así de angustiada,
el Creador se comunica a Sí mismo de una manera tan imperceptible para el ojo natural,
como lo es la caída del rocío;
pero no es menos refrescante en sus poderes secretos para el hombre interior,
de lo que el rocío es para la vegetación. --__Ensayo Anónimo sobre la Devoción.__]
No es una obra de la cabeza, sino del corazón, y una que debe ser continua.
Es el medio por el que __la vida y el alimento__ son transmitidos al alma,
y el canal por el que fluyen y se comunican los dones y la gracia del Espíritu Santo.
Todo anhelo secreto del alma dirigido a Dios es oración. Y por ende,
todas las personas son capaces de orar y son llamadas a hacerlo,
tal como todos son llamados a la salvación y son capaces de ella.

Pablo nos ha exhortado a "`orar sin cesar;`"^
footnote:[1 Tesalonicenses 5:17]
y nuestro Señor nos dice: "`A vosotros digo, velad y orad.`"^
footnote:[Marcos 13:33, 37 y 14:38]
Vengan, entonces, al agua de la vida, todos los que tienen sed,
y no desperdicien su precioso tiempo "`cavando cisternas rotas que no retienen agua.`"^
footnote:[Jeremías 2:13]
Vengan, ustedes almas hambrientas, que no encuentran con qué alimentarse;
vengan y serán saciadas.
Vengan, ustedes pobres afligidos, que gimen bajo su carga de miseria y dolor,
y serán aliviados y consolados.
Vengan a su Médico, ustedes los enfermos,
y no teman acercarse a Él porque están llenos de enfermedades;
expónganlas ante Sus ojos y serán sanadas.

Hijos, acérquense a su Padre, Él los recibirá con los brazos de Amor.
Vengan, ustedes pobres ovejas descarriadas y errantes, regresen a su Pastor.
Vengan, ustedes, los que han estado buscando felicidad en los placeres y afanes mundanos,
pero que no han logrado encontrar en ellos la satisfacción que esperaban.
Vengan y aprendan a ser verdaderamente felices aquí, y eternamente felices en el porvenir.
Vengan pecadores a su Salvador.
Vengan, ustedes los torpes, ignorantes y analfabetos;
los que piensan que son los más incapaces de orar.
En efecto, ustedes son los más particularmente llamados y los más aptos para ello.
Que todos, sin excepción, vengan, porque Jesucristo nos ha llamado a todos.

Sin embargo,
deben aprender un tipo de oración que pueda ser llevada a cabo en todo momento,
que no interfiera con las actividades externas, y que pueda ser practicada por igual,
por todos los rangos y condiciones de los hombres; por los pobres,
como también por los ricos; por los analfabetos, como por los eruditos.
Por lo tanto, ésta no puede ser una oración de la cabeza,
sino del corazón. Es un tipo de oración que no se puede interrumpir,
excepto por los afectos desordenados y descontrolados.
Y aunque ustedes se consideren tan sordos e incapaces de logros sublimes, aun así,
a través de la oración se obtienen fácilmente la posesión y el goce de Dios.
Porque Él está más deseoso de darse a Sí mismo a nosotros,
de lo que nosotros podemos estar de recibirlo.

La oración es la guía a la perfección y a todo bien soberano.
Nos libra de todo pecado y nos concede todas las virtudes;
porque __el único gran medio para ser perfectos,
es caminar continuamente en la presencia de Dios.__
Él mismo ha dicho: "`Anda delante de mí y sé perfecto.`"^
footnote:[Génesis 17:1]
Sólo por la oración somos llevados y mantenidos en Su presencia;
y una vez que lo hayamos conocido plenamente a Él, y experimentado la dulzura de Su amor,
nos resultará imposible saborear algo tanto como a Él mismo.
