[short="Todos Son Capaces de Orar"]
== Capítulo 4. Todos Son Capaces de Alcanzar la Oración Interna y Espiritual

Si todos estuvieran dispuestos a seguir el camino espiritual, entonces,
mientras los pastores están al cuidado de su rebaño,
podrían experimentar el Espíritu de los Cristianos primitivos;
y mientras los agricultores están en el arado,
podrían mantener una bendita unión y comunión con Dios;
y mientras los comerciantes desgastan su hombre exterior con trabajo,
podrían ser renovados con fuerza en el interior.
Todo tipo de perversidad desaparecería pronto,
y toda la humanidad se convertiría en verdaderos seguidores del Buen Pastor.

¡Oh, una vez que el Señor ha conquistado el corazón,
con qué facilidad se corrige todo mal moral!
Es por esta razón que Dios requiere el corazón, por encima de todas las cosas.
Sólo la conquista del corazón puede extirpar todos los espantosos males,
que tanto predominan entre los hombres.
Jesucristo se convertiría en el Soberano universal y pacífico,
y los corazones de toda la humanidad serían completamente renovados.

La decadencia de la piedad interna es sin duda alguna,
la fuente de los diversos errores que han surgido en el mundo;
todos los cuales serían rápidamente despojados de su fuerza y derribados,
si se estableciera la verdadera religión interna.
Si en vez de involucrar a nuestros hermanos descarriados en vanas disputas,
simplemente les enseñáramos a creer y a orar diligentemente,
los guiaríamos dulcemente hacia Dios.
¡Oh,
cuán inexpresablemente grande es la pérdida que experimenta
la humanidad al descuidar la vida interna!

Algunos se justifican diciendo que éste es un camino peligroso,
o alegan que las personas sencillas son incapaces de comprender los asuntos espirituales.
Pero las Escrituras de Verdad afirman todo lo contrario.
Isaías dice: "`El que anduviere en este camino, por torpe que sea, no se extraviará.`"^
footnote:[Isaías 35:8]
¿Y dónde puede estar el peligro de caminar en el único y verdadero camino--que es Jesucristo^
footnote:[Juan 14:6]--rindiéndonos a Él, fijando nuestra mirada continuamente en Él,
poniendo toda nuestra confianza en Su gracia,
y volviéndonos a Su amor puro con todas las fuerzas de nuestra alma?

Las personas sencillas, lejos de ser incapaces de esta perfección,
por su docilidad para ser enseñadas, su inocencia y su humildad,
son especialmente aptas y están calificadas para alcanzarla.
Y debido a que no están acostumbradas al razonamiento, son menos propensas a especular,
y menos tenaces en sus propias opiniones.
Por su ignorancia,
a menudo se someten con mayor libertad a las enseñanzas del Espíritu Divino;
mientras otros, que están cegados por la autosuficiencia y esclavizados por el prejuicio,
resisten con fuerza las operaciones de la gracia.

En las Escrituras se nos dice que "`a los simples, Dios los hace entender;`"^
footnote:[Salmo119:130]
y también nos aseguran que Dios cuida de ellos: "`Jehová guarda a los sencillos.`"^
footnote:[Salmo 116:6]
Cristo les dijo a Sus Apóstoles: "`Dejad a los niños venir a mí,
porque de los tales es el reino de los cielos.`"^
footnote:[Mateo 19:14]
Si los sencillos son incapaces de razonar, entonces enséñenles la oración del corazón,
no la de la cabeza; la oración del Espíritu de Dios,
no la oración de la invención del hombre.

Desgraciadamente,
es al esperar que ellos oren en formas elaboradas
y ser meticulosamente críticos al respecto,
que ustedes crean sus principales obstáculos.
Muchos hijos se han desviado de los mejores padres,
por empeñarse en enseñarles un lenguaje muy refinado y pulido.

Las expresiones sencillas y francas del amor filial son
infinitamente más significativas que el lenguaje más estudiado.
El Espíritu de Dios no necesita de nuestros procedimientos y métodos complicados.
Cuando a Él le place, convierte fácilmente a los pastores en profetas.
Y Él se encuentra tan lejos de excluir a nadie del templo de la oración,
que abre de par en par las puertas para que todos puedan entrar;
en tanto que la sabiduría clama:
"`El que sea simple que entre aquí. Al falto de entendimiento le dice: Ven,
come de mi pan, y bebe del vino que he mezclado.`"^
footnote:[Proverbios 9:4-5 NBLA]

Enseñar a los hombres a buscar a Dios en sus propios corazones, a pensar en Él,
a volverse a Él cada vez que descubren que se han alejado de Él,
y a hacer y padecer todas las cosas con un ojo sencillo para agradarlo,
es el camino más fácil y natural.
Es guiar el alma a la fuente misma de gracia,
donde se encuentra todo lo necesario para la santificación.

¡Ojalá todos se sometieran inmediatamente a este camino, que es Jesucristo,
para que Su Reino sea establecido en sus corazones!
Porque ya que el único que puede oponerse a la soberanía de Cristo es el corazón,
es por medio de la sujeción del corazón que Su soberanía es ensalzada.
Y ya que nadie puede alcanzar este bendito estado,
salvo aquellos a quienes Dios conduce y coloca en él, no pretendamos llevar a nadie a Él,
sino solamente apuntar el camino más directo y seguro que conduce a Él. Y les rogamos
que no se vean frenados en su progreso interno por ninguna práctica religiosa externa,
ni descansen en la sombra en lugar de la sustancia.
Si el agua de la vida eterna se mostrase a algunas almas sedientas,
¡cuán inexpresablemente cruel sería confinarlas a una serie de formas externas,
e impedir así que se acerquen a ella,
de modo que el anhelo de estas almas nunca se vería satisfecho,
sino que perecerían de sed!

¡Oh, ustedes hombres ciegos e insensatos, que se enorgullecen del conocimiento,
la sabiduría, el ingenio y el poder! ¡Cuán bien confirman lo que Dios ha dicho,
que Sus secretos están escondidos de los sabios y de los entendidos,
y que les son revelados a los niños.^
footnote:[Mateo 11:25]
