== Capítulo 5. El Método para Alcanzar la Verdadera Oración

El tipo de oración al que hemos aludido es la del silencio interno,
donde el alma--retirada de todas las cosas externas, en santa quietud,
humilde reverencia y fe viva--espera pacientemente sentir la Presencia Divina,
y recibir las preciosas influencias del Espíritu Santo.
Y cuando te retires con este propósito, que debe ser tu práctica diaria,
debes considerarte puesto en la presencia de Dios, mirándolo a Él con un ojo sencillo,
rindiéndote completamente en Sus manos,
para recibir de Él todo lo que a Él le plazca dispensarte; y al mismo tiempo,
esforzándote calmadamente en fijar tu mente en paz y silencio,
renunciando a todos tus razonamientos propios,
y no tratando intencionalmente de pensar en nada específico,
por bueno o provechoso que pueda parecer.
Y si alguna vana imaginación se presenta a tu mente, debes gentilmente darle la espalda,
y así esperar fiel y pacientemente para sentir la Presencia Divina.

Si al encontrarte internamente reunido,
algo de quietud interna o algún grado de la influencia ablandadora
del Espíritu Divino te es misericordiosamente concedido,
debes valorar esas manifestaciones de la presencia de Dios en tu alma,
y estar cuidadosa y reverentemente atento a ellas; siendo cauteloso, empero,
y no esforzándote por incrementarlas por tus propios esfuerzos.
Porque al hacerlo, alejarás tu mente de ese estado de santa quietud y humilde vigilancia,
que debes procurar conservar tanto como te sea posible.
Y si tratas de avivar la llama,
corres el peligro de extinguirla y de privar tu alma
de ese alimento que estaba destinado para ella.

Un sentido vivo de la Presencia de Dios nos librará
rápidamente de las incontables divagaciones mentales,
nos alejará de los objetos externos y nos acercará a nuestro Dios,
quien solamente puede ser hallado en lo más íntimo de nuestro ser,
que es en el Templo donde Él mora.^
footnote:[1 Corintios 3:16]
Entonces,
cuando estemos completamente vueltos hacia lo interno
e impregnados del sentido abrasador de Su presencia,
debemos permitir que el bendito alimento que hemos
saboreado se hunda en lo profundo del alma,
en quietud y calma, con reverencia, confianza y amor.

La oración del silencio interno es el camino más fácil y más provechoso,
porque con sólo dirigir nuestra atención a Dios,
el alma se vuelve un humilde suplicante ante Su Señor;
o como un niño que se lanza al pecho seguro de su madre.
Dicha oración es también la más segura,
porque el alma es alejada de las operaciones de la imaginación, la cual,
al estar siempre expuesta a los engaños del enemigo,
a menudo se deja seducir por el desenfreno y es fácilmente desconcertada y engañada,
de modo que se ve así privada de su paz.

Debido a que la mente se ha acostumbrado a estar lejos de su hogar,
vagando de aquí para allá, de un tema a otro, le será muy difícil contenerse al inicio,
y librarse de esas divagaciones que entorpecen la oración. De hecho,
dichas divagaciones de la imaginación ponen a prueba a los principiantes,
y son permitidas con el fin de probar su fe, ejercitar su paciencia,
y mostrarles lo poco que pueden hacer por sí solos; enseñándoles así,
a depender solamente de Dios como la única fuerza para vencer todas sus dificultades:
"`Porque nadie será fuerte por su propia fuerza.`"^
footnote:[1 Samuel 2:9]
Pero si éstos depositan toda su esperanza en Él y perseveran fielmente,
cada obstáculo será gradualmente removido,
y encontrarán que pueden acercarse a Él con facilidad.
El silencio interno no sólo se obtendrá con menos dificultad,
sino que a veces se sentirá fácil, dulce y placentero.
Entonces sabrán que éste es el verdadero camino para encontrar a Dios;
y sentirán que "`Su nombre es como ungüento derramado.`"^
footnote:[Cantares 1:3]

Y aunque debemos ser muy vigilantes y diligentes en todo tiempo,
recogiendo todos nuestros pensamientos errantes y dominándolos
tanto como nos sea posible a una adecuada sujeción,
aun así, una lucha directa contra ellos sólo servirá para incrementarlos y empeorarlos.
Sin embargo, recordando que estamos en la presencia de Dios,
y esforzándonos por hundirnos bajo un sentido y una percepción de esa verdad,
volviéndonos sencillamente hacia el interior, emprenderemos una guerra muy ventajosa,
aunque indirecta, contra ellos.

Ahora, los que no han aprendido a leer,
no están por dicho motivo excluidos de la oración,
porque el gran Maestro que enseña todas las cosas es Jesucristo mismo.^
footnote:[Juan 14:26]
Éstos deben aprender esta regla fundamental:
que "`el Reino de Dios dentro de ellos está;`"^
footnote:[Lucas 17:21 RV1602]
y que solamente allí debe ser buscado.

Nuestro bendito Redentor dice: "`El reino de Dios está dentro de ustedes.`"
Por tanto, abandonen las riquezas y los placeres de este mundo malvado,
y vuélvanse al Señor con todo su corazón, y su alma encontrará descanso.^
footnote:[Mateo 11:28-29]
Si retiras tu atención de las cosas externas, y la mantienes fija en el Maestro interno,
esforzándote por obedecerle en todo lo que Él requiera de ti,
pronto percibirás la venida del reino de Dios.^
footnote:[Mateo 6:10]
Porque el reino de Dios es esa "`paz y gozo en el Espíritu Santo,`"^
footnote:[Romanos 14:17]
que no puede ser recibido por hombres sensuales y mundanos.

Es por falta del retiro interno y de la oración, que nuestras vidas son tan imperfectas,
y que no estamos siendo impregnados ni calentados con la Luz Divina de la Verdad; Cristo,
la Luz del mundo.^
footnote:[Juan 1:9]
Por eso debemos practicarlos diariamente;
y no existe nadie tan ocupado como para que no pueda encontrar
algún momento para retirarse internamente con Dios.
Cuanto menos practiquemos la oración silenciosa, menos deseos tendremos de ella;
porque al ocupar nuestra mente en las cosas externas,
no tardaremos en adoptar el hábito de hacerlo,
a tal punto que se vuelve muy difícil volverla de nuevo hacia el interior.

"`El Señor está en Su santo templo; que calle delante de Él toda la tierra.`"^
footnote:[Habacuc 2:20]
Callar todos nuestros pensamientos y deseos carnales es absolutamente indispensable,
si deseamos oír la voz secreta del Divino Instructor.
El oír es un sentido creado para recibir sonidos, y es más pasivo que activo.
Recibe, pero no comunica una sensación. Y si deseamos oír al Señor,
debemos inclinar nuestro oído a Cristo, la Palabra eterna,^
footnote:[Apocalipsis 19:13 RV1602]
sin cuya comunicación Divina, el alma está muerta, oscura y estéril.
Y cuando Él habla dentro de nosotros,
requiere la más silenciosa atención a Su voz vivificante y eficaz.

Por lo tanto, no debemos pensar en nosotros mismos, ni en nuestro interés propio,
sino que debemos oír y estar atentos a la voz de nuestro Dios.
El silencio externo es un requisito necesario para
el cultivo y mejoramiento del silencio interno;
y de hecho,
es imposible estar verdaderamente vuelto al interior
sin amar y practicar el silencio externo y el retiro.
Y es incuestionablemente cierto, que estar internamente reunidos con Dios,
es muy incompatible con estar continuamente ocupados
e inmersos en las numerosas tonterías que nos rodean.

Cuando por el descuido o la infidelidad nos distraemos o nos relajamos,
o (por así decirlo) perdemos el enfoque,
es de suma importancia que nos volvamos nuevamente
hacia el interior de manera gentil y apacible;^
footnote:[Esto no se trata de volvernos hacia nosotros mismos,
ni hacia nada que el hombre posea o tenga por naturaleza.
Más bien, es un volverse hacia la obra, enseñanza, corrección, resplandor, crucifixión,
vivificación que es obra del Espíritu de Dios,
quien aparece (como siempre lo ha hecho) en Su templo.]
y de esa forma aprenderemos a conservar el espíritu y la unción de la oración a lo largo
del día. Pues si la oración del silencio interno estuviera confinada a media hora,
o a una hora, cosecharíamos muy poco fruto.

Y es de suma importancia para el alma,
acudir a la oración con confianza y con un amor tan puro y desinteresado,
que no busca nada de Dios excepto la habilidad para complacerlo y para hacer Su voluntad;
pues un siervo cuya diligencia es solamente proporcional a su expectativa de recompensa,
se vuelve indigno de toda recompensa.
Acudan entonces a la oración, no para gozar de los placeres espirituales,
sino para que sean llenados o vaciados, según lo considere mejor Dios.
Esto los preservará en firmeza espiritual, cuando sientan desesperación o consolación,
y evitará que los sorprenda la sequedad, o cuando perciban los retiros de Dios.

La oración constante es mantener el corazón siempre orientado hacia Dios.
Esfuércense, entonces, cuando acaben de orar,
a no permitir que sus mentes se enreden demasiado con las cosas externas,
procurando estar totalmente rendidos a la Voluntad Divina,
para que Dios haga con ustedes y con los suyos según Su beneplácito Divino,
apoyándose en Él como un Padre amable y amoroso.
Y aunque estén envueltos en asuntos externos,
y por ello sus mentes se vean impedidas a estar realmente fijas en Él, aún entonces,
llevarán siempre con ustedes un fuego que nunca se apagará;
sino que (al contrario) alimentará una secreta oración interna que será como
una lámpara que está continuamente encendida delante del trono de Dios.

Un hijo que ama a su padre no siempre piensa específicamente en él;
muchos objetos alejan su mente de ello, pero éstos nunca interfieren con el amor filial.
Y cuando su padre regresa a sus pensamientos,
él lo ama y siente en lo más profundo de su corazón
que nunca ha dejado de amarlo por un instante,
aunque en ocasiones ha dejado de pensar en él. De
esta manera debemos amar a nuestro Padre celestial.

Solamente a través de la verdadera religión podemos llamar a Dios nuestro Padre,
y convertirnos verdaderamente en Sus hijos.
Pero la verdadera religión es algo que nace del cielo,
es una emanación de la verdad y de la bondad de Dios sobre los espíritus de los hombres,
en donde somos formados a la imagen y semejanza de Él mismo,
y hechos "`participantes de la Naturaleza Divina.`"^
footnote:[2 Pedro 1:4]

El verdadero Cristiano es en todos los sentidos, de la más noble estirpe,
de linaje celestial y divino, nacido (como lo expresa Juan): "`De arriba.`"^
footnote:[Juan 3:3 Véase el texto al margen.]
Y en otro lugar dice: "`Mirad cuál amor nos ha dado el Padre,
para que seamos llamados hijos de Dios.`"^
footnote:[1 Juan 3:1]

Si tales consideraciones no son suficientes para convencernos
de la insensatez de nuestro apego a las cosas que perecen,
y motivarnos a anhelar privilegios más grandes y gloriosos,
ciertamente debemos habernos hundido en un estado de profunda y deplorable insensibilidad.
Y como lo ha declarado nuestro Señor,
que "`aunque alguno se levante de entre los muertos,`"^
footnote:[Lucas 16:31]
aún sería imposible ser levantados.
