[short="Sobre la Sequedad Espiritual"]
== Capítulo 6. Sobre la Sequedad Espiritual

Tan pronto como te hayas entregado a servir al Señor en este camino interno,
Él comenzará a purificarte y a probar tu fe para acercarte aún más a Sí mismo.
Y para este fin, Él te guiará a través de caminos secos y desiertos;
de modo que a menudo,
cuando te esfuerces por fijar tu mente en silencio para palpar en busca de tu Dios,
no experimentarás el consuelo y el refrigerio que esperabas.
Por el contrario,
estarás más asediado de lo usual por una multitud de imaginaciones molestas e incesantes,
tanto que comenzarás a pensar que te esfuerzas en vano,
y que la oración del silencio interno es un logro al que no puedes aspirar,
viendo que tu imaginación es inmanejable, y que tu mente está muy vacía de lo bueno.
Pero este estado de sequedad es muy provechoso si se soporta con paciencia.^
footnote:[Nota de Jeanne Guyón:
Si deseas ser realmente beneficiado por las Sagradas Escrituras y por otros libros espirituales,
debes examinarlos con profunda atención e introversión de mente, procurando,
lo que sea que hayas escogido, leer solamente una pequeña porción de ello;
esforzándote por saborearla y digerirla, extrayendo la esencia y la sustancia de ella;
y a no avanzar mientras permanezca alguna fragancia o sabor en el pasaje.
Cuando se disipe, toma de nuevo tu libro y procede como lo estabas haciendo,
sin leer más de media página seguida; pues no es la cantidad que se lee,
sino la manera en que se lee lo que nos resulta de provecho.
Los que leen rápido no sacan más provecho del que sacarían
las abejas si sólo rozan la superficie de una flor,
en lugar de esperar a introducirse en ella y así extraer su dulce.
Si siguiéramos este método, estaríamos más dispuestos para el retiro y la oración.]

El Señor utiliza este velo de sequedad para varios fines,
uno de los cuales puede ser para que no sepamos lo que Él está haciendo en nosotros,
y así nos mantengamos humildes.
Porque si sintiéramos y supiéramos con seguridad
lo que Él ha estado trabajando en nuestras almas,
sin duda alguna nos llenaríamos de satisfacción y arrogancia.
Imaginaríamos que estamos haciendo algo bueno, y nos consideraríamos muy cerca de Dios,
y ésta complacencia del yo impediría un verdadero avance espiritual.

Por lo tanto,
si en esta oración de quietud interna te sientes en un estado seco y desconsolador,
al no tener la habilidad de deshacerte de tus pensamientos molestos,
ni de experimentar ninguna luz, consuelo o sentido espiritual; aun así, no te aflijas,
ni desistas de tu propósito.
Por el contrario,
ríndete en ese momento con determinación y persevera pacientemente como en Su presencia;
porque mientras perseveras de esa manera, tu alma prosperará internamente.

¿Crees que cuando sales de la oración en las mismas condiciones en las que empezaste,
sin sentirte beneficiado de ella, has estado trabajando en vano?
Eso es una falacia, porque la verdadera oración consiste,
no necesariamente en el disfrute de la luz y conocimiento espiritual,
sino en soportar con paciencia, perseverar en la fe y en el silencio,
creer que te encuentras en la presencia del Señor,
y volver tu corazón constantemente a Él con tranquilidad y sencillez de mente.

Debemos estar conscientes de que la naturaleza caída siempre es enemiga del Espíritu;
y que cuando es desposeída de los placeres perceptibles, permanece débil,
melancólica y llena de irritabilidad.
De ahí, que por la inquietud de tus pensamientos, la pereza de tu cuerpo,
los deseos persistentes de dormir y la inhabilidad de controlar
tus sentidos (cada uno de los cuales desea seguir su propio placer),
te sentirás a menudo impaciente por terminar tu oración. ¡Dichoso
eres si puedes perseverar en medio de esta dolorosa prueba!
Recuerda que "`los que esperan a Jehová tendrán nuevas fuerzas;
levantarán alas como las águilas; correrán, y no se cansarán; caminarán,
y no se fatigarán.`"^
footnote:[Isaías 40:31]

La oración del silencio interno se ejemplifica bien con
aquella lucha que se describe en las Sagradas Escrituras,
cuando el patriarca Jacob luchó toda la noche con
Dios hasta que rayó el alba y Él lo bendijo.
Por lo tanto, el alma tiene que perseverar,
para luchar contra las dificultades que se encontrará en la oración interna sin desistir,
hasta que el Sol de la Luz interna comience a aparecer, y el Señor otorgue Su bendición.

Si te acercas a la
oración con el espíritu y la intención de orar,
mientras no te apartes de esa intención (aunque tus pensamientos
divaguen por el predominio del mal y de la debilidad),
aun así estarás orando en espíritu y en verdad.
Dios te ayudará a vencer todas tus dificultades en Su propio tiempo;
y cuando menos lo esperes,
Él te dará aspiraciones santas y deseos más fuertes de servirle.
No desconfíes pues de Él, sino solamente de ti mismo; y recuerda, como dice el apóstol,
que Él es el "`Padre de misericordias y Dios de toda consolación.`"^
footnote:[2 Corintios 1:3]
Sus consuelos son retirados en ocasiones, pero Su misericordia permanece para siempre.
Él sólo te priva de lo que es dulce y sensible de
Su gracia porque tienes necesidad de ser humillado.

Entonces esfuérzate, y aunque te parezca que trabajas sin obtener gran provecho,
debes recordar, sin embargo, que debemos arar y sembrar antes de que podamos cosechar;
y si perseveras en fe y paciencia,
cosecharás una abundante recompensa por todos tus esfuerzos.
¿Serías tan irrazonable como para esperar encontrar sin buscar,
o suponer que la puerta será abierta sin tomarte la molestia de tocar?
Esto sería como si un granjero esperara ver sus campos repletos de grano,
sin haberse tomado la molestia de poner la semilla en el terreno.

No es difícil unirse a Dios mientras estás gozando de Sus consuelos y consolaciones;
pero si quieres probarle tu fidelidad,
debes estar dispuesto a seguirlo a través de los caminos secos y desiertos.
La autenticidad de un amigo no se conoce mientras recibe favores y beneficios;
pero si permanece fiel cuando es tratado con frialdad y negligencia,
es una prueba de la sinceridad de su apego.

Aunque Dios no tiene otro deseo más que impartirse
a Sí mismo a los que lo aman y lo buscan,
Él suele esconderse de nosotros para que seamos despertados de la pereza,
y animarnos a buscarlo con fidelidad y amor.
¡Y con qué abundante bondad recompensa nuestra fidelidad!
¡Y cuán dulces son los consuelos de Su amor,
cuando vienen después de haber retirado Su presencia!
David dice: "`Pacientemente esperé a Jehová, y se inclinó a mí, y oyó mi clamor.
Y me hizo sacar del pozo de la desesperación, del lodo cenagoso;
puso mis pies sobre peña, y enderezó mis pasos.
Puso luego en mi boca cántico nuevo, alabanza a nuestro Dios.`"^
footnote:[Salmo 40:1-3]

En las temporadas en que Su presencia se retira de nosotros,
somos dados a creer que es una prueba de nuestra fidelidad, y por lo tanto,
como evidencia del fervor de nuestro amor,
lo buscamos __a través del esfuerzo de nuestra propia fuerza y actividad,__
pensando que este esfuerzo lo incitará a regresar más rápidamente.
Pero este no es el camino correcto cuando nos encontramos en ese estado.
Con paciente rendición, con humillación,
con repetidas respiraciones de un anhelo ferviente pero apacible,
y con un silencio reverente, debemos esperar el regreso de nuestro Amado.
Solamente así demostraremos que no buscamos nada sino a Él y Su beneplácito,
y no los deleites egoístas de nuestras propias pasiones.

Cuando sentimos la dulzura de la gracia de Dios, es muy común suponer que Lo amamos;
pero sólo cuando se retira Su Presencia es que nuestro amor es probado,
y la medida de él verdaderamente conocida.
Durante estas temporadas somos convencidos de la debilidad y la miseria de nuestra naturaleza,
y cuán incapaces somos, por nosotros mismos, de pensar o de hacer cualquier cosa buena.
Hay muchos, que cuando experimentan el corazón ablandado, el derramamiento de lágrimas,
y otros deleites perceptibles, imaginan que son los favoritos de Dios,
y que verdaderamente lo poseen a Él; y luego,
a menudo pasan el resto de sus vidas buscando más de esas sensaciones placenteras.
Pero éstos deben ser cautelosos, no sea que se engañen a sí mismos.
Porque cuando estos consuelos proceden del hombre natural,
y son producidos por sus propios razonamientos o admiración propia,
les impiden discernir la luz verdadera,
o dar un verdadero paso hacia la perfección. Por lo tanto,
debemos estar atentos para distinguir entre el impulso de nuestras emociones o afectos,
y las operaciones que proceden puramente de Dios, dejándonos guiar completamente por Él,
quien será nuestra luz en medio de la oscuridad y sequedad.

No es de poco provecho sufrir con paciencia en la oración, en la falta de consuelo,
angustia y terquedad de una imaginación errante; porque esto es una ofrenda de uno mismo,
como holocausto y sacrificio total.
Y mientras te ejercitas en rechazar calmadamente tus pensamientos vanos,
y soportas tranquilamente tu estado oscuro y desolado,
es como si el Señor estuviera colocando muchas coronas sobre tu cabeza.
Por eso es de gran importancia que te esfuerces en
todo momento por mantener tu corazón en paz,
para que puedas conservar puro el templo de Dios.
Y la manera de conservarlo en completa paz,
es entrando en ella por medio del silencio interno.

Cuando te veas severamente atacado, retírate a esa región de paz,
y encontrarás la fortaleza en la que podrás triunfar sobre tus enemigos,
visibles e invisibles, y sobre todas las trampas y tentaciones.
Dentro de tu propia alma reside la Ayuda Divina y el Soberano Auxilio.
Retírate internamente y todo estará tranquilo, seguro, apacible y calmado.
Así, pues,
por medio del silencio interno--que solamente puede ser alcanzado con
la Ayuda Divina--empezarás a experimentar tranquilidad en un tumulto,
soledad en compañía, luz en la oscuridad, serenidad en las tensiones,
vigor en el abatimiento, valor en el temor, resistencia en la tentación,
paz en la guerra, y calma en la tribulación.
