[short="Sobre Defectos y Debilidades"]
== Capítulo 7. Sobre Defectos y Debilidades

Si bajamos la guardia tanto como para vagar nuevamente
entre las cosas externas en busca de felicidad,
o hundirnos en el libertinaje, o cometer alguna falta,
debemos volvernos inmediatamente al interior;
porque habiéndonos apartado de esa manera de nuestro Dios,
debemos regresar a Él tan pronto como sea posible,
y con paciencia permitirle cualquier sensación que a Él le plazca causar en nosotros.
Porque Él ha declarado: "`Yo reprendo y castigo a todos los que amo.`"^
footnote:[Apocalipsis 3:19]
Es de suma importancia, que al cometer alguna falta,
velemos contra el disgusto y la inquietud que brotan de una raíz secreta de orgullo,
y del amor a nuestra propia grandeza; pues sólo nos duele sentir lo que realmente somos.
Y si nos desanimamos, o nos permitimos hundir en la desesperación,
nos debilitamos aún más; pues al reflexionar constantemente sobre nuestras faltas,
se levanta un desasosiego que es, por lo general, peor que la falta misma.

El alma verdaderamente humilde no se sorprende de sus defectos o fallos;
y cuánto más miserable y desdichada se percibe,
más se entrega a Dios y se esfuerza por tener una relación más cercana e íntima con Él,
para poder valerse de Su fuerza eterna.
Deberíamos estar más persuadidos a actuar así, como Dios Mismo ha dicho:
"`Te haré entender, y te enseñaré el camino en que debes andar;
sobre ti fijaré mis ojos.`"^
footnote:[Salmo 32:8]
