[short="Sobre las Tentaciones y las Tribulaciones"]
== Capítulo 8. Sobre las Tentaciones y las Tribulaciones^
footnote:[O "`pruebas,`" y así a lo largo de este capítulo.
// lint-disable invalid-characters
En la versión King James la palabra griega πειρασμός,
es traducida por lo general como "`tentaciones,`" tal como en Santiago 1:2; 1:12; 1:14;
etc.,
pero en la mayoría de las traducciones modernas del Inglés
y del Español se traduce esta palabra como "`pruebas.`"]

Aunque "`Dios no puede ser tentado por el mal, ni él tienta a nadie;`"^
footnote:[Santiago 1:13]
es evidente que las tentaciones son permitidas para nuestro propio bien,
y si son soportadas adecuadamente, tienden a nuestra purificación.

"`Por tanto`", dice el apóstol,
"`tened por sumo gozo cuando os halléis en diversas pruebas,
sabiendo que la prueba de vuestra fe produce paciencia.`"^
footnote:[Santiago 1:2-3]
Y en todas nuestras pruebas, por muy difíciles que nos parezcan,
o de cualquier naturaleza que sean, debemos recordar que se dice:
"`Bienaventurado el varón que soporta la tentación;
porque cuando haya resistido la prueba, recibirá la corona de vida,
que Dios ha prometido a los que le aman.`"^
footnote:[Santiago 1:12]

Por naturaleza somos malos, orgullosos y ambiciosos,
y estamos tan llenos de nuestros propios apetitos,
de nuestros propios juicios y opiniones,
que si no se nos permitieran las tentaciones y las tribulaciones para probarnos,
humillarnos y purificarnos, nunca llegaríamos a un estado de aceptación para con Dios.

El Señor, al ver nuestra miseria y nuestras inclinaciones perversas,
y al ser movido por ello en compasión, retira con frecuencia Su fuerza de nosotros,
para que sintamos nuestra propia debilidad;
permitiéndonos ser asaltados por violentos y dolorosos
movimientos de impaciencia y orgullo,
y de muchas otras tentaciones.
Y a algunos que han estado por mucho tiempo en la práctica del pecado,
se les permite ser atacados por la glotonería, exceso, ira, blasfemia,
desesperanza y muchos otros agravios,
con el fin de que puedan conocerse a sí mismos y ser humillados.
Con estas tentaciones la Infinita Bondad humilla nuestro orgullo,
y nos da en ellas la medicina más sanadora.

"`Todas nuestras justicias,`" dice Isaías, son "`como trapo de inmundicia;`"^
footnote:[Isaías 64:6]
a causa de la vanidad, la arrogancia y el amor al yo con que están contaminadas.
Por lo tanto,
es necesario que sean purificadas con el fuego de la tentación y la tribulación,
para que así sean limpias, puras, perfectas y aceptables ante los ojos de Dios.
El Señor pule el alma que atrae hacia Sí mismo con la lima áspera de la tentación,
liberándola así del herrumbre de muchas pasiones y tendencias malignas.
A través de las pruebas y las tribulaciones, la humilla, sujeta y ejercita,
mostrándole su propia debilidad y miseria.
De esta manera purifica y desnuda el corazón,
para que todas sus acciones sean puras y útiles.
¡Oh, cuán feliz serías si pudieras creer tranquilamente,
que todas las pruebas y las tribulaciones con las que eres atacado,
son permitidas para tu propia ganancia y provecho espiritual!

Quizás digas, que cuando eres acosado por otros,
o perjudicado y agraviado por tu prójimo, eso no puede ser para tu beneficio espiritual,
viendo que es el resultado de la culpa y la malicia de otro.
Pero esto no es más que una astuta y oculta estratagema del enemigo.
Porque aunque es cierto que Dios no desea el pecado de tu prójimo,
aun así desea Su propia bondad llevada a cabo en ti;
y la angustia que te ocasione el pecado de otro debería serte de provecho,
al aumentar tu paciencia y ejercitar tu tolerancia y amor.

Considera cómo el Señor utiliza los pecados de otros para el bienestar de tu propia alma.
¡Oh,
la grandeza de la Divina Sabiduría! ¿Quién puede escudriñar
las profundidades de los métodos secretos y extraordinarios,
y de los caminos ocultos, por los que Él guía al alma que anhela ser purificada,
transformada y dignificada?
De hecho, puede que algunas veces la mayor tentación sea estar sin tentación,
porque entonces somos más propensos a caer en un estado de tibieza.
Por eso, no debemos quejarnos cuando nos ataque la tentación, sino que con rendición,
paz y fidelidad debemos cerrar la puerta de nuestros corazones contra ella.
Si deseas servirle a Dios y llegar a la sublime experiencia de paz interior,
debes atravesar este camino áspero de tentación y tribulación, y en él ser pulido,
limpiado, renovado y purificado.

Argumentar y luchar directamente contra las tentaciones, a menudo sirve para aumentarlas,
y puede apartar al alma de esa unión a Dios que siempre debe esforzarse por mantener.
El método más certero y seguro para vencer es, simplemente,
alejarse del mal y acercarse más y más a Dios.
Cuando un niño pequeño percibe un monstruo, no espera luchar contra él,
y difícilmente vuelve su mirada hacia él;
sino que rápidamente se esconde en el pecho de su
madre con la absoluta confianza de seguridad.
De la misma forma, el alma debe alejarse de los peligros de la tentación y huir a su Dios.
"`Dios está en medio de ella,`" dice el Salmista, "`no será conmovida.
Dios la ayudará al clarear la mañana.`"^
footnote:[Salmo 46:5]
"`Torre fuerte es el nombre de Jehová; a él correrá el justo, y será levantado.`"^
footnote:[Proverbios 18:10]

Si hacemos lo contrario e intentamos atacar a nuestros enemigos en nuestra debilidad,
nos sentiremos con frecuencia heridos, por no decir completamente vencidos.
Pero, al arrojarnos en la presencia de Dios y depender completamente de Él,
encontraremos los suministros necesarios para sostenernos.
Esta fue la ayuda que buscó David: "`A Jehová he puesto siempre delante de mí;
porque está a mi diestra, no seré conmovido.
Se alegró por tanto mi corazón, y se gozó mi alma;
mi carne también reposará confiadamente:`"^
footnote:[Salmo 16:8-9]
Y en Éxodo se dice: "`Jehová peleará por vosotros, y vosotros estaréis tranquilos.`"^
footnote:[Éxodo 14:14]

Los hombres o los demonios no te pueden herir, si te mantienes siempre cerca de tu Dios;
porque, "`¿quién es aquel que os podrá hacer daño, si vosotros seguís el bien?`"^
footnote:[1 Pedro 3:13]
Pero si resultas herido, es tu orgullo,
tus pasiones y tus muchas tendencias malignas no sometidas,
lo que se levanta y te lastima; y mientras ésto permanezca, el enemigo lo utilizará,
y buscará alejar tu mente de la unión a Dios.

"`Cada uno es tentado, cuando de su propia concupiscencia es atraído y seducido.`"^
footnote:[Santiago 1:14]
Por lo tanto, conoce tu propio estado corrupto,
y la necesidad que tienes de ser purificado por las pruebas y tentaciones.
Y mantente siempre vigilante,
no sea que el incansable enemigo gane terreno en tu alma
a través de sus insinuaciones y agradables encantos,
que adaptará a tu situación y condición presente.
Pues a lo largo de tu vida, encontrarás que él te ofrecerá muchas cosas como tentaciones,
esforzándose por producir en ti una desmesurada inclinación y deseo por ellas;
y si cedes ante ellas cuando eres tentado,
el peligro de ser completamente vencido será muy grande.

Si el maligno no es resistido en este primer ataque,
avanza introduciéndose gradualmente con el fin de poseer el corazón por completo.
Y mientras se postergue nuestra oposición mediante una acostumbrada negligencia,
nuestro poder de oposición disminuirá cada día,
y la fuerza del adversario se incrementará proporcionalmente.
Por tanto, cuando sientas en ti mismo un fuerte y vehemente deseo tras algo,
y descubras que tu inclinación te lleva con demasiada rapidez a hacerlo,
esfuérzate por contenerte retirándote hacia tu interior.
A fin de hacer todas las cosas bien, debemos hacerlas como en la presencia de Dios,
de lo contrario, nos desviaremos fácilmente,
y estaremos en peligro de ser totalmente derribados.

¡Oh bendita alma,
si tan sólo te contentaras y reposaras en el fuego de la tentación y la tribulación,
y permitieras ser completamente probada y tratada,
soportando pacientemente los ataques del enemigo y los retiros del bien celestial,
cuán rápido te encontrarías rica en tesoros eternos! ¡Cuán
rápido haría la Divina Bondad un trono rico en tu alma,
y una morada deleitosa para ti, para refrescarte y consolarte en ella!
Entiende esto: que aunque el Señor te visite por una temporada,
Él sólo establece Su morada en las almas apacibles; esto es,
aquellas en las que el fuego de la tentación y la tribulación
ha consumido todas las inclinaciones corruptas.
El Señor no descansa en ningún otro lugar, sino donde reine la quietud,
y donde el amor al yo haya sido expulsado.

Si a partir del caos,
Su omnipotencia ha producido tantas maravillas en la creación del mundo,
¿qué no hará Él en tu alma (creada a Su propia imagen y semejanza) si te mantienes constante,
quieto y rendido a Él, bajo un verdadero sentido de tu propia nadedad?

Por lo tanto, "`no perdáis, pues, vuestra confianza, que tiene grande galardón,`"^
footnote:[Hebreos 10:35]
sino que mantente constante.
¡Oh bendita alma, mantente constante!
Porque no será como lo imaginas;
y nunca te encontrarás más cerca de Dios que en esos
momentos de abandono usados para probar tu fe.
Aunque el sol se esconda a veces en las nubes, no cambia su lugar, ni pierde su brillo.
El Señor permite esas dolorosas tentaciones y abandonos
para limpiarte y despojarte del yo;
para que por medio de tales pruebas,
llegues a ser completamente de Él y te rindas totalmente a servirle.

Oh cuánto hay que purificar en un alma que debe llegar al monte santo de transformación
y perfección. Porque mientras quede en nosotros alguna medida de maldad,
cualquier cosa del yo, debemos ser sujetos a pruebas y tentaciones.
Pero cuando el yo es crucificado, no queda nada más en lo que el tentador pueda obrar.
¡Oh, cuán rendida, desnuda,
negada y crucificada debe estar el alma para no resistir la venida del Divino Señor,
ni Su continua comunión con ella!
