== Capítulo 9. Sobre la Negación al Yo

El que espera llegar a la perfección, o a unir el alma a Dios,
por medio del consuelo y la consolación, encontrará que se encuentra equivocado.
Porque debido a la depravación de nuestra naturaleza,
debemos esperar padecer y ser purificados en cierta medida,
antes de que podamos ser en algún grado aptos para unirnos a Dios,
o para que se nos permita saborear del gozo de Su Presencia.

Por eso sé paciente en todos los sufrimientos que a Dios le plazca enviarte.
Si tu amor hacia Él es puro, no lo buscarás menos en el sufrimiento que en el consuelo.
Y ciertamente, Él debe ser tan amado en uno como en otro,
ya que al sufrir en la cruz hizo la mayor demostración de Su propio amor por ti.

No seas como los que se entregan a Él una temporada, y se apartan de Él otra.
Estos sólo se entregan para ser consentidos, y luego,
cuando llega el momento de ser crucificados se retiran, o como mínimo,
se vuelven al mundo en busca de consuelo.
Pero el verdadero consuelo no se encuentra sino en una libre
y completa rendición de tu voluntad a la Voluntad Divina.
Aquel que no pone la mirada en la cruz,
no puede poner la mirada en las cosas que son de Dios;^
footnote:[Mateo 16:23]
y un corazón que saborea la cruz, encuentra que incluso lo amargo es dulce.
"`Pero al hambriento todo lo amargo es dulce.`"^
footnote:[Proverbios 27:7]
Dios da la cruz, y la cruz nos da a Dios.
Y podemos estar seguros de que hay un verdadero avance interno,
dondequiera que haya un avance en el camino de la cruz.

En cuanto algo se presente a sí mismo como una forma de sufrimiento,
y sientas una repulsión contra ello, ríndete inmediatamente a Dios con respecto a eso,
ofreciéndote a Él como un sacrificio vivo; y entonces encontrarás,
que cuando se acerque la cruz no será tan pesada,
porque ya te has dispuesto a recibirla voluntariamente.
Jesucristo Mismo estuvo dispuesto a sufrir su mayor severidad.
A menudo soportamos la cruz en debilidad, en otros momentos en fortaleza;
pero todo debería ser igual para nosotros en la voluntad de Dios.

Si el hombre hubiera podido ser redimido de su estado
caído y corrupto en el que vive por naturaleza,
mediante cualquier otro camino que no fuera el de
tomar la cruz y morir a su propia voluntad,
Cristo lo habría enseñado y establecido con Su ejemplo.
Pero a todos los que desean seguirlo, Él les ha ordenado que tomen la cruz;
y les ha dicho a todos sin excepción: "`Si alguno quiere venir en pos de mí,
niéguese a sí mismo, y tome su cruz, y sígame.`"^
footnote:[Mateo 16:24]
¿Por qué entonces temes tomar la cruz que te guiará al camino que lleva al reino de Dios?

De la cruz se derivan la humildad celestial, la verdadera fortaleza,
los gozos del Espíritu, la conquista del yo, y la perfección de la santidad.
No hay redención, ni esperanza de que la Vida Divina continúe en nosotros,
a menos que tomemos la cruz contra nuestros apetitos carnales e inclinaciones.
Porque todo consiste en la muerte del yo,
¡y no hay forma de obtener vida y paz verdaderas,
sino muriendo de este modo a las corrupciones de nuestra naturaleza caída!
Por lo tanto, toma tu cruz y sigue a Jesús en el camino que conduce a la paz eterna.
Él se ha adelantado cargando esa cruz en la que murió por ti, para que puedas seguirlo,
soportando con paciencia la tuya, y en ella,
morir a ti mismo por Él. Y si morimos juntamente con Él,
también viviremos juntamente con Él. Y si somos partícipes de los padecimientos de Cristo,
también seremos partícipes de Su gloria.
(Ver Romanos 8:17; 1 Pedro 4:13)

¿Por qué buscas otro camino hacia la gloria que no sea aquel en el que estás llamado
a seguir al "`Capitán de tu Salvación`"? La vida de Cristo fue una cruz continua,
¿y deseas tú un estado continuo de tranquilidad y gozo?
Comprende, entonces,
que tu vida debe consistir en una muerte continua a los apetitos y pasiones de la naturaleza
caída. Y comprende también que cuánto más plenamente mueras a ti mismo,
más verdaderamente comenzarás a vivir para Dios.
Entonces, si deseas gozar de paz verdadera aquí,
y obtener la eterna corona de gloria en el porvenir,
es necesario que en todo lugar y en todo momento, cargues la cruz voluntariamente.
Así, pues, sufrir la muerte del yo es tu porción;
y sufrir paciente y voluntariamente es el gran testimonio
de tu amor y fidelidad a tu Señor.

Por tanto,
dispón tu espíritu a sufrir pacientemente los muchos
inconvenientes y problemas de esta vida;
porque de seguro los encontrarás, y nunca podrás evitarlos,
aunque corras hasta los confines de la tierra, o te escondas en las cuevas más profundas;
y un sufrimiento llevado con paciencia es lo único que puede vencer su poder,
o sanar las heridas que ha hecho.
Pero aunque toda tribulación es dolorosa y lamentable, y el deseo de tu alma es evitarla,
el yo no puede evitar ser miserable; y la cosa misma que te esfuerzas por evitar,
te seguirá donde sea que vayas.
El soportar pacientemente la cruz y la muerte del yo sobre ella,
son los deberes indispensables del hombre caído.
Solamente así puede ser liberado de su oscuridad,
corrupción y miseria, y ser restaurado a la posesión de la vida, luz y paz en Cristo.

Entonces, sin tener otro deseo más que el de ir con ansias en pos de Él,
de morar siempre con Él, y de hundirnos en la nadedad delante de Él,
debemos aceptar sin discriminación todo lo que Él disponga, tanto oscuridad o luz,
fertilidad o esterilidad, debilidad o fuerza, dulzura o amargura, tentaciones, extravíos,
dolor, fatigas o dudas; y ninguno de ellos retrasará verdaderamente nuestro curso.
