[short="Sobre la Muerte al Yo"]
== Capítulo 10. Sobre la Muerte al Yo

Todos los esfuerzos que se hacen por mejorar al hombre externo,
sólo impulsan el alma hacia afuera,
hacia ese mundo en el que ya está fervientemente apasionada y ocupada,
y así sus poderes se difunden y esparcen por todas partes;
porque al dedicarse directamente a las cosas externas,
fortalece esos mismos sentidos que está tratando someter.

Este tipo de muerte a la carne nunca podrá conquistar las pasiones o reducir su actividad.
El único método efectivo para llevar a cabo esto, es el verdadero silencio interno,
por medio del cual el alma se vuelve entera y totalmente
al interior para poseer a un Dios presente.
Si el alma dirige todas sus fuerzas y energías hacia Él, en el centro de su ser,
este acto tan sencillo la separará y retirará en cierta medida de los sentidos externos.
El ejercicio de todos sus poderes internos deja a
los sentidos externos más debilitados e impotentes;
y entre más se acerca a Dios, más desprendida se siente de las cosas externas,
y las pasiones son menos influenciadas por ellas.

Al hacer morir así el ojo y el oído (que suministran continuamente
nuevos temas y estímulos a la imaginación inquieta),
hay poco riesgo de caer en el exceso.
Dios nos enseñará esto,
y solamente tenemos que dejarnos llevar por donde sea que Su Espíritu nos guíe.

El alma experimenta una doble ventaja cuando procede de esa forma; la primera es,
que al retirarse de los objetos externos se acerca más a Dios; y la segunda,
que al acercarse más a Él (además del poder y la virtud
que recibe) se encuentra aún más alejada del pecado.
Y así, eventualmente, dirigir la mente hacia Dios en el interior se convierte,
por así decirlo, en algo habitual.
