== Capítulo 11. Sobre la Rendición

Debemos rendir toda nuestra existencia a Dios, con la firme y segura convicción de que,
mientras nos esforcemos por seguirlo fielmente,
las circunstancias de cada momento serán conforme a Su directa voluntad o consentimiento,
y tal como lo requiere nuestra condición. Esta convicción nos hará
rendirnos en todas las cosas y aceptar todo lo que sucede,
no como algo que proviene de la creación de abajo, sino de Dios Mismo.

Pero les ruego a ustedes que desean rendirse con sinceridad a Dios,
que después de haberse ofrecido, no retrocedan.
Recuerden que un regalo, una vez entregado, ya no está a disposición de quién lo da.
La rendición es un asunto de suma importancia para nuestro progreso espiritual;
es la llave al atrio interior; de modo que,
quien verdaderamente sabe cómo rendirse a sí mismo, no tarda en volverse perfecto.
Debemos, por lo tanto, continuar firmes e inconmovibles en ella,
y no oír la voz de nuestro razonamiento natural.
Una gran fe produce una gran rendición. Debemos confiar en Dios,
"`en esperanza contra esperanza,`"^
footnote:[Romanos 4:18]
tal como Abraham, el padre de la fe.

La rendición es un abandono de todo interés egoísta,
quedando sujetos por completo a la Disposición Divina.
Todos los Cristianos son exhortados a la rendición, pues se les dice:
"`No os afanéis por el día de mañana;
porque vuestro Padre celestial sabe que tenéis necesidad de todas estas cosas.`"^
footnote:[Mateo 6:32, 34]
"`Reconócelo en todos tus caminos, y él enderezará tus veredas.`"^
footnote:[Proverbios 3:6]
"`Encomienda a Jehová tus obras, y tus pensamientos serán afirmados.`"^
footnote:[Proverbios 16:3]
"`Encomienda a Jehová tu camino, y confía en él;
y él hará. Exhibirá tu justicia como la luz, y tu derecho como el mediodía.`"^
footnote:[Salmo 37:5-6]

Esta virtud se practica al perder continuamente nuestra
propia voluntad en la voluntad de Dios;
al rendirnos en todas las cosas, dejando lo pasado en el olvido,
dejando lo que está por venir (tras haber hecho fielmente
nuestra parte) bajo la dirección de Dios,
y dedicando el momento presente a Él;
no atribuyendo nada de lo que nos sucede a la creación de abajo,
sino reconociendo todas las cosas como provenientes de Dios,
y mirando todo (excepto nuestros propios pecados)
como algo que sin duda procede de Él. Por tanto,
ríndanse a ser guiados y a estar dispuestos como Dios disponga.

Debemos cooperar voluntariamente y unirnos a los designios de Dios,
que tienden a desligarnos de todas nuestras obras, para que la Suya tome su lugar.
Permitan que esto ocurra en ustedes,
y no se apeguen indebidamente a nada por más bueno que parezca,
pues deja de ser bueno si en alguna medida los desvía
de lo que Dios quiere con respecto a ustedes.

La Voluntad Divina es más valiosa que todo lo demás.
Y nuestra conformación a este dulce yugo,
es lo que nos introduce en las regiones de paz interna.
Comprendiendo esto,
podemos saber con certeza que la rebelión de nuestra
voluntad es la razón principal de nuestro descontento,
y que ésta es la causa por la que sufrimos tanta angustia y ansiedad.
¡Oh, cuánta tranquilidad sentiríamos,
si sometiéramos nuestras voluntades a la Voluntad Divina
y pusiéramos todo a Su disposición! ¡Qué paz más dulce,
qué serenidad interna,
cuán sublime felicidad y qué consciencia de la bendición! Despojémonos, pues,
de todo apego a los intereses del yo, y vivamos sólo de la fe y de la rendición.
