[short="Sobre la Verdadera Conversión"]
== Capítulo 13. Sobre la Verdadera Conversión

[.centered]
"`__Volveos, volveos de vuestros malos caminos; ¿por qué moriréis, oh casa de Israel?__`"^
footnote:[Ezequiel 33:11]
"`__Volved a aquel contra quien se rebelaron profundamente.__`"^
footnote:[Isaías 31:6]

Convertirse verdaderamente,
es apartarse completamente de las cosas creadas y volverse completamente a Dios.

Para alcanzar la salvación es absolutamente necesario que
dejemos el pecado externo y nos volvamos a la justicia.
Pero esto en sí no es la perfecta conversión,
la cual consiste en un cambio completo del hombre, de una vida externa a una interna.

Cuando el alma se vuelve verdaderamente a Dios,
encuentra una facilidad maravillosa para continuar firme en esta conversión;
y cuánto más permanece convertida o vuelta,
más se aproxima y más firmemente se adhiere a Dios.
Y cuánto más se acerca a Él,
tanto más se aleja de ese espíritu que es contrario a Él. Así,
el alma llega a estar tan firmemente establecida y enraizada en su conversión,
que este estado se vuelve (en cierta medida) natural para ella.

Ahora, no debemos suponer que esto se deba a una intensa labor de sus propias fuerzas,
porque el alma no es capaz (ni debe intentarlo) de
ningún otro tipo de cooperación con la Gracia Divina,
sino la de esforzarse por retirarse a sí misma de los objetos externos,
y volverse internamente al Señor. Y tras hacerlo,
no tiene que hacer nada más que continuar firme en su unión a Dios.

Dios posee una virtud atrayente, la cual,
acerca el alma más y más poderosamente hacia Sí mismo,
cuánto más se aproxima a Él. Y en Su atracción, Él la purifica y la perfecciona,
tal como sucede con un líquido impuro que es evaporado por el sol, el cual,
al ascender gradualmente, se disipa y se vuelve puro.
En efecto, el líquido contribuye a su evaporación solamente a través de su pasividad;
pero el alma coopera con la atracción de su Dios a través de una libre y afectuosa correspondencia
y comunión. Este vuelco de la mente hacia el interior es fácil y eficaz,
y hace avanzar el alma naturalmente y sin dificultad,
porque Dios mismo es el centro que la atrae.

Por tanto, nuestro cuidado y atención deben consistir en alcanzar el silencio interno.
Y no nos desanimemos por las penas y dificultades que encontremos en este ejercicio,
que no tardará en ser recompensado por nuestro Dios
con una provisión tan abundante de Su fuerza,
que hará que el ejercicio sea cada vez más fácil,
siempre que seamos fieles en retirar humildemente nuestros
corazones de los objetos y de las gratificaciones externos,
y nos volvamos a nuestro centro, con los afectos llenos de ternura y serenidad.
Cuando en algún momento nuestros afectos se vuelvan turbulentos,
un suave retiro interno hacia un Dios presente los acallará y los apaciguará fácilmente.
Cualquier otra forma de contender contra ellos los irritará en lugar de calmarlos.
Una sola palabra de nuestro Salvador tiempo atrás, calmó un mar embravecido y furioso;
¿acaso no podrá calmar la conmoción de una alma perturbada,
si sinceramente clamamos a Él en nuestra angustia?
