[short="Sobre la Crucifixión del Yo"]
== Capítulo 14. Sobre la Crucifixión del Yo

El alma se vuelve apta para unirse a Dios al entregar el
yo al poder destructor y crucificador del Amor Divino.
Sin duda, este es el sacrificio más esencial y necesario en la religión Cristiana,
y la única forma de rendir un verdadero tributo a la soberanía de Dios.

Por la destrucción de la existencia del yo dentro de nosotros,
logramos reconocer verdaderamente la suprema existencia de nuestro Dios;
porque a menos que dejemos de vivir en el yo,
el Espíritu de la Palabra eterna no puede vivir en nosotros.
Ahora, cuando rendimos nuestra propia vida damos lugar a Su venida;
y cuando morimos a nosotros mismos, Él mismo vive y mora en nosotros.^
footnote:[Gálatas 2:20]

En efecto,
debemos rendir todo nuestro ser a Jesucristo y no vivir más para nosotros mismos,
para que Él se convierta en nuestra vida, y "`habiendo muerto,
nuestra vida esté escondida con Cristo en Dios.`"^
footnote:[Colosenses 3:3]
Al abandonarnos y renunciar a nosotros mismos, nos perdemos de vista en Él,
y ésto sólo puede llevarse a cabo mediante la crucifixión del yo,
que es la verdadera alabanza de adoración que rinde a "`Dios y al Cordero, alabanza,
y honra, y gloria y poder, por los siglos de los siglos.`"^
footnote:[Apocalipsis 5:13]

Efectivamente, esta es la oración de la Verdad.
Es "`adorar al Padre en espíritu y en verdad,`"^
footnote:[Juan 4:23]
porque aquí es donde experimentamos al Espíritu ayudándonos en nuestras debilidades,
e intercediendo por nosotros conforme a la voluntad de Dios.^
footnote:[Romanos 8:26-27]
Y siendo así influenciados por el Espíritu puro de Dios,
somos sacados y liberados de nuestra propia forma carnal y corrupta de orar.
Le rendimos el debido honor a Dios sólo mediante la crucifixión del yo.
Y en la medida en que esto es alcanzado,
Aquel que nunca permite un vacío en la naturaleza, nos llena continuamente de Sí mismo.

Si supiéramos las virtudes y las bendiciones que
el alma obtiene a partir de este tipo de oración,
estaríamos dispuestos a hacerla sin cesar.
Porque nos conduce a la perla de gran precio, al tesoro escondido;^
footnote:[Mateo 13:44, 46]
el cual, quien lo encuentra, de buena gana vende cuanto tiene para comprarlo.
Conduce a la fuente de agua viva que salta para vida eterna;^
footnote:[Juan 4:13-14]
a la verdadera adoración a Dios,
y al pleno cumplimiento de los más puros preceptos evangélicos.

Jesucristo nos afirma que el Reino de Dios está dentro de nosotros;^
footnote:[Lucas 17:21]
y esto es real en dos sentidos: Primero,
en el sentido de que Dios se convierte tan plenamente en nuestro Maestro y Señor interno,
que nada se resiste ante Su dominio; y entonces nuestro interior es Su reino.
Y segundo, cuando poseemos a Dios (que es el Bien supremo), también poseemos Su reino,
donde hay plenitud de gozo,
y donde obtenemos el propósito de nuestra creación. En efecto,
el propósito de nuestra creación es gozar de nuestro Dios, incluso en esta vida,
pero (¡ay!) cuán pocos son los que llegan a experimentar el gozo puro que da Su presencia.
