[short="Actuar Bajo la Influencia Divina"]
== Capítulo 15. El Hombre Actúa Más Noblemente Bajo la Influencia Divina, de lo que Posiblemente Podría Hacer Siguiendo su Propia Voluntad

Cuando algunas personas oyen sobre esta oración del silencio interno,
imaginan erróneamente que el alma permanece muerta e inactiva;
pero la verdad es que el alma actúa con más nobleza y amplitud que nunca antes,
porque Dios Mismo es su amado, y ahora actúa bajo el poder de Su Espíritu.
Cuando Pablo habla de ser "`guiado por el Espíritu de Dios,`"
él no quiere decir que debamos dejar de actuar,
sino que debemos actuar a través del poder interno de Su gracia.
Esto está perfectamente representado en la visión del profeta Ezequiel,
de las ruedas que tenían un Espíritu viviente; y dondequiera que iba el Espíritu,
ellas iban también. Ellas ascendían y descendían según eran movidas;
porque el Espíritu de Vida estaba en ellas, y ellas "`no se volvían cuando andaban.`"^
footnote:[Ezequiel 1:9]
De la misma manera,
el alma debe someterse a la voluntad de ese Espíritu vivificador con que es alumbrada,
y ser estrictamente fiel para seguirlo solamente cuando Él se mueve.
Por tanto,
nuestro trabajo debe consistir en esforzarnos por obtener y mantener un estado tal,
que sea el más susceptible a las impresiones Divinas,
y el más moldeable a todas las operaciones de la Palabra eterna.

Mientras un lienzo no sea estable,
el pintor es incapaz de representar una imagen fidedigna; de la misma manera,
cada acto de nuestro propio espíritu egoísta produce trazos falsos y erróneos.
Éstos distorsionan la obra y frustran el diseño de este adorable Pintor.
Por tanto, debemos permanecer en paz y movernos solamente cuando Él nos mueve.
Jesucristo tiene vida en Sí mismo, y Él es la vida de cada alma viviente.^
footnote:[Juan 5:26]

Como toda acción sólo tiene valor en proporción a
la dignidad de su verdadero origen o fuente,
este tipo de acción es incuestionablemente mayor que cualquier otra.
Las acciones que son producidas por la fuente u origen Divina, son Divinas;
pero las acciones que provienen de la criatura, aunque aparenten ser buenas,
son solamente humanas.
Jesucristo, la Palabra, "`tiene vida en Sí mismo;`"^
footnote:[Juan 5:26]
y siendo comunicador de Su naturaleza, Él desea comunicarla al hombre.
Por lo tanto, debemos abrir paso al fluir interno de esa Vida, lo cual puede lograrse,
sólo mediante la expulsión de la naturaleza caída y la represión de la actividad del yo.
Esto concuerda con la afirmación de Pablo: "`De modo que si alguno está en Cristo,
nueva criatura es; las cosas viejas pasaron; he aquí todas son hechas nuevas.`"^
footnote:[2 Corintios 5:17]
Pero este estado sólo se puede alcanzar muriendo a nosotros mismos,
y a toda nuestra propia actividad, para que la influencia de Dios pueda ocupar su lugar.

En efecto, el hombre puede abrir la ventana,
pero el Sol mismo es quien debe darnos la Luz.
Jesucristo ha ejemplificado esto en el Evangelio.
Marta hizo lo correcto, pero debido a que lo hizo en su propio espíritu,
Cristo la amonestó. El espíritu del hombre es intranquilo y turbulento,
y por esta razón hace muy poco aunque aparente hacer mucho.
"`Marta,`" dice Cristo, "`afanada y turbada estás con muchas cosas;
pero solo una cosa es necesaria; y María ha escogido la buena parte,
la cual no le será quitada.`"^
footnote:[Lucas 10:41-42]
¿Y qué había escogido María? Reposar en tranquilidad y paz a los pies de Cristo.
A la vista de todos, ella dejó de actuar,
para que el Espíritu de Cristo pudiera actuar en ella; dejó de vivir,
para que Cristo pudiera ser su vida.

Pedro, al calor de sus pasiones, le dijo al Señor que por Su bien,
él estaba listo y dispuesto a rendir su vida.
Pero al oír las palabras de una criada, lo negó.

Los diversos problemas de la vida se deben a que el alma no permanece en su lugar,
ni se contenta con la voluntad de Dios,
ni con lo que se le ofrece día a día. Muchas almas pueden
estar resignadas a la voluntad _general_ de Dios,
y aun así fallar con respecto al momento presente.
Y estando fuera de la voluntad de Dios,
caen una y otra vez mientras continúan así. Pero cuando vuelven a la Divina Voluntad,
todo sigue adelante bien.
Dios ama lo que se hace en Su propio orden, y según Su propia voluntad y tiempo;
y mientras te rindas fielmente a ello, harás todas las cosas bien.

Todos los hombres tienen más o menos deseos apasionados,
excepto los que viven en la Voluntad Divina.
Algunos de estos deseos pueden parecer buenos,
pero si no están de acuerdo con la voluntad de Dios,
el que descansa en la Voluntad Divina es infinitamente más pacífico,
y glorifica más a Dios.
Esto nos muestra cuán necesario es renunciar a nosotros mismos y a toda nuestra actividad,
con el fin de seguir a Cristo;
y que no podemos seguirlo verdaderamente sin ser vivificados por Su Espíritu.
Ahora, para que Su Espíritu pueda obtener una entrada en nosotros,
es necesario que nuestro propio espíritu sea primeramente subyugado:
"`El que se une al Señor,`" dice Pablo, "`un espíritu es con Él.`"^
footnote:[1 Corintios 6:17]

Todas las cosas deben ser hechas en su debido tiempo.
Cada estado tiene su comienzo, su progreso y su consumación;
y es un grave error detenernos en el inicio.
No hay habilidad adquirida por el hombre, salvo la que involucra el proceso necesario.
Primero debemos ocuparnos con diligencia y esfuerzo,
y al final segaremos la mies de nuestra perseverancia.
Cuando una embarcación está en el puerto,
los marineros se ven obligados a emplear todas sus
fuerzas para sacarla de allí y ponerla en el mar;
pero al terminar la podrán maniobrar con facilidad, como a ellos les agrade.
De la misma manera,
mientras el alma permanece atada al pecado y a los enredos de las criaturas,
se requieren esfuerzos muy frecuentes y arduos para lograr su libertad.
Las cuerdas que la sostienen deben ser soltadas, y luego,
por medio de fuertes e intensos esfuerzos, se desprende poco a poco de su antiguo puerto.
Pero luego, al dejar el puerto atrás, se dirige al refugio que desea alcanzar.

Cuando la embarcación está en marcha, a medida que avanza en el mar deja la tierra atrás;
y cuánto más se aleja del antiguo puerto,
menos dificultad y esfuerzo se necesitan para avanzar.
Por fin comienza a navegar sin dificultad, y en seguida avanza tan rápido,
que el remo que se ha vuelto inútil, se deja a un lado.
¿Cuál es el deber que tiene ahora el capitán? Él se contenta con desplegar las velas
y sujetar el timón. Desplegar las velas es dejar la mente presentada ante Dios,
para que pueda ser influenciada por Su Espíritu.
Sujetar el timón es impedir que el corazón se desvíe de su verdadero curso,
recuperándolo con gentileza y guiándolo firmemente con la regla del Espíritu bendito,
el cual gana gradualmente posesión y dominio de él; igual que el viento,
poco a poco hincha las velas y dirige la embarcación.

Mientras el viento sopla a favor, los marineros descansan de sus labores,
y la embarcación navega rápidamente sin esfuerzo.
Y cuando descansan así, dejando el barco al viento,
avanzan más en una hora de lo que habrían podido
avanzar en un largo periodo por sus propios esfuerzos.
En realidad, si ellos intentaran utilizar el remo en ese momento, no sólo se fatigarían,
sino que entorpecerían el avance de la embarcación debido a sus inoportunos esfuerzos.

Este es también el curso de acción que debemos seguir internamente;
y que nos hará avanzar en un corto tiempo--a través de la influencia Divina--infinitamente
más lejos que toda una vida gastada en actos repetitivos de esfuerzos propios.
Ciertamente, quienquiera que elija este camino, lo hallará más fácil que cualquier otro.

Si el viento es contrario y se desata una tormenta, en lugar de zarpar a la mar,
debemos echar el ancla para que sostenga el barco.
Nuestra ancla es una firme confianza y esperanza en Dios,
que aguarda pacientemente que cese la tempestad y que vuelva una brisa favorable,
tal como dice David: "`Pacientemente esperé al Señor,
y Él se inclinó a mí y oyó mi clamor.`"^
footnote:[Salmo 40:1]
Por lo tanto, debemos rendirnos al Espíritu de Dios,
entregándonos completamente a Su guía Divina,
y no permitir que ninguna circunstancia nos abata;
porque el abatimiento es la puerta por la cual el
enemigo ingresa al alma para robarle su paz.
Tampoco debemos preocuparnos ni ocuparnos con lo que otros digan o hagan,
pues esto sólo será causa de desasosiego.

Calmemos todos los movimientos de nuestro corazón tan pronto como lo veamos agitado.
Renunciemos a todos los placeres que no vengan sólo de Dios.
Acabemos con todos los pensamientos y divagaciones inútiles.
Busquemos diligentemente a Dios dentro de nosotros, y sin duda lo encontraremos;
y con Él hallaremos gozo y paz.
Ese gozo y esa paz prevalecen en medio del sufrimiento,
y debido a que fluyen de una fuente inagotable,
se convierten en una fuente perpetua de deleite.
"`La paz os dejo,`" les dijo Cristo a Sus seguidores, "`mi paz os doy;
no os la doy como el mundo la da.`"^
footnote:[Juan 14:27]

Si conociéramos la bendición de escuchar y obedecer a Dios,
y cuán grandemente se fortalece y se anima el alma por ello,
toda carne callaría delante del Señor.^
footnote:[Zacarías 2:13]
En efecto, todo se calmaría tan pronto como Él apareciera.
Pero para animarnos aún más en la ilimitada rendición a Él,
Dios nos asegura por el mismo profeta,
que no debemos temer rendirnos de esta manera a Él,
porque Su cuidado hacia nosotros sobrepasa el mayor cariño que podamos concebir:
"`¿Se olvidará la mujer,`" dice Él, "`de lo que dio a luz,
para dejar de compadecerse del hijo de su vientre?
Aunque olvide ella, yo nunca me olvidaré de ti.`"^
footnote:[Isaías 49:15]
¡Oh, bendita garantía llena de consuelo! ¡Quién, sabiendo esto,
temerá rendirse por completo a los tratos y a la guía de Dios!

Todos los hombres buscan la paz, pero la buscan donde no se encuentra.
Ellos la buscan en el mundo; el mundo siempre ofrece paz,
pero no puede darnos paz verdadera; porque dondequiera que vayamos,
llevamos en nosotros mismos la fuente fructífera de toda confusión;
__nuestra propia voluntad rebelde y egoísta.__
Una de las pasiones más peligrosas del corazón es la inclinación hacia la libertad carnal;
si seguimos esa inclinación, en lugar de seguir la verdadera libertad,
seremos conducidos a la esclavitud.
Como nuestras pasiones son los peores tiranos, si las obedecemos,
aunque sea parcialmente, estaremos siempre en una perpetua lucha y conflicto interno.
Y si nos rendimos completamente a ellas,
es espantoso pensar a qué extremos nos llevarían; pues ellas atormentan el corazón,
y como un torrente arrasan todo lo que está delante de ellas, y nunca están satisfechas.
La verdadera libertad solamente puede ser encontrada en Cristo,
cuya verdad nos hace libres,^
footnote:[Juan 8:32]
y nos hará experimentar que servirle a Él es reinar.

Esa piedad por la que somos santificados y consagrados por completo a Dios,
consiste en hacer Su voluntad con gran cuidado en todas las circunstancias de la vida.
Da los pasos que desees dar, haz las obras que quieras hacer,
deja que luzcan con esplendor,
pero nunca serás recompensado a menos que hayas hecho la voluntad de tu Soberano Amo.
Aunque tu siervo haya hecho maravillas en tu casa,
si no hizo lo que le ordenaste que hiciera, no valorarías su esfuerzo,
y con justa razón podrías quejarte de él por ser un mal siervo.

No hay un buen espíritu sino el Espíritu de Dios;
y cualquier otro espíritu que nos aleje del verdadero bien,
no es sino un espíritu de ilusión, por más halagador que aparente ser.
¿Quién desearía ser llevado en un magnífico carro por un camino que conduce al abismo?
El camino que lleva a un precipicio es aterrador, aunque esté cubierto con rosas;
pero el camino que lleva a la corona es deleitoso, aunque esté lleno de espinas.
Él nos ha dado a Su buen Espíritu para que nos enseñe,^
footnote:[Nehemías 9:20]
por tanto, no sigamos ya nuestra propia voluntad sino la Suya;
de modo que no sólo nuestros actos religiosos, sino todos los demás,
sean realizados con el propósito de complacerle a
Él. Entonces toda nuestra conducta será santificada.
Entonces nuestras obras se convertirán en un continuo sacrificio,
y nuestros corazones estarán ocupados con la oración incesante y el amor constante.
Por lo tanto, ¡sometámonos a la crucifixión de nuestra propia voluntad,
para que Su voluntad reine en nosotros!
Porque es Su potestad mandar y nuestro deber obedecer.
