[#cap16, short="La Paz y el Reposo Delante de Dios"]
== Capítulo 16. Sobre la Posesión de la Paz y el Reposo Delante de Dios

El alma que es fiel en el ejercicio de ese amor y unión a Dios que ya se ha descrito,
se asombra al sentir que Él gradualmente toma posesión de todo su ser,
y que un continuo sentido de Su presencia puede volverse, por decirlo así,
algo natural para él. La Presencia de Dios infunde una serenidad inusual a través de
todas nuestras facultades--ella calma la mente y brinda un dulce reposo y tranquilidad,
incluso en medio de nuestras labores diarias; y sin embargo,
es necesario que continuemos rendidos a Él sin reserva.

No obstante, debemos considerar como un asunto de suma importancia,
cesar de la actividad y esfuerzo del yo,
para que Dios sea el único que actúe. Él dice por medio de la boca de Su profeta David:
"`Estad quietos, y conoced que yo soy Dios.`"^
footnote:[Salmos 46:10]
Sin embargo, aquellos que atacan este tipo de oración y dicen que es ociosa,
se equivocan grandemente,
pues es una acusación que solamente puede surgir de la inexperiencia.
Si hicieran algún esfuerzo por alcanzarla,
pronto experimentarían lo opuesto de lo que suponen,
y encontrarían que sus acusaciones son sin fundamento.

Esta apariencia de falta de acción, de hecho,
no es una consecuencia de esterilidad o apatía, sino más bien de madurez y abundancia;
y esto lo percibirá claramente el alma experimentada.
El interior no es como una fortaleza que pueda ser poseída
por la fuerza y la violencia del esfuerzo humano.
Es más bien como un reino de paz que debe ser poseído por el amor.
Rindámonos entonces a Dios sin temor a correr peligro.
Él nos amará y nos capacitará para amarlo; y ese amor, que aumenta diariamente,
producirá en nosotros todas las otras virtudes.
Sólo Él puede llenar nuestros corazones que el mundo ha agitado e intoxicado,
pero que nunca ha podido llenar.
Verdaderamente, Él no nos quitará nada sino lo que nos hace infelices.

Por lo tanto, ya no temamos entregarnos completamente a Dios.
¿Cuál es el riesgo que corremos al depender solamente de Él? Pero
los que tienen toda la expectativa puesta en sí mismos,
serán inevitablemente engañados,
y deben recibir la reprensión que Dios da a través de Su profeta Isaías:
"`He aquí que todos vosotros encendéis fuego, y os rodeáis de teas;
andad a la luz de vuestro fuego, y de las teas que encendisteis.
De mi mano os vendrá esto; en dolor seréis sepultados.`"^
footnote:[Isaías 50:11]

A medida que el alma avanza,
no tiene necesidad de que otros medios la capaciten
o la preparen para acercarse al Señor,
aparte de esta tranquilidad de corazón; porque aquí,
la presencia de Dios (que es el mayor objetivo) y un estado continuo de oración,
comienzan a sentirse poderosamente, y el alma experimenta lo que el apóstol Pablo dice,
que "`cosas que ojo no vio, ni oído oyó, ni han subido en corazón de hombre,
son las que Dios ha preparado para los que le aman.`"^
footnote:[1 Corintios 2:9]
El alma disfruta algo de trascendente bendición, y llega a sentir que '`ya no vive,
mas vive Cristo en ella;`'^
footnote:[Gálatas 2:20]
y que la única forma de encontrarlo a Él es volviéndose internamente donde Él está presente.
A medida que hacemos esto, nos llenamos de los consuelos de Su presencia,
nos maravillamos de tan grande bendición,
y disfrutamos una comunión interna que los asuntos externos no pueden interrumpir.

Se puede decir de este tipo de oración. lo mismo que se decía anteriormente de la sabiduría:
"`Con ella me vinieron a la vez todos los bienes.`"^
footnote:[Sabiduría 7:11]
Porque diversas virtudes se realizan ahora con tanta dulzura y facilidad,
que se ven naturales y espontáneas.
