== Capítulo 17. Sobre la Perfección o la Unión del Alma con Dios

El estado más provechoso y deseable en esta vida es el de la perfección Cristiana,
que consiste en la unión del alma a Dios; una unión que incluye todo bien espiritual,
produce en nosotros una maravillosa libertad de espíritu que nos levanta
por encima de todas las circunstancias y los cambios de esta vida,
y nos libra de la tiranía del temor humano.
Da un poder extraordinario para realizar bien todas nuestras acciones,
y desempeñarnos con rectitud en todos nuestros deberes.
Provee una prudencia verdaderamente Cristiana en todo lo que emprendemos,
una paz y tranquilidad perfectas en todas las condiciones, y en resumen,
una continua victoria sobre el amor al yo y a las pasiones carnales.

Es imposible alcanzar la unión Divina solamente a través de la práctica de la meditación,
o por la agitación de nuestras emociones,
o incluso mediante la oración más iluminada y bellamente compuesta;
porque según la Escritura, "`no verá hombre a Dios, y vivirá.`"^
footnote:[Éxodo 33:20]
Ahora, todos los ejercicios de oración verbal, e incluso de contemplación activa,
cuando son llevados a cabo en la vida de nuestra propia voluntad,
no pueden hacernos ver a Dios;
porque todo lo que proviene del poder o esfuerzo propio del hombre--por
muy noble o sublime que sea--debe morir primero.

Juan relata que "`se hizo silencio en el cielo:`"^
footnote:[Apocalipsis 8:1]
Ahora, este cielo representa el centro de nuestra alma, en donde,
antes de que aparezca la majestad de Dios, todo debe ser acallado hasta el silencio.
Todos los esfuerzos, sí, la existencia misma del amor al yo debe ser destruida,
pues la voluntad natural es la que se opone a Dios,
y toda la maldad del hombre procede de ella.
De hecho,
la pureza del alma se incrementa en la medida que
la voluntad natural se somete a la voluntad Divina.

Por lo tanto, el alma no puede llegar a una verdadera unión Divina,
sino a través de la crucifixión de su voluntad; ni tampoco puede hacerse una con Dios,
a menos que sea restablecida en la pureza de su creación original.
Dios purifica al alma por medio de Su sabiduría como
los refinadores purifican los metales en el horno.
El oro no se puede purificar sino por medio del fuego,
el cual poco a poco separa de él y consume todo lo que es terrenal y contrario.
Esto debe ser fundido y disuelto,
y todas las mezclas impuras deben ser eliminadas lanzándolas una y otra vez al horno.
Entonces el oro ya no tendrá ninguna mezcla corrupta; su pureza es perfecta,
su simplicidad completa, y de esta forma es apto para la más exquisita obra.
Así podemos ver, que el Espíritu Divino, como un fuego incesante,
debe devorar y destruir todo lo terrenal, sensual y carnal,
junto con toda la actividad del yo,
antes de que el alma sea apta y capaz de experimentar una verdadera unión a Dios.

Dios dice: "`Haré más precioso que el oro fino al varón.`"^
footnote:[Isaías 13:12]
Pero cuando Él comienza a quemar, destruir y purificar, entonces,
el alma--al no percibir los designios ventajosos
de estas operaciones--se retrae de ellas.
Y así como el oro,
que cuando se introduce por primera vez en el horno parece oscurecerse en lugar de brillar,
el alma a menudo también cree que su pureza se ha perdido,
y que sus tentaciones son sus pecados.

Pero si admitimos que deleitarnos en Dios es el fin para el que fuimos creados,
que "`sin santidad`"^
footnote:[Hebreos 12:14]
nadie puede alcanzar dicho fin,
y que para alcanzarlo debemos pasar necesariamente por un proceso severo
y purificador--¡qué extraño es que temamos y evitemos este proceso!
Que todos, pues, sigan a la meta,
permitiéndose ser guiados y gobernados por el Espíritu de gracia,
el cual los conducirá infaliblemente al fin de su creación, el deleitarnos en Dios.

"`Sed, pues, vosotros perfectos, como vuestro Padre que está en los cielos es perfecto.`"^
footnote:[Mateo 5:48]
El alma que permanece en su propia voluntad desordenada, es imperfecta.
Se vuelve más perfecta, en la medida que se acerca a la voluntad de Dios.
Cuando el alma se ha acercado tanto que en nada puede alejarse de la Voluntad Divina,
entonces llega a ser completamente perfecta, transformada,
y a estar unida a la naturaleza Divina.
Y al estar así purificada y unida a Dios, encuentra profunda paz y dulce descanso,
lo cual la lleva a tal experiencia de amor, que se llena de gozo.
Se conforma a la voluntad de su Dios en cada circunstancia que se levanta,
y se regocija en todo para hacer lo que le agrada a Dios.

El Señor se acerca a tal alma y se comunica internamente con ella.
La llena de Sí mismo porque está vacía. La reviste
con Su luz y con Su amor porque está desnuda.
La levanta porque está caída, y la une a Sí.

Si deseas entrar en este cielo estando en la tierra,
olvida toda preocupación y todo pensamiento ansioso, apártate de ti mismo,
para que el amor de Dios pueda vivir en tu alma.
Así podrás decir junto con el apóstol: "`Ya no vivo yo, mas vive Cristo en mí.`"^
footnote:[Gálatas 2:20]
¡Qué felices seríamos si pudiéramos dejar todo por Dios,
si lo buscáramos únicamente a Él, si suspiráramos en pos de nadie más que de Él,
si Él fuera el único dueño de nuestros suspiros! ¡Oh,
prosigamos sin interrupción hacia el gozo de este bendito estado!
Dios nos llama a hacerlo.
Él nos invita a entrar a nuestro centro interior donde Él nos renovará y cambiará,
y nos mostrará un reino nuevo y celestial, lleno de gozo, paz,
contentamiento y serenidad.

Es aquí donde el alma espiritual,
apartada y de mente celestial encuentra una paz inquebrantable.
Y aunque se enfrente a muchas luchas en lo externo, y algunas veces se sienta desnuda,
abandonada, atacada y desolada, aun así,
estas tempestades nunca alcanzarán la serenidad celestial
interna en donde habita el amor puro y perfecto.
Porque aunque el príncipe de las tinieblas la asalte con violencia, aun así,
sigue firme y se mantiene como un pilar fuerte,
sin que le suceda más de lo que le ocurre a una alta montaña durante una tormenta.
El valle de abajo se oscurece con nubes densas y se ve acosado
con tormentas feroces de granizo y truenos,
mientras que la alta montaña resplandece bajo los brillantes rayos del sol.
En quietud y serenidad continúa despejada, inconmovible y llena de luz.
Un alma así es en verdad, "`como el monte de Sion, que no se mueve,
sino que permanece para siempre.`"^
footnote:[Salmo 125:1]

En este trono de quietud se manifiestan todas las perfecciones de la belleza espiritual.
Es aquí donde disfrutaremos la luz verdadera de los misterios divinos de Cristo.
Aquí encontraremos la perfecta humildad, la completa rendición,
la mansedumbre e inocencia de la paloma,
la libertad y pureza de corazón. Aquí se experimenta la alegre sencillez,
la imparcialidad celestial, la oración continua, la desnudez sin vergüenza,
la perfecta abnegación y la verdadera ciudadanía en los cielos.
Este es el tesoro valioso y escondido; esta es la perla de gran precio.

Fin
