== Capítulo 10 El Diario de Charles Marshall

[.section-date]
1637--1698

Nací en la ciudad de Bristol, en el cuarto mes de 1637.
Mi educación y crianza fueron según las más estrictas formas de la religión,
al ser mi padres muy temerosos del Señor. Ellos me
mantuvieron alejado de la compañía de otros niños,
y alrededor de los cinco o seis años aprendí a leer las Escrituras de la verdad,
en las cuales, después de poco tiempo, me deleitaba mucho.
Desde mis más tiernos años, aborrecí las palabras vulgares, las mentiras y otros pecados,
y no sólo eso,
sino que muchas veces tenía deseos y respiraciones internas por conocer a Dios.
Así, alrededor de los once o doce años, no sólo deseaba conocer al Dios verdadero y vivo,
sino que también Lo buscaba,
y amaba y estimaba a las personas sobrias y honestas que temían al Señor.

Yo iba con mi madre a las reuniones de los Independientes,
en los días cuando todavía eran tiernos y sinceros.
A veces iba a las reuniones Bautistas,
para oír a aquellos hombres que eran estimados los más celosos
en sus días. Entre estas personas y en esas asambleas,
hubo algunas veces despertares espirituales por las
agitaciones y esfuerzos internos del don de Dios,
y bajo el sentido de esto,
en muchas almas brotaron anhelos y respiraciones vivas tras el
conocimiento verdadero y espiritual de Dios quien es Espíritu.
Pero la mayoría salió de este estado de ternura y
se atascaron en la profesión de las palabras,
obras y experiencias de los santos, dejando atrás esa medida pura de luz, vida y verdad.

Luego a medida que crecía,
me sentía cada vez más insatisfecho con las profesiones y profesantes sin vida y vacíos,
al sentir el peso de la naturaleza de pecado que estaba sobre mi espíritu.
En la consciencia de mi pecado,
me convertí en un persona solitaria y lloraba como una paloma sin compañero.
Y al ver que no podía encontrar la vida entre las profesiones muertas del cristianismo,
pasé mucho tiempo retirado solo, en campos y bosques, y por manantiales de agua,
donde me deleitaba recostarme y beber.
En aquellos días de retiro, mis clamores al Señor eran fuertes, grandes y muchos.
A veces, estando retirado en lugares libres de toda compañía,
a fin de aliviar mi corazón, lloraba audiblemente debido a la pesadez de espíritu.

En aquellos días tuve revelaciones de la miserable
caída e inexpresable degeneración de la humanidad,
y del cautiverio y esclavitud en la que se encontraba mi alma.
En la verdadera consciencia de este estado de esclavitud y servidumbre lloraba diciendo:
"`¡Ojalá mi alma fuera aliviada de estas cargas y pesos de muerte y tinieblas! ¡Ojalá
yo fuera salvado del obvio estado de tinieblas egipcio y de la tierra de sequedad;
la tierra de angustia, la tierra de horrible oscuridad!`" "`¡Oh,
indescriptible caída,`" decía mi alma.
"`¡Oh, inexpresable pared de división y separación! ¡Oh, indecible abismo!`"
Pues el estado caído y perdido de los hijos e hijas de los hombres,
me fue revelado más allá de toda palabra de explicación.

En ese tiempo, mientras caminaba y contemplaba la creación del Todopoderoso Dios,
todo testificaba en mi contra.
El cielo y la tierra, el día y la noche, el sol, la luna y las estrellas, sí,
las corrientes de agua y los manantiales de lo profundo,
todo conservaba sus respectivos lugares.
La hierba y las flores del campo, los peces del mar y las aves del aire;
todo mantenía su orden, sólo el hombre, la principal obra de la mano de Dios,
estaba degenerado.
Entonces lloraba amargamente:
"`¡El estado del hombre en la caída es peor que el de la bestia que perece!
Porque '`el buey conoce a su dueño,
y el asno el pesebre de su señor,`' pero el hombre en este estado,
no conoce a Dios su hacedor, y se ha convertido en un extraño para Él,
caminando en enemistad y desobediencia, y sirviéndole y obedeciendo al diablo,
que no ha creado nada, ni puede preservar ninguna cosa viva!`"
Desde el principio, la aparición de Satanás contra Dios ha sido enemistad pura,
completamente malvada, destructiva y asesina.
Y tal es la indescriptible y espesa oscuridad que ha venido sobre el hombre,
que se entrega en cuerpo,
alma y espíritu para ser guiado por él. En esto vi que una
espesa oscuridad había venido sobre las familias de la tierra,
y podía certificar la verdad de esa Escritura que dice:
"`Tinieblas cubren la tierra y oscuridad las naciones.`"^
footnote:[Isaías 60:2]

Y así, con una profunda consciencia de la miserable condición del hombre,
y particularmente de mi propio cautiverio y participación en esa oscuridad,
miseria y tristeza,
caía al suelo y clamaba a Dios por liberación y redención de dicho estado.
Y aunque el testigo de Dios se agitaba en mí de esta manera,
y fue de hecho el revelador de este miserable estado,
aun yo no tenía un conocimiento claro de Aquel que me lo había revelado.

En ese tiempo, alrededor del año 1654, muchos buscaban al Señor,
y unos pocos de nosotros guardábamos un día a la
semana en ayuno y oración. Cuando llegaba el día,
nos reuníamos temprano en la mañana, y sin haber probado nada nos sentábamos,
a veces en silencio.
Cuando alguno encontraba algo sobre su espíritu y una inclinación en su corazón,
se arrodillaba y oraba al Señor. En ocasiones, antes de que terminara el día,
podía haber unos veinte de nosotros reunidos.
Hombres, mujeres, y de vez en cuando niños, decían unas pocas palabras en oración,
y a veces estábamos muy postrados y quebrantados delante del Señor en humildad y ternura.

En el año 1654, llegaron a una de estas reuniones los queridos John Audland y John Camm,
mensajeros del Dios vivo.
Por el poderoso ministerio de John Audland (que le fue encomendado por el Señor),
fui alcanzado y vuelto al Espíritu de Dios (el Mismo
que anteriormente me había revelado mi condición,
como se mencionó). El testimonio que fue llevado
por estos dos mensajeros fue recibido de buena gana,
y mientras me mantenía cerca del Espíritu, al cual estaba vuelto,
vi una gran separación hecha entre la luz y las tinieblas, el día y la noche,
lo precioso y lo vil.
Y como mi mente amaba la luz, el juicio fue establecido en mi corazón,
o sea "`puesto por medida, y la justicia por nivel.`"^
footnote:[Isaías 28:17 LBLA]

Fui llevado a un gran pavor, temor y asombro de Dios,
y también tenía gran estima y respeto por Sus mensajeros,
quienes trajeron las buenas noticias de vida y salvación,
y a través de quienes la verdadera doctrina cayó como el rocío.
Debido a que las palabras de ellos eran palabras de gracia,
había un gran temor en mi corazón de rebelarme contra
alguna parte del consejo que recibí de ellos.

Luego experimenté un largo viaje a través de la administración de condenación,
la cual fue en verdad gloriosa en su tiempo.
Descubrí que mientras me mantenía bajo el juicio del Señor en mi corazón,
este operaba como una espada, un fuego y un martillo,
y la naturaleza malvada era en alguna medida vencida.
Entonces, algo del alivio y amor divinos fluían, y me refrescaban en mis viajes.

Pero luego, el antiguo y astuto enemigo empezó a tenderme trampas y a cazar mi alma,
la cual había sido en alguna medida rescatada de las fauces de la muerte.
Porque cuando tenía revelaciones preciosas del camino de la Verdad
(a través de las cuales brotaban esperanza y gozo secretos),
el enemigo me impedía crecer en la verdad y atesorar el dulce deleite de ella,
al hacerme gastar mi propio pan defendiendo la verdad contra los
opositores y declarándola a aquellos que creía que la amaban.
Y cuando había gastado el pan que me había sido dado para la fuerza de mi propia alma,
y regresaba a casa y meditaba en mi corazón, me descubría bastante vacío,
pues había regalado lo que me había sido dado para mi propio refrescamiento y consolación,
y veía que mi Amado se había retirado.
Entonces la angustia se apoderaba de mí más allá de toda expresión y me sentía muy abatido.
Al tener algún entendimiento de la causa,
estaba listo para prometer que si yo volvía a tener la paz,
refrigerio y alimentación anteriores,
no volvería a salir corriendo apresuradamente ni gastaría mi porción,
razón por la que esa dificultad y aridez internas habían venido sobre mi espíritu.
Aquí el enemigo (quien mediante su disfraz me había desviado),
trabajó sutilmente en el día de mi angustia,
a fin de traer gran desánimo e incredulidad sobre mi espíritu.

Mi alma recuerda la gran ansiedad de espíritu,
la consciencia que tenía de que el Señor se había retirado y ocultado Su rostro,
y la experiencia del velo que caía sobre mí. De esta manera fui llevado
a un celo que no concordaba con el verdadero conocimiento (es decir,
el conocimiento que da el poder del Señor en Su guía),
y cuando había prometido y luego roto el pacto,
era perseguido por el Señor como un quebrantador del pacto.
Pero con el tiempo el Señor me ayudó a través de
esta prueba y aprendí a permanecer como un tonto,
y a sentarme en silencio delante del Señor entre Su pueblo,
en lugar de perjudicar mi condición y contristar al Espíritu de Dios.
Y cuando permanecía obediente a la dirección de la sabiduría,
entonces un gozo secreto brotaba en mí, con paz pura y alivio interior.
Pero si sentía la vida, el gozo y la luz del Señor brillando sobre mi tabernáculo,
y aun así no me mantenía postrado en humildad (donde
es experimentado el crecimiento en la Verdad),
el enemigo obraba con sutileza de nuevo,
para persuadirme de que no había necesidad de una
vigilancia y cuidado internos tan estrictos,
como antes.
En algunas ocasiones prevaleció a través de este engaño, para llevarme a una libertad,
tanto interna como externa,
que tenía la tendencia de llevarme otra vez a la esclavitud interior.

A través de frecuentes renovaciones, revelaciones, profecías y promesas,
algunas veces estaba listo a concluir que mi montaña era inamovible.
Pero pronto descubría que el Señor retiraba Su presencia,
y luego experimentaba un invierno de nuevo y diversas tormentas del enemigo.
Y al no haber aprendido a contentarme con la necesidad, como con la abundancia,
no sólo caía en un estado pobre y murmurador, sino también en gran aflicción,
porque debido a este cambio, estaban listos a entrar temores y dudas.
Trabajaba duro en esta noche,
pero no podía obtener nada que administrara algún consuelo duradero.
Al estar en gran temor y tristeza, me encontraba deseando, corriendo, y esforzándome,
pero cuánto más me afanaba, '`encendiendo teas por mi cuenta`' (Isaías 50:11),
más se incrementaba mi tristeza, porque no había aprendido aún el estado de rendición.

Entones, tras haber sido llevado muy bajo,
y habiendo llorado muchos días en la consciencia de los retiros de la presencia,
amor y poder de mi Dios, y estando en profunda angustia y estupor,
me fueron revelados los viajes de Israel en el desierto;
la manera en que Dios los probó con falta de pan y agua.
Vi que la felicidad de ellos radicaba en contentarse y rendirse a la voluntad de Dios,
y en la creencia de que la fidelidad del Señor los ayudaría a soportar la prueba.
Pero Israel murmuraba, y de este modo contristaba al Espíritu de Dios,
y yo también. Sin embargo,
a través de la compasión de Dios el estado de rendición me fue revelado,
en el que el hombre estaba antes de caer mediante la transgresión,
en su propia obra y voluntad.
Y cuando mi entendimiento fue así abierto, mi alma clamó al Señor mi Dios: "`¡Oh,
guárdame en paciencia y mansedumbre puras, y en obediencia viva y aceptable,
y confiaré en Ti!`"

Conforme creía en la luz del Señor, me ubicaba en ella y me rendía a ella, el poder,
amor y vida puros de Dios irrumpían como antes y me refrescaban en gran manera.
Entonces el sol brillaba sobre mi tabernáculo y yo me inclinaba delante del Señor,
bendiciendo y alabando Su santo y glorioso nombre.
Entonces el Señor me instruía y Su Espíritu y poder me revelaba el camino de preservación,
el cual era, ser reducido a la verdadera humildad.
Y así,
mi alma empezó a ser como la paloma que encontró un lugar para la planta de sus pies.

Sin embargo, el enemigo continuaba tentándome por medio de sus seducciones,
y poniendo sus cebos y trampas,
de modo que si en algún momento mi corazón era atraído a mirar
hacia fuera o se salía a ver la tierra (como hizo Dina,
Génesis 34), yo quedaba expuesto a un gran peligro de ser contaminado.
En realidad,
descubría que si en algún momento me salía del poder puro y preservador de Dios,
que había comenzado a obrar en mi alma (a través de estos dolores de parto),
y dejaba entrar el espíritu y razón del mundo, y por tanto,
veía alguna belleza en algún fruto que no era el producido por el árbol de la vida,
entonces una herida, una mancha y una contaminación se apoderaban de mi rápidamente.

Atravesé este ejercicio interno cuando ningún amigo o conocido íntimo sabía de él. ¡Oh,
recuerdo las noches de amarga tristeza por las que pasé,
aunque caminaba inocentemente entre los hombres y ninguno podía discernir
la corrupción! Pues en el gran amor de Dios hacia mi alma,
en aquellos días de prueba y ejercicio internos,
el juicio rápidamente seguía sobre cualquier salida de mi mente.

Pero mientras me mantenía vuelto hacia el Señor y recto de corazón,
y no me unía a ninguna iniquidad,
encontraba al Señor a mano en muchas pruebas que
sucedían en nuestra ciudad y en otros lugares,
incluso durante la obra del poder de las tinieblas en James Nayler,
y la salida de John Perrot y otros.^
footnote:[James Nayler y John Perrot fueron prominentes
ministros entre los primeros cuáquero,
que se salieron al error e imaginación,
y trajeron sobre la joven Sociedad una medida de división y desgracia.
Nayler abiertamente confesó su error,
se arrepintió públicamente en multitud de ocasiones,
y fue restaurado a la Sociedad de Amigos antes de su muerte en 1660.
Al parecer, Perrot emigró a Barbados, donde él y sus opiniones terminaron en descrédito.]
Dios me dejó ver (siendo entonces un joven muchacho) a través
de todas esas obras y sutiles disfraces del enemigo,
y me preservó mediante una mano secreta.
No siento dejar mucho por escrito sobre esos tiempos difíciles.
Esas cosas son conocidas por el Señor, junto con las causas y los fines,
y Su permiso y libertad otorgada al enemigo.

Dios ha deseado mantener postrado a Su pueblo en cada generación,
y mediante Su poder ha golpeado secretamente todo
lo que tiene una tendencia a robarle Su honor.
Él se deleita en el humilde y mora con el quebrantado y contrito de espíritu.
En este estado de postración, se encuentra nuestra seguridad y preservación en esta edad,
y en todas las edades sucesivas.
A través de estos ejercicios (de los que he dado un indicio) he aprendido,
que desde el inicio mismo de la obra de restauración y redención en cada individuo,
la preservación de todos se encuentra en que nos retiremos internamente hacia Dios,
en que nos mantengamos muy humillados (en el puro temor, asombro y pavor del Señor),
y en que palpemos en pos de Su poder redentor y preservador
del alma que vivifica y aviva.
En la medida que habitemos aquí, eso nos mantiene vivos en su propia naturaleza pura,
sobre el mundo y sobre su espíritu y corrupción.

Estoy persuadido en mi espíritu, más allá de las palabras,
de las potentes obras del enemigo en las generaciones de la humanidad para lograr su fin,
a saber: Después de que el Señor Dios Todopoderoso ha aparecido en alguna época,
en el libre derramamiento de Su amor,
surgimiento de Su poder y extensión de Su brazo para restaurar al hombre en pacto con Él,
el enemigo ha aparecido luego, con todo su poder y sutileza,
para gradual y secretamente socavar y frustrar la obra de Dios.
Su gran propósito ha sido, por medio de diferentes trampas,
arrastrar a las personas visitadas a una disminución de su aprecio del poder,
aparición y manifestación de Dios en sus días,
y sacar sus mentes (mediante sus múltiples disfraces) hacia una estima,
ya sea de la manifestación que ha sucedido o de la que puede estar por venir.
Esto saca a la mente del debido respeto por la _presente_ manifestación,
la única que puede obrar el bienestar eterno de la criatura.
Este fue el caso de aquellos a quienes se les dijo: "`¡Oh, si también tú conocieses,
a lo menos en este tu día, lo que es para tu paz!`"
Esto lo he aprendido del Señor, y por tanto lo dejo,
tanto a los Amigos a quienes pueda llegar en esta época,
como al pueblo de Dios en las siguientes generaciones del mundo.

Después de casi dieciséis años de viaje en el espíritu, en el año 1670,
a mis treinta y tres años,
el Dios Todopoderoso me levantó por medio de Su poder que
había estado obrando en mi corazón por muchos años,
a predicar el evangelio eterno de vida y salvación. Entonces empezó un nuevo ejercicio,
ya que el enemigo me tentó a resistir al Señor,
a mirar mi propia debilidad de cuerpo y espíritu,
y mi insuficiencia para una obra tan grande.
Tal era la fuerza del enemigo en mi alma,
que si el Señor Dios (en Su indescriptible amor) no hubiera estado conmigo,
no me hubiera sostenido, ni me hubiera ayudado,
habría perecido después de todo por la desobediencia.
Porque cuando el poder de Dios cayó sobre mí,
y me fue requerido que dijera unas pocas palabras
en las asambleas del pueblo del Señor en Bristol,
me asaltaron muchos razonamientos, a saber:
Que estas eran personas sabias y que no podía agregarles nada a ellas;
que yo podría dañar mi propia condición;
que las imaginaciones podrían ser la base real de tales demandas;
que muchos hombres sabios me verían como un muchacho presuntuoso y me juzgarían; etc.
Así razoné muchas veces durante las reuniones, hasta que me sentía muy angustiado,
y cuando las reuniones terminaban (en las que había sido desobediente),
mi carga era insoportable.
¡Oh, entonces estaba listo a pactar con el Señor,
que si yo sentía las demandas de Su poder de nuevo,
fielmente me rendiría en obediencia a Él! Pero cuando era probado otra vez,
la misma mente rebelde era movida por el poder del enemigo.

Entonces el Señor retiró el movimiento y sentido de Su poder,
y todo refrescamiento con él, y escondió Su rostro de mí. Fui dejado en gran pena,
sintiendo que otros se alimentaban del pan de vida
en nuestras reuniones y sacaban el agua de vida,
pero mi alma salía vacía, con grandes barrotes sobre ella,
encerrándola (por decirlo así) bajo tinieblas.
Yo experimentaba el disgusto del Señor y estaba doblegado en gran angustia.
Y mi alma clamaba al Señor que me probara otra vez e irrumpiera con Su poder,
y que me diera un claro conocimiento de Sus demandas,
y yo lo obedecería. Entonces el Señor Dios de vida oyó mi
clamor de nuevo y abrió mi corazón que se encontraba cerrado.
Y cuando comencé a sentir el poder de Dios moverse en mi hombre interior,
por un lado me alegré, pero por otro me entristecí,
al temer que yo fuera rebelde otra vez.

En efecto, fue tan difícil para mí abrir mi boca en aquellas reuniones de Bristol,
que si el Señor no hubiera manifestado Su poder en mi corazón
como vino nuevo en una vasija que necesitaba respiradero,
y no hubiera abierto paso con Su poder en muchas ocasiones, yo habría perecido.
Pero el Señor tenía en cuenta mi estado y conocía también el estado
de las personas entre las que yo me reunía. Y cuando,
por el gran amor y poder de mi Dios, yo finalmente superé la prueba,
entonces las trampas del enemigo quedaron expuestas,
por lo que mi alma alabó al Señor Dios de mi vida.
En verdad he sido, y sigo siendo,
quebrantado a menudo en la consciencia de Su bondad
hacia mí cuando no era más que un niño,
no, cuando no era más que un gusano.
¡En este tiempo, en el verdadero sentido y fresco recuerdo de Tu amor, bendigo,
magnifico y exalto Tu nombre, oh, Señor. En verdad, Tú eres Dios y haces bien,
y eres digno de todo temor, obediencia, reverencia y honor por los siglos de los siglos!

Después de que (a través de la bondad,
amor y poder de Dios) obtuve alguna medida de dominio sobre lo que me estorbaba,
fielmente le rendí a mi Dios mi libertad, posesiones, relaciones y todo,
y fui llevado a las asambleas del pueblo del Señor
en la ciudad de Bristol y lugares adyacentes.
Conforme me rendía en obediencia, encontraba que mi camino había sido hecho más fácil,
y veía al enemigo (que se esforzaba por estorbarme) más y más conquistado.
En el año 1670, recibí la siguiente comisión de Dios:
"`Recorre la nación y visita Mi semilla sedienta y herida,
la que engendré entre Mi pueblo el día de su primera tierna visitación. Proclama Mi
año aceptable y el día de la perfecta liberación de Mi semilla sedienta y herida,
y también, el día de venganza que viene sobre todos los que la han herido,
ya sea entre Mi pueblo o en el mundo.`"
Entones clamé al Señor diciendo: "`¿Cómo visitaré a Tu pueblo en estos tiempos,
cuando la vara de los malvados está sobre sus espaldas,
y cuando los hombres en casi todo lugar se esfuerzan por
medio de la violencia a dispersar las asambleas de Tu pueblo?
¿Cómo me reuniré con ellos?`"
Y el Señor dijo: "`Ve, Yo prosperaré tu camino,
y la prueba presente sobre Mi pueblo será como una nube matutina,
y seré para ellos como tierno rocío a lo largo de la tierra.`"
Entonces, me incliné delante del Señor y viajé en obediencia a Su mandamiento,
y desde el final del mes décimo de 1670, hasta el 20 del décimo segundo mes de 1672,
estuve en unas cuatrocientas reuniones.^
footnote:[Durante este largo viaje al servicio del evangelio,
Charles Marshall visitó la mayor parte de Inglaterra y estuvo varias veces en Londres.
Una vez, durante una breve estadía en su casa,
se enfermó tanto que casi todos se desesperaron por su vida.
En otra ocasión, experimentó una aflicción muy dolorosa por la muerte de su hijo.]

Muchos fueron convencidos en mis viajes, las bocas de los opositores fueron detenidas,
y el Espíritu de Dios cayó sobre varios que ahora
tienen un testimonio que dar de Su nombre.
Varias veces estuve muy debilitado en mi cuerpo, incluso, al borde de la muerte.
Sin embargo, mi Dios Todopoderoso, en amorosa bondad,
me levantó de nuevo de manera maravillosa, particularmente en dos ocasiones.
Grandes fueron las pruebas, penas, dificultades y peligros por los que pasé,
tanto internos como externos, que sólo mi Dios Todopoderoso conoce,
y grandes fueron Sus liberaciones de muchas maneras.
En una ocasión, cuando estaba en Lancashire, cerca de la casa de Margarita Fox,
fui maravillosamente preservado junto con otras cuatro personas.
Nosotros habíamos bajado a la orilla del mar para cruzar las arenas,
y dos personas que vivían al otro lado nos informaron que podíamos ir seguros;
nada parecía contradecir lo dicho.
Pero cuando yo intenté ir, fui detenido en mi mente,
y después de esperar en el Señor un momento, me fue claramente prohibido hacerlo.
Me fue mostrado que si alguno intentaba continuar en ese momento,
ciertamente perecería. Esto me hizo obstaculizar la salida de los pasajeros,
y aproximadamente una hora después el mar se desbordó,
así que si nosotros hubiéramos ido, con toda probabilidad habríamos muerto.
Cuando algunos que estaban ahí vieron esto,
fueron grandemente enternecidos y magnificaron el nombre del Señor.

[.offset]
En la visita a la ciudad de Londres dejé un pequeño documento,
una copia del cual escribo a continuación:

[.embedded-content-document.address]
--

Una advertencia a todas las personas que han inclinado
su oído a la declaración de la Verdad,
pero no la han recibido en el amor de ella.
Una advertencia a los que están convencidos de la Verdad,
pero no se han sujetado a ella en obediencia pura y viva.
Una advertencia a todos los que han comenzado en
el Espíritu y dirigido sus rostros a Sión,
para que no regresen a Egipto (espiritualmente así llamado),
ni se sienten a lo largo del camino.

El terrible Día de venganza de Dios es proclamado,
en el que todos los profesantes del cristianismo y sus profesiones serán probados.
La era será completamente limpiada, el trigo aventado, el oro probado,
y el Día de Dios vendrá sobre todas las imágenes y semejanzas.
En realidad, se hollará todo lo que se haya levantado sin el poder antiguo y eterno.
Habrá un día de calamidad, miseria,
asombro y angustia sobre los habitantes de la ciudad de Londres,
y de dolor sobre la nación de Inglaterra; y después de este, a lo largo de las naciones,
un día de reunión de los esparcidos de Israel y de los dispersos de Jacob.

--

En el nombre y autoridad del Dios Todopoderoso,
también descargué mi consciencia en la ciudad de Bristol,
y no retuve nada del consejo del Señor para ellos.
Sino que en el poder y demostración de Su Espíritu, y con toda claridad,
prediqué la Verdad como está en Jesús,
manifestando las muchas trampas del enemigo que acompañan a los Amigos de esa ciudad.
Estoy limpio de la sangre de los habitantes de esa
ciudad y de todos los que profesan la Verdad en ella;
y estoy seguro de que un día de profunda prueba vendrá sobre muchos de sus habitantes.
Así como fue mi testimonio en la ciudad de Londres, fue en la ciudad de Bristol.

En mis viajes por la tierra, se hicieron muchos intentos de encarcelarme,
pero el Señor estaba conmigo y Su palabra era como un fuego en mis huesos,
"`recorre la tierra.`"
En verdad,
el Señor me ayudó en la batalla espiritual contra el enemigo de las almas de los hombres.
En ese tiempo, se promulgaron leyes contra todo disidente,^
footnote:[Eran disidentes los que no se conformaban a las doctrinas,
creencias o prácticas de la iglesia de Inglaterra.]
y se les dio autoridad a los magistrados de multar con veinte libras
al propietario de cualquier casa donde se realizara una reunión,
junto con veinte libras por el predicador y cinco chelines por cada oyente.
Y el que informaba al magisterio de alguna de estas reuniones,
recibía una tercera parte de la multa.
Sin embargo, aunque este fue un tiempo de dolorosa persecución a lo largo de la nación,
en mi paso a través de las ciudades, pueblos y todos los condados de Inglaterra,
no se le permitió a ningún hombre que pusiera sus manos sobre mí, ni detuviera mi camino;
ningún hombre, que yo sepa,
perdió cinco libras por mi causa en toda la nación. Dejo esto a la posteridad,
no para gloria del yo, sino para magnificar y exaltar el santo poder del Señor,
y para que muchos viajeros que todavía están por levantarse,
sean refrescados y confíen en el Señor Jehová, en quien está la fuerza eterna.
Aunque Él nos llama a cosas difíciles, no es un Maestro duro,
porque Él da poder a todo el que cree y confía en Él,
cuyo brazo derecho de salvación ha hecho cosas gloriosas
en nuestro día. ¡A Él sean dadas eternas alabanzas,
honor, santa acción de gracias y reconocimiento por los siglos de los siglos!

Después de esto no viajé tan continuamente,
ni guardé un registro de muchas cosas y liberaciones
notables que me encontré en mis viajes.
Pero esto lo puedo decir con toda certeza y en la presencia de mi Dios,
que Él abrió la puerta de los corazones de las personas tan eficazmente,
que creo que miles recibieron la Palabra de vida y muchos
fueron añadidos a la iglesia en diversos lugares.
Se establecieron algunas reuniones donde nunca había habido un Amigo antes.
En un lugar, toda una reunión fue convencida a la vez,
y nunca oí que alguno de ellos se volviera,
sino que todos permanecieron fieles al Señor. La ternura
que he visto en muchos lugares a lo largo de la tierra,
y las lluvias de vida que han descendido sobre la plantación del Señor,
están más allá de toda expresión. Muchos que habían apostatado y se habían desviado,
fueron eficazmente alcanzados y nuevamente traídos de vuelta.
Por tanto, puedo verdaderamente decir que el Señor estaba conmigo y que me abrió camino,
según Su palabra para mí antes de que yo saliera.

Yo continué obrando hasta que John Story y John Wilkinson, junto con sus seguidores,
se opusieron al orden y disciplina que fueron establecidos
entonces en las iglesias de Cristo.
Esta oposición se llevó a cabo bajo el engañoso pretexto
de defender la libertad de consciencia,
pero su verdadero origen estaba en un indebido deseo de libertad en la carne,
y en un espíritu miedoso y perezoso que se volvió del poder del Señor,
y de la dependencia diaria en su fresco surgimiento y vivificación. Estos hombres buscaron
retener el ministerio de la parte doctrinal de la Verdad en un espíritu seco y muerto,
mientras se esforzaban por destruir nuestras reuniones mensuales, trimestrales y anuales,
y las reuniones de mujeres, llamándolas "`formas`" e "`ídolos,`" cuando en realidad,
era el mismo poder y sabiduría divinos los que nos reunían para ser un pueblo,
y causaron la creación y establecimiento de un buen orden y disciplina entre nosotros.

Grande fue el viaje y obra de nuestro anciano y honorable Amigo, George Fox,
en este importante asunto, en la primera aparición de la Verdad en esta era.
Varios otros hermanos también fueron profundamente
inspirados a establecer reuniones en dicho buen orden,
y hallamos que el Señor estaba con nosotros en nuestra obra y servicio.
El poder del Señor había obrado poderosamente para establecernos en un buen orden,
a fin de que apareciéramos al mundo guiados por Su sabiduría,
al ser hallados en una forma de piedad que surgía de Su poder interno en el alma.

Pero el enemigo, que deseaba que fuéramos un pueblo en confusión,
y Babel en lugar de Sión,
obró en la sabiduría terrenal y sensual de algunos hombres de espíritu descuidado,
que habían perdido su sentido de las guías del Todopoderoso.
Estos fueron conducidos a la falsa imaginación,
de que nosotros íbamos a desviarnos de la guía interna del Espíritu de Dios,
al establecimiento de formas externas como otros grupos religiosos,
dejando así la luz de Jesucristo,
la cual debía ser la guía de cada hombre en la fe y en la práctica.
En seguida ellos se esforzaron, con todas sus fuerzas,
por derribar y arruinar las reuniones antes mencionadas,
alegando que "`una imposición en la consciencia`" era la causa de su separación,
cuando en realidad su oposición había surgido del
poder de las tinieblas que obraba en ellos,
por lo que perdieron su luz y llevaron a muchos a su errores.

Este espíritu llevó gran aflicción y dolor sobre algunos,
al comienzo de sus obras en Westmoreland, Bristol, Wiltshire,
Gloucestershire y muchos otros lugares.
Grandes fueron los desórdenes que causó en Bristol y Wiltshire, debido a lo cual,
el Señor me movió (junto con otros fieles hermanos) a hacer
guerra contra ese espíritu en Su nombre y poder.
Así, con gran esfuerzo, lágrimas y angustia de espíritu, por varios años seguidos,
corrimos entre los vivos y los muertos en esos condados.
Puedo decir en la verdad,
que el Señor Dios me guió a viajar en Su nombre y terror por toda la tierra,
y estuvo conmigo en aquel día de profunda prueba.
De hecho,
tengo razones (con gran inclinación de espíritu) para magnificar Su glorioso nombre,
que me preservó fiel sobre todo desánimo.
Él fortaleció mi arco y llenó diariamente mi aljaba con flechas,
y trabajé como el que come el pan de adversidad y bebe agua de aflicción,
no ahorrando fuerza ni sustancia.

Recuerdo muy bien el día que recibí instrucción del Señor en una visión,
con respecto a ese pueblo, en la que me fue mostrada la obra, fin y caída de ellos.
Por tanto,
llegó a ser la gran preocupación de mi alma invitar a Amigos fieles de Wiltshire,
para tener una reunión con el propósito de esperar en el Señor,
en un profundo ejercicio del alma,
y clamar a Él que apareciera por el bien de Su nombre y Su pueblo.
Los Amigos respondieron de buena gana a mi deseo y acordamos
dicha reunión. Cuando estábamos esperando en el Señor,
este era el clamor de mi alma entre Amigos y hermanos: "`¡Oh, Señor,
¿qué harás por Tu gran nombre que es deshonrado?
¿Qué harás por Tu herencia?
Porque el enemigo y destructor desea esparcir y devorar Tus corderos,
y pisotear Tu viña!`" Así clamábamos delante del Señor con corazones postrados,
y Él oyó desde el cielo, Su santa morada, y Su poder irrumpió en una maravillosa forma,
ablandando a Su pueblo delante de Él. De hecho,
Su presencia y sabiduría celestial consoló y confirmó a Sus siervos,
y abrió los corazones de los Amigos para hablar bien del
nombre del Señor y de la grandeza de Su poder y aparición.

Posteriormente se concluyó que esta reunión debía continuar,
lo cual fue por muchos años el caso,
y en ella prevaleció nuestra lucha con el Señor. En verdad
Él nos acompañó con Su poder y presencia celestiales,
y desde ese momento en adelante,
vimos una demolición de ese espíritu divisor en todos sus emprendimientos,
y una poderosa confirmación de la herencia y pueblo del Señor.

El mismo poder de Dios derramó al Espíritu de oración sobre la ciudad de Bristol,
donde el Señor apareció muchas veces y frustró la intención de los predicadores
de la separación. La honda y piedra de David hirieron a su Goliat,
que se levantó contra los escuadrones de Israel,
y la gloria del Señor brilló sobre todos.
No puedo olvidar los muchos días,
noches y años de dolor por los que pasé en esa ciudad y condados aledaños,
donde trabajé en el poder del Altísimo para establecer
las iglesias de Cristo en paz y buen orden.

Después de este tiempo el enemigo llenó el corazón
del sacerdote de la parroquia donde yo vivía,
y él trabajó muchos meses para llevarme a prisión y quitarme mis bienes.^
footnote:[Por el bien de la consciencia,
los primeros cuáqueros no pagaron a la iglesia de Inglaterra los diezmos obligatorios,
y a menudo sufrieron largos encarcelamientos y la pérdida de propiedades como resultado.]
Él no escatimó esfuerzos hasta que me metió en la Prisión de la Flota en Londres,
donde me separaron de mi querida esposa y niños. Ahí estuve
confinado antes y durante el tiempo de la Gran Helada,^
footnote:[La Gran Helada de 1648-84 es uno de los cuatro o cinco
inviernos más fríos registrados en las Islas Británicas.
El río Támesis en Londres se congeló por completo por cerca de dos meses,
y se reportó que el hielo tenía unas 11 pulgadas de espesor.
La tierra estaba congelada hasta una profundidad de 27 pulgadas en Londres,
y más de 4 pies de Somersert.]
y después de aproximadamente un año, mi familia también se movió a Londres.
En este encarcelamiento sufrí mucho en cuerpo, espíritu y sustancia,
todo lo cual es conocido por el Señor que estaba conmigo.

Después de unos dos años, el sacerdote llegó a la prisión,
hizo que abrieran las puertas y me sacó; en algún momento después murió. Luego,
me establecí con mi familia cerca de Londres,
y por muchos años trabajé en el evangelio en esa ciudad.
Tenía una carga sobre mi corazón por los enfermos,
y por varios otros servicios para la iglesia y el pueblo de Dios,
y frecuentemente me reunía con algunos en el gobierno,
a favor del pueblo sufriente del Señor y del bien de mi país natal.

Los últimos tres años he visitado varias veces la ciudad de Bristol y condados aledaños,
y el Dios Todopoderoso ha forjado en mí dolores de parto para Su iglesia en esas visitas,
y me ha concedido fuerzas para realizar Su obra.
En efecto, Su gloria brilló sobre todos, Su río corrió, Su lluvia tardía descendió,
los manantiales de los profundidades se abrieron,
y los misterios del reino y viajes del Israel espiritual fueron abundantemente revelados.
Y ahora, el clamor de mi alma al Dios de mi vida es, que todos seamos un pueblo digno,
para alabanza y reconocimiento del nombre del Señor!

[.asterism]
'''

__Charles Marshall fue doctor en medicina por profesión,
pero la mayor parte de su vida adulta la dedicó al cuidado y aliento del rebaño de Cristo.
Tanto en la predicación como en la escritura,
siempre tuvo cuidado de mantenerse detrás de la guía y movimientos del Espíritu,
convencido de que la sabiduría y recursos naturales del
hombre no contribuyen en nada a la causa de Cristo,
o al incremento de Su reino.
Hablando de su ministerio,
William Penn (fundador de Pensilvania) en una ocasión escribió:
"`Él no era de palabras rebuscadas ni de elegante discurso,
ni se apoyaba en la memoria o en revelaciones anteriores,
sino alguien que esperaba sentir el poder vivo y celestial de Dios
para ser llevado adelante en sus ejercicios ministeriales,
por lo cual, como ministro del evangelio correcto,
a menudo refrescaba a la familia y herencia de Dios.`"__

__Aunque sufrió mucho por los perseguidores envidiosos de su época,
se decía que "`no se dejó mover por los abusos o heridas,
atribuyendo tales cosas a la naturaleza caída o a la ignorancia.`"
Continuó fiel hasta el final a través de muchas pruebas y encarcelamientos,
volviendo a muchos "`de las tinieblas a la luz,
y del poder de Satanás al poder de Dios.`"
En un corto testimonio de su vida, su esposa Hannah escribió:
"`A medida que se acercaban sus últimos momentos, cerró sus ojos con su propia mano,
y con alegría y compostura,
como alguien a quien se le había quitado el aguijón de la muerte,
encomendó su alma a Dios, el 15 del noveno mes de 1698, a los 62 años.`"__
