== El Diario y las Cartas de Catherine Payton

Como desde mi juventud los tratos del Todopoderoso para conmigo han sido singulares,
y dignos de ser conservados en la memoria con agradecimiento,
he puesto por escrito algunas notables circunstancias de mi vida,
que espero que despierten futura acción de gracias y vigilancia en mí. Y al considerar
cuán maravillosamente se ha manifestado el brazo divino en mi ayuda,
deseo que al escribir estas líneas me animen a confiar
firmemente en él y a perseverar en sumisión a este.
Siento también la necesidad de dejarles a los parientes que me sobrevivan,
algunos recuerdos de los varios ejercicios y peligros por los que he pasado,
y del misericordioso sostén y bondadosa preservación que me ha concedido el Señor.

Pero primero, me parece apropiado dejar un breve testimonio de mis padres,
quienes no sólo profesaron la Verdad, sino que también la poseyeron.
Mi padre, Henry Payton, de Dudley, Worcestershire, hijo de John y Catherine Payton,
respetables miembros de la Sociedad de Amigos,
fue llamado a la obra del ministerio como a los dieciocho años. Cuando era joven
viajó mucho al servicio de la Verdad por muchas partes de esta nación,
por Irlanda y Escocia, y por las colonias de América también;
y por el testimonio de Amigos,
tengo buenas razones para creer que sus servicios eran verdaderamente
aceptables y edificantes para las iglesias.
Su ministerio era vivo y claro,
y su mayor cuidado era no hablar más de lo que le
era revelado directamente por el Espíritu de la Verdad.
Su porte era serio, su conducta limpia y firme, y su caridad,
en proporción con sus circunstancias, era amplia.
Era un esposo afectuoso, un padre tierno y un amable maestro,
servicial entre sus vecinos, y amado y respetado por ellos.

Durante muchos años antes de su muerte,
estuvo incapacitado no sólo para el servicio público en el ministerio,
sino también para ocuparse en privado de las tareas
de vida en el mantenimiento de su familia,
al estar afligido de un trastorno de parálisis,
bajo el cual sus facultades fueron cediendo gradualmente.
Yo a menudo lo acompañaba en su larga debilidad, leyéndole y atendiéndolo,
y puedo testificar con respecto a él,
que retuvo el aroma de la vida divina hasta el final;
y que frecuentemente manifestaba una verdadera preocupación espiritual por sus hijos,
particularmente por mí,
su hija menor y tiernamente amada por él. Cuando su habla se entrecortaba,
de modo que no podía articular más que un poco, aun así a menudo decía:
"`El Señor los bendiga mis hijos.`"
Fue liberado de su aflicción a los setenta y cinco años,
y no dudo de que haya entrado a la bienaventuranza eterna.

Mi madre era hija de Henry y Elizabeth Fowler, de Evesham, Worcestershire.
Era una mujer religiosa, dotaba con un fuerte y firme entendimiento,
y con muchas virtudes notables,
por lo que estaba capacitada para el papel que tenía que desempeñar en la vida.
El Señor bendecía grandemente sus esfuerzos por sus hijos,
y no tengo dudas de que oía sus oraciones,
para '`que el rocío del cielo cayera sobre ellos.`' Ella
decía que no quería grandes riquezas para sus hijos,
sino que moraran en el temor de Dios.
Su firme y fuerte afecto marital se manifestó durante la larga
indisposición de mi padre mediante su tierna atención hacia él;
y después de su muerte, al mencionarlo frecuentemente en términos que evidenciaban,
que la unión de ellos estaba fundamentada en ese amor que la muerte no puede disolver.
Ella decía que cuando se casó con él,
estaba tan lejos de sentirse intimidada por la idea de que él la
iba a dejar sola por los viajes en la obra del ministerio,
que había hecho un pacto solemne con el Señor,
con la resolución de hacer todo lo posible para dejarlo en libertad para tales servicios.
Y cuando le plació a la divina Sabiduría privarla
de un esposo a quien ofrecer para Su servicio,
quería que al menos uno de sus vástagos fuera llamado al ministerio.
Eso se cumplió en mí, a quien ella amaba tiernamente;
pero creo que me dedicó tan libremente, como Ana había dedicado a Samuel,
y siempre estaba dispuesta a ponerme por delante en Su obra,
aunque siempre tenía cuidado de que yo no corriera por delante de mí Guía. Y aunque
después de que fui llamada al ministerio me tocaba alejarme de ella con alguna frecuencia,
nunca se quejó, sino que continuamente me animaba e impulsaba a la fidelidad;
de modo que entre las muchas misericordias que me concedió la bondadosa Providencia,
puedo contar con justicia no como la menor, haber tenido una madre como ella.

Ella era una madre afectuosa con todos sus hijos,
aunque muy perceptiva de sus faltas y rápida para reprenderlos,
no los consintió durante su infancia,
sino que los educó para que fueran industriosos y diligentes.
Era en verdad, un ejemplo de fortaleza, alegría, seriedad, trabajo duro, economía,
auto negación y rendición a la divina voluntad.
Era generosa con sus amigos;
su casa y su corazón siempre estaban abiertos para recibir a los mensajeros del Señor,
por lo que decía, que pensaba que una bendición había sido derramada sobre su familia.
Era caritativa con el pobre, y prefería ahorrar en otros gastos para tener más para dar.
Murió a los noventa y un años,
y conservó un grado considerable de solidez de juicio
hasta casi el final de su útil y cuidadosa vida.

Habiendo descendido de padres como estos,
puede suponerse que estuve en el camino de la instrucción religiosa desde mi infancia;
y de hecho, no puedo fechar el primer amanecer de la luz divina sobre mi alma.
Con humilde agradecimiento puedo decir,
que temprano en la mañana de mi vida conocí al Señor como un Dios cercano,
que me convencía del mal y levantaba deseos en mí,
en pos del conocimiento salvador de Su divino amor y poder.

Los Amigos que viajaban en el ministerio usualmente se hospedaban en la casa de mi padre.
Cuando era muy joven yo amaba la compañía de ellos,
y recuerdo con gratitud la tierna atención de ellos hacía mí. Aquí puedo observar,
que si nuestros jóvenes de hoy apreciaran la compañía y conversación
de aquellos cuyos '`pies son hermosos sobre los montes`'^
footnote:[Isaías 52:7; Romanos 10:15.]
de la salvación, y han tenido gran experiencia del amor de Dios,
podrían sacar mucho provecho de ello.
Pero ¡ay!, cuán frecuentemente algunos en nuestros días,
evitan la compañía de los ministros sólidos y con discernimiento,
dándoles escasa oportunidad de manifestarles el tierno
afecto con el que están revestidos sus espíritus,
probablemente temerosos de ser reprendidos por causa
de sus indulgentes libertades en la carne,
contrarias a la libertad pura de la Verdad.
Creen que tal reprensión es difícil de soportar,
aunque sea dada en ese amor que busca la verdadera felicidad de nuestras almas.

Yo podía leer bien desde muy pequeña, y al pasar mucho tiempo con mi afligido padre,
leía a menudo para él. Las experiencias y sufrimientos
de los mártires fieles y de nuestros primeros Amigos,
con los relatos de sus gloriosas salidas del tiempo,
con plena seguridad de su eterna bienaventuranza,
produjeron provechosas impresiones sobre mi mente.
En realidad, mi espíritu a menudo se enternecía por ello,
y mi amor por la virtud y la piedad era fortalecido,
de modo que puedo decir con certeza de esas personas santas, que '`aunque están muertos,
todavía hablan.`'^
footnote:[Hebreos 11:4]
¡Ojalá la juventud de la presente generación y de las venideras oiga sus voces,
y los mueva a evitar las sendas de la vanidad y a
seguir las pisadas de los compañeros de Cristo!

Sin embargo, a pesar de estos prometedores comienzos,
mientras crecía cedí a varias tentaciones,
de modo que las propensiones malignas de la naturaleza obtuvieron predominio,
y fui alejada de la sencillez de la Verdad.
Pero incluso en mi infancia experimenté varios conflictos,
y mis convicciones del mal eran fuertes;
así que mi corazón a veces estaba lleno de tristeza y mi almohada mojada con mis lágrimas,
aunque mi semblante y porte eran mayormente alegres.
Una vez, tras haber cedido a la tentación,
mi consciencia de culpa era tan grande que llegué a la conclusión
de que había pecado contra el Espíritu Santo,
y que por eso, en concordancia con el testimonio de Cristo, '`no sería perdonada,
ni en este siglo ni en el venidero.`'^
footnote:[Mateo 12:32]
Esto afectó mi tierna mente con tanta tristeza y angustia indecible,
que no pudo ocultarse completamente de la familia; aunque aún en mi infancia,
era capaz de guardar para mí misma la mayoría de mis ejercicios internos.
Creo que tenía unos ocho o nueve años cuando pasé por esa condición,
y como en mi niñez fui visitada varias veces por fiebres que me abatieron mucho,
me llevó a considerar si estaba preparada para el terrible cambio con el que era amenazada.
Una sensación de peso se apoderó de mi espíritu entonces,
de que mi alma no era suficientemente pura para ser admitida en el santo reino de Cristo.

A veces pactaba con el Señor que sería más prudente y vigilante en el futuro,
pero mi descuidada inclinación natural volvía a tener
predominio y le daba nueva ocasión al arrepentimiento.
Mi disposición natural era muy volátil y mi comprensión rápida;
y a medida que se abrían más mis facultades,
más me deleitaba en libros de naturaleza y tendencia muy
contrarias a los que habían atraído mi atención en mi infancia.
Yo tenía un pariente cercano, quien,
a pesar de que había sido favorecido con una visitación divina en su juventud,
había despreciado las misericordias de su alma, y perseguía vanidades mentirosas.
Él tenía una casa en el mismo pueblo, y a través de él, mis hermanas y yo,
tuvimos oportunidad de obtener obras de teatro y de romances, que yo leía con avidez.
Pasé suficiente tiempo en su casa como para ser introducida en
entretenimientos muy inconsistentes con la sencillez de la Verdad,
y con mis anteriores impresiones religiosas.
De hecho, en ese entonces mi estado era en verdad muy peligroso,
y si no hubiera sido por la intervención de la divina Providencia,
habría seguido un rumbo que habría terminado de manera deplorable.

También leía historia, era aficionada a la poesía y tenía gusto por la filosofía; así,
pues, estaba en camino de "`embellecer mi entendimiento,`" como dice el refrán,
y de ser más consumado en mi conducta;
lo cual me habría inclinado a alimentar la naturaleza vana y orgullosa,
a hacerme más agradable para los que vivían en ella, y hacerme distinguida en el mundo.
Pero el Señor, en Su sabiduría,
tenía el designio de llevarme a la vista pública en una
forma directamente opuesta a la de la sabiduría,
placer u honor mundanos.
Y cuando le plació a Él abrir más plenamente mi entendimiento con
respecto a Su grande y gloriosa obra de renovación del espíritu,
vi que debía desistir de esas publicaciones y estudios,
y dedicarme a la única cosa necesaria, a saber,
trabajar la salvación de mi alma inmortal; y en verdad,
considero una gran misericordia que yo haya atendido prontamente esa indicación.

Por muy lícito que sea (en las estaciones apropiadas) mirar las obras de la naturaleza,
y familiarizarse con la historia de tiempos pasados o presentes,
mi atención estaba ahora atraída poderosamente por temas más elevados;
si yo hubiera perseguido esas cosas más bajas,
me habría convertido en una '`vasija echada a perder en la rueda.`'^
footnote:[Jeremías 18:4]
Lamentablemente, este es el caso de muchos que han sido divinamente visitados,
pero que no han atendido profunda y firmemente las instrucciones de la sabiduría pura,
sino que buscan ser sabios y eruditos en asuntos
que se relacionan meramente con este mundo presente,
y no han avanzado en la sencillez del conocimiento divino.
Y aunque ha quedado claro que la mano del Señor se ha movido misericordiosamente
sobre algunos de estos para formarlos para Su servicio,
aun así no han crecido hasta esa medida de utilidad
en la iglesia de Cristo que podrían haber alcanzado,
si se hubieran sometido pasivamente a los giros de Su mano preparadora.
Si los hijos y las hijas de nuestra Sociedad religiosa,
que han sido favorecidos con un buen entendimiento natural,
se vistieran con la sabiduría celestial,
se convertirían y parecerían verdaderamente grandes en la
digna y humilde sencillez del servicio al Rey de reyes.
Los conocimientos y las adquisiciones humanas hinchan
con demasiada frecuencia las mentes de los jóvenes;
y de hecho, algunos que son de edad más avanzada también se enorgullecen en esas cosas,
cuando, como ejemplos para la generación naciente, deberían revestirse de humildad.

Se observó de un verdaderamente honorable miembro de nuestra favorecida Sociedad,
que "`él era un maestro en las cosas espirituales y naturales,
y todo por obra del Todopoderoso.`"^
footnote:[Relato de William Penn sobre George Fox.]
He leído muy poco de filosofía natural,
y no estoy en posición de presumir de mi conocimiento adquirido de las cosas humanas,
naturales o divinas; pero puedo decir, que a menudo he admirado cómo,
por un destello de luz celestial, se abre el entendimiento a las cosas naturales,
para de un vistazo contemplar la economía general del divino Formador de todas las cosas,
tal como se muestra en la creación externa.
Esto produce adoración a Él, bajo el humilde sentido de Su poder,
misericordia y sabiduría, junto con gran admiración por Sus obras,
al ver que son en verdad maravillosas, y en toda su extensión incomprensibles.
Por tanto,
¡qué las facultades de Sus hijos adoptivos no se
ocupen indebidamente explorando estas obras externas,
en alguna forma que les impida el avance en sus varias
jornadas en la iglesia militante del Señor;
porque cuando sus almas estén felizmente fijadas en el Triunfante,
sabrán suficiente como para inspirar para siempre el cántico angelical:
"`Grandes y maravillosas son tus obras.
Señor Dios Todopoderoso, las has hecho todas con sabiduría!`"

Regreso a mi educación a partir de estas observaciones, la que, mientras estuve en casa,
no fue completamente descuidada en lo que se refiere al aprendizaje útil y necesario.
Sin embargo,
como las circunstancias de aflicción de nuestra familia me habían
hecho permanecer muy cerca hasta que alcancé los dieciséis,
mi madre decidió entonces enviarme a Londres,
y ponerme por un año bajo el cuidado de Rachel Trafford.
Ella y su hermana tenían un respetado internado,
y mi madre no tenía dudas de la amable atención de ellas hacia mí,
porque cuando Rachel era joven había pasado un tiempo
considerable en la familia de mi padre.
Ella era afectivamente amable conmigo, y como ministra e instructora,
creo que su mente se ejercitaba con frecuencia en
pro del mejoramiento espiritual de sus estudiantes,
lo que a veces se manifestaba mediante súplicas verbales por ellos,
así como por medio de consejos y apropiadas reprensiones.

Yo mejoré mucho durante el tiempo que estuve en el internado,
y mis compañeras se portaban bien conmigo; pero al ser más madura,
alta y proporcionalmente grande para mi edad, me veía demasiado mujer para un internado.
Sin embargo, algunas de mis compañeras eran mayores que yo,
lo que creo que aumentaba la preocupación de mi maestra con respecto a nuestra preservación,
pues, para usar su propia expresión,
éramos más como una '`escuela de mujeres.`' Yo conocía muy
de cerca a la sobrina de mi instructora (quien se desempeñaba
como maestra) y a una de las estudiantes--una joven sensible,
agradable y bien portada, pero no de nuestra Sociedad,
que había sido admitida en la escuela para prepararse en costura y para ser instructora.
Como ninguna de ellas estaba bajo la influencia de la verdadera religión,
no me beneficié en el aspecto más esencial de mi comunión con ellas.
Pero después de haber estado unos pocos meses en la escuela,
fui favorecida con una renovada visita del amor divino,
y empecé a sentirme intranquila con mi situación. El hogar se hizo deseable,
aunque sabía que era una casa de aflicción;
y cuando le di a entender esto a mi querida madre, mi hermano James llegó y me recogió,
más pronto de lo que mi madre había planeado cuando la dejé.

Hasta ahora he recordado los tratos del Todopoderoso con mi alma,
manifestados principalmente en tierna misericordia;
pero había llegado el día en que Sus justos juicios se manifestarían
contra todo lo que era altivo y estaba levantado en mí,
y era opuesto a Su Espíritu puro.
En ese día, mis desvíos de Él (el Pastor de Israel) fueron traídos a mi memoria,
y mis pecados puestos en orden delante de mí. En realidad,
esto provocó gran humillación y quebrantamiento de corazón,
junto con fuertes clamores a Él,
pidiéndole que misericordiosamente pasara por alto mis transgresiones y me recibiera
en pacto con Él. Aunque esa dispensación no era agradable para la naturaleza degenerada,
la cual (de la misma manera después de que Adán había
transgredido) busca evadir la condenación,
aun así, debido a la gloria que yo sabía que había más allá de ella,
y al divino amor que había visto en ella, dije en lo secreto de mi alma:
"`Es bueno para mí estar bajo esta dispensación.`" Fui llevada
a soportar pacientemente los juicios del Señor por el pecado,
a fin de que pudiera experimentar la remisión de estos,
a través del bautismo de arrepentimiento y la vida
o Espíritu santificador de Su Hijo Jesucristo.
Y al fin (en el tiempo señalado por la sabiduría infinita) experimenté esa misericordia;
de modo que mis pasadas transgresiones fueron borradas del '`libro de memoria,`'
a condición de mi futura y firme perseverancia en el temor de Dios.
Y en el discernible triunfo de la divina misericordia sobre el juicio,
mi alma se regocijó con humilde agradecimiento.

Sin embargo, así como los hijos de Israel que fueron liberados de Egipto,
y luego viajaron a través del desierto,
encontraron nuevas y diversas pruebas a las que tenían que enfrentarse,
de manera tal que pensaron que sus sufrimientos se acrecentaban en lugar de disminuir,
y frecuentemente temían perecer en esa tierra desértica; así encontré también yo,
que liberada del peso opresivo de las transgresiones pasadas,
tenía que viajar para alcanzar la herencia prometida a los santos,
que es un estado real de establecimiento en justicia.

Pronto me encontré en muchos profundos bautismos y ejercicios de fe y paciencia.
Fui llevada a mirar dentro de mi propio corazón, el cual,
debido a la irregularidad de sus pasiones e inclinaciones,
bien podría haber sido comparado con un desierto sin cultivar,
a través del cual vi que tenía que viajar,
y en el que debía recibir la ley para el orden de mi conducta externa.
¡Oh, las temporadas de hambre y sed, las inquietudes y perplejidades, los "`truenos,
relámpagos y tempestades`" que tuve que atravesar aquel día,
todo lo cual parecía amenazarme con destrucción! Esto debe ser
recordado eternamente con agradecimiento a la Mano divina,
que me preservó de estar tan abatida por ello,
como para mirar atrás con deseos de regresar a ese
país o condición del que dichosamente había escapado.
Aquí el adversario se transformó como un ángel de luz,
y bajo la engañosa apariencia de justicia,
presentó el camino tan estrecho que era imposible
caminar en él y seguir actuando como un ser racional.
De este modo intentó desanimarme o impedir que alcanzara la libertad del verdadero evangelio,
en el uso de las cosas creadas y en el curso de mi conducta.

De hecho,
en esa época de profunda angustia '`la tierra y los cielos fueron
sacudidos.`' Algunos de los principios religiosos que había recibido
por medio de la educación fueron puestos en duda,
y me quedé sin un fundamento sólido con respecto a ellos;
no podía alcanzar algún grado de certeza por el testimonio de otros,
ni por los escritos de los que los habían reivindicado para el mundo;
siendo obligada a recibir mi convencimiento de la verdad,
a partir del profundo y seguro terreno de la revelación divina.

He visto que todo eso fue necesario para prepararme
para el servicio que había sido designado para mí,
para que el fundamento de mi fe estuviera establecido en la certeza,
y para que pudiera testificar con valentía que había
__experimentado__ lo que afirmaba que era la verdad;
y además, para estar adecuadamente calificada para simpatizar con, y ministrar a,
los que estaban en un estado similar.
Pronto vi para qué oficio estaba designada en la iglesia de Cristo.
Mi alma recibió esa manifestación de la voluntad divina con un buen grado de rendición;
sin embargo, mientras llegaba el tiempo del Señor para ponerme a Su servicio,
me asaltaban con frecuencia temores de que fuera requerido de mí,
en cierto tiempo o en cierta forma,
que les resultara doblemente difícil a la carne y sangre.
El adversario también estaba ocupado con sus presentaciones,
intentando con ellas desanimar mi mente de seguir su correcto deber,
o apurarme hacia lo que tenía una falsa apariencia de este,
a fin de llevarme a la confusión.

Sin embargo,
en todas esas "`voces del extraño,`" hacía falta esa certeza que yo había
concluido debía acompañar a la manifestación de la voluntad divina,
y a la que yo felizmente estaba siendo llevada a buscar.
Al fin fui fortalecida para pactar con el Todopoderoso,
que cuando la evidencia fuera clara y fuerte, me sometería a ella.

Aquí no está de más observar,
que puede que algunas mentes sean más propensas que otras a luchar con estas cosas.
Los que tienen una imaginación fuerte y rápida,
y cuyos corazones han sido profundamente afectados
por la excesiva pecaminosidad del pecado,
y por el amor de Dios a la humanidad, y desean fuertemente,
que lo uno llegue a su fin y lo otro abunde en la tierra--para
estos es difícil mantenerse en todo momento,
especialmente cuando son jóvenes en experiencia religiosa, en la tranquila morada,
el único lugar donde la voz del verdadero Pastor es oída y distinguida de la del extraño.
Pero a medida que la voluntad se va rindiendo gradualmente a la voluntad de Dios,
y el funcionamiento natural de la imaginación se va silenciando,
y el alma llega a adorar más constantemente en el templo del Señor,
el adversario es atado en estas falsas apariciones; o si se le permite presentarlas,
se adquiere fortaleza para permanecer en quietud y probar los espíritus.
He visto en la luz de la Verdad,
que esto es absolutamente necesario antes de que avancemos en el
servicio del Señor. La falta de esto ha producido mucha confusión,
y ha sido causa de gran reproche a nuestra alta y santa profesión,
para los que buscan una oportunidad para echar por
tierra la creencia en la revelación divina.

Ahora regreso: Habiendo llegado al mencionado estado de rendición,
esperé quietamente en un estado de ferviente oración,
para discernir los movimientos de la Mano divina y no moverme antes del tiempo apropiado.
Tengo buenas razones para creer que esto fue oído y respondido;
y por el movimiento de la vida divina,
fui constreñida a suplicar al Todopoderoso en nuestra pequeña reunión en Dudley,
el día diez del mes Dos de 1748, habiendo entrado entonces a mis veintidós años.

Ojalá todos los hijos del Señor,
a quienes Él designa para el importante y solemne servicio del ministerio,
esperaran humilde y pacientemente hasta saber cuándo moverse; porque por descuidar eso,
muchos han entrado al servicio antes de haber pasado
completamente la dispensación de preparación;
y si en algún momento llegaran a ser fuertes en Su servicio, sería porque al principio,
y por mucho tiempo, tuvieron que seguir en estado de debilidad.
¡Qué nadie desprecie "`el día de las pequeñeces`"!^
footnote:[Zacarías 4:10]
Unas pocas palabras pronunciadas bajo la dirección divina,
con frecuencia son de bendición para aquellos a quienes
el Amo de las solemnes asambleas las dirige.

Seguí ministrando según le placía al Señor darme capacidad, en gran quebranto de corazón,
y por un tiempo no hablé más que unas pocas palabras a la vez;
porque un gran temor se apoderaba de mi espíritu,
no fuera a ministrar en la sabiduría de la criatura,
que siempre da muerte y engendra su propia imagen.
Con la consciencia de este peligro, mis clamores al Todopoderoso eran fuertes,
rogándole que lo que yo les fuera a ofrecer a las personas no estuviera mezclado,
aunque pareciera simple o despreciable a los ojos del sabio y erudito del mundo.
Y mientras seguía avanzando en el ministerio con temor y temblor, el Señor estaba conmigo.
Con el tiempo amplió mi entendimiento e incrementó
mi servicio en la revelación de la Verdad,
ante lo cual Su pueblo se regocijaba, y yo, en obediencia a Sus requerimientos,
sentía una dulce paz.

Sin embargo, mi espíritu con frecuencia se sentía apesadumbrado,
al ser humillado con muchos y profundos ejercicios que yo
encontraba provechosos para establecerlo en la justicia,
aunque fueran dolorosos para la naturaleza.
Dejo como una observación, que rara vez, si es que alguna,
he visto a alguien continuar y llegar a algún grado considerable de utilidad en la iglesia,
cuyo fundamento no haya sido profundamente cimentado en aflicciones y pruebas,
por medio de las cuales son crucificados con Cristo, y por tanto,
levantados con Él para gloria y honor, tanto en el presente como el estado futuro.
Pero en todas mis aflicciones y profundos bautismos, el Pastor de Israel estaba conmigo,
y preservaba y sostenía mi espíritu para honor de Su propio nombre,
el único a quien podía atribuirle la alabanza.
Porque en aquellos días y años de tribulación designados,
yo tenía muy poca ayuda del hombre,
pues me tocó vivir en un lugar donde no había nadie cerca
que fuera capaz de darme mucha ayuda o consejo sabio,
por no haber caminado en los mismos pasos.
A veces pensaba que mi caso estaba oculto a algunos de los
siervos del Señor que se sentían movidos a visitar Su herencia,
o bien,
que en parte se les impedía ministrar a mi condición;
y mi lengua estaba muy sellada en silencio, pues mis ejercicios eran indecibles.

He considerado que todo eso fue de excelente utilidad,
pues lo contrario me podría haber llevado a depender de
los siervos del Señor (lo que siempre trae debilidad),
o haber producido confusión,
al compartir mi caso con los que no estaban suficientemente capacitados para ministrarlo,
pero que aun así, habrían dado consejo al respecto.
He visto que es provechoso y necesario para los que
están en un estado de infancia en la religión,
aguantar sus propios ejercicios,
apoyándose simplemente en el único Brazo que puede llevarlos a través de ellos; y,
hasta que la mente haya adquirido un profundo discernimiento
para distinguir claramente quien está del lado del Señor,
ser muy cautelosos de a quienes comunican sus pruebas,
no vayan a ser heridos al descubrir que aquellos que han escogido como sus amigos,
resulten ser enemigos de la cruz de Cristo.
Sin embargo, cuando en los tiempos de gran dificultad,
el Señor dirija a buscar consejo de Sus experimentados siervos,
esto será sin ninguna duda provechoso.
En efecto, un amigo firme y comprensivo es una gran fuerza y bendición,
cuando concedido en la sabiduría divina.

[.asterism]
'''

+++[+++__Nota del editor:__ En este punto de su diario,
Catherine Payton comenzó un relato detallado de sus viajes en la obra del ministerio,
cuyos servicios la mantuvieron ocupada casi continuamente
los siguientes veinte años de su vida.
Aunque hay mucha información biográfica interesante,
y se encuentran muchas anécdotas instructivas en los relatos de estos viajes, se pensó,
que para el propósito de esta breve publicación,
una muestra de sus cartas podría presentarle al lector una visión
más clara de la vida y valor de esta extraordinaria mujer de Dios.

La primera carta fue escrita a la joven Rebecca Jones,^
footnote:[Rebecca Jones llegó a ser una estimada ministra de la Sociedad de Amigos,
considerada por todos los que la conocieron como una discípula mansa,
dotada predicadora y amorosa "`madre en Israel,`"
y un brillante ejemplo de toda virtud Cristiana.
Su diario y sus cartas están disponibles en inglés en www.friendslibrary.com.]
durante el largo viaje ministerial de Catherine Payton
por las colonias en América entre 1753 y 1756.
Se incluye un extracto del diario de Rebecca Jones,
para darle contexto a la carta que sigue.]

[.offset]
Rebecca Jones escribe:

[quote]
____
En el año 1754, a mis dieciséis años,
vino de la vieja Inglaterra en visita religiosa a las iglesias de Cristo en América,
Catherine Payton, en compañía de Mary Peisley de Irlanda.
Estuve con Catherine Payton en varias reuniones en esta ciudad,
y escuché varios de los testimonios que ella dio, con los que me sentí muy complacida;
pero como muchos otros sólo __escuché__ y no busqué aprender
el camino de salvación con sinceridad.
¡Pero bendito y alabado sea para siempre el gran
Ministro de todos los ministros y Obispo de las almas,
quien en Su abundante compasión por una pobre criatura
en el camino mismo que conduce a las cámaras de muerte,
le plació misericordiosamente, a través de esta sierva,
poner mi estado y condición delante de mí! En efecto,
Él le permitió en una de nuestras reuniones vespertinas del Primer-día,
hablar tan pertinentemente a mi situación,
mostrando las consecuencias de jugar con la convicción Divina,
y proclamando el amor de Dios a través de Cristo a todos los pecadores arrepentidos,
que clamé en la amargura de mi corazón: "`¡Señor, qué quieres que haga para ser salva!`"
Mi corazón fue alcanzado tan eficazmente,
que estuve dispuesta a renunciar a todo lo de aquí, con tal de obtener la verdadera paz;
sí, mi vida natural no habría sido una ofrenda demasiado grande,
si hubiera sido requerida para heredar eterna salvación.

¡Oh, los muchos días de tristeza y noches de profunda angustia por los que pasé entonces!
Cuántas veces clamé: "`¡Señor, sálvame o perezco!`"
Casi llegué a la desesperación por encontrar misericordia,
porque el pecado no sólo '`parecía sobremanera pecaminoso,`'^
footnote:[Romanos 7:13]
sino que el enemigo de mi alma me persuadía de que
mis pecados eran de un color tan oscuro,
y se habían repetido tan a menudo, que yo había descuidado el día de mi visitación;
y que ahora, al igual que Esaú, no obtendría la bendición aunque la buscara con lágrimas.

Pero sean magnificadas para siempre la misericordia y la bondad del Señor mi Dios,
el Padre eterno; porque Él no me dejó ahí,
aunque estaba en la situación descrita por el profeta Ezequiel: Estaba muy contaminada,
y me revolcaba en la inmundicia de la carne,
sin ninguna ayuda de mis conocidos terrenales, y era una extraña para la familia de Dios.
En realidad, no había sido '`lavada con agua, ni frotada con sal,
sino arrojada sobre la faz del campo, desprovista de cercado;
ningún ojo se compadecía de mí, para hacer algo de esto por mí.`'^
footnote:[Ezequiel 16:3-5]
Pero cuando el Ayudador seguro pasó a mi lado, me vio en mi deplorable condición,
echó Su manto de amor divino sobre mí, y con poderosa voz dijo: "`¡VIVE--sí, me dijo:
VIVE!`"^
footnote:[Ezequiel 16:6]

La renovación del favor divino me animó a entrar de nuevo
en solemne pacto con ese misericordioso Ser,
contra el que yo me había rebelado tanto, y a quien yo había ofendido tan justamente;
y las respiraciones de mi alma eran fervientes,
anhelando ser capaz de ceñirme a los términos del pacto hecho en el tiempo de mi humillación.

Mi amor por este instrumento en la mano del Señor +++[+++Catherine Payton]
era muy grande; y en cierta ocasión, estando muy reducida en mi mente,
bajo la consideración de mis muchas y profundas transgresiones,
cogí mi pluma y le abrí un poco de mi condición, aunque tuve miedo de poner mi nombre.
Esperé una oportunidad,
y entonces se la deslicé en su mano justo cuando entraba a una reunión,
y dos días después recibí (de manos de uno de sus amigos) la siguiente respuesta,
la cual,
como tuvo el bendito efecto de animar mi mente a confiar
reverentemente en la infinita misericordia del Señor,
la transcribo aquí en su totalidad.
Al recibir y leer esta carta, mi corazón se derritió en gran ternura delante del Señor,
y mi mente se animó a confiar en Su ilimitada misericordia, así extendida a mí,
una pobre e indigna criatura.
Tal vez su lectura reviva la esperanza de alguna alma afligida.
____

[.embedded-content-document.letter]
--

[.letter-heading]
Catherine Payton a Rebecca Jones

[.signed-section-context-open]
Filadelfia, 4 del mes Uno, 1755.

[.salutation]
Querida niña,

He leído cuidadosamente tu carta, y por la ternura de espíritu que siento hacia ti,
concibo mucha esperanza de que te irá bien,
si te mantienes cerca de ese Poder que te ha visitado.
El cual, así como ya ha aparecido como una luz para convencerte de pecado,
si Se lo permites,
también lo destruirá en tu corazón. Esta dispensación que ha comenzado,
es la razón de esa angustia de espíritu que sientes,
la que disminuirá gradualmente en la medida que seas ayudada a vencer.

No te desanimes demasiado, ni por lo que has cometido contra el Señor,
ni por lo que tengas que sufrir por Él;
porque aunque tus pecados hayan sido como la grana,
Él puede y quiere hacer tu corazón como la nieve (tras tu
sincero arrepentimiento y humilde caminar en Su temor),
y darte fuerza para que hagas cualquier cosa que Él te pida.

Si estás dispuesta y eres obediente en el futuro,
comerás del bien de la tierra en el tiempo del Señor, y tal como ya has sido instruida,
que "`sólo recibirás consolación en la medida que seas apta para ella,`" entonces,
espera pacientemente y deja que la administración de condenación sea perfeccionada--así
la administración de Luz y Paz será más clara y fuerte;
la que de seguro vendrá sobre ti, si permaneces fiel a ese Poder que te ha visitado.

Deseas que yo te explique algunas porciones de las Escrituras que mencioné en la reunión,
lo que estoy dispuesta a hacer tanto como la mención de ellas se relacione con tu estado--pues
creo que fueron para despertar vigilancia y cuidado sobre tu conducta,
a fin de que tu alma produzca los frutos de pureza y amor de Dios,
que serán manifestados únicamente mediante tu obediencia; y también,
para que no descanses en nada que no sea el conocimiento de Su poder,
revelado en tu corazón como refinador y maestro;
ni coloques tu felicidad en algo menos que la experiencia de Su salvación.

Salgo mañana del pueblo, y al no saber tu nombre por tu carta,
no sé cómo llegar a hablar contigo.
Por tanto, le he encomendado el cuidado de esta carta a Anthony Benezet, quien, creo,
que hará todo lo posible por hacértela llegar.

Adiós y que el Señor continúe bendiciéndote.
Termino, con mucha prisa, tu compasiva amiga,

[.signed-section-signature]
Catherine Payton.

[.postscript]
====

P+++.+++ D.-- Prefiero que guardes esto para ti;
y asegúrate de ser cuidadosa de la manera que cuentas tu
condición a quienes no tienen entendimiento de ella.

====

--

[.asterism]
'''

+++[+++La siguiente carta fue escrita por Catherine Payton
y dirigida a un grupo de personas en Cardiff,
Gales,
quienes habían renunciado en parte a su anterior profesión
religiosa y se sentaban juntas a esperar en el Señor,
pero que todavía se encontraban en un estado inestable.]

[.embedded-content-document.letter]
--

[.blurb]
=== A los pocos que han sido convencidos de la rectitud de esperar en el Señor en silencio, y acostumbran reunirse para ese buen fin en Cardiff.

[.salutation]
Amigos,

Me siento movida a saludarlos tanto en el amor del
Padre celestial como en mi sentido del deber,
deseando que permanezcan firmes en la Verdad inmutable,
para que cimentados en la correcta fe, no sean llevados por cualquier viento de doctrina,
sino que en la estabilidad de la mente,
puedan distinguir entre lo que procede de la Fuente pura de sabiduría,
y lo que está mezclado con la política humana y las tradiciones de los hombres,
que tienden a alejar la mente de la sencillez de la adoración
evangélica y a fijarla en actuaciones externas,
entreteniéndola con '`ejercicios corporales que aprovechan poco.`'^
footnote:[1 Timoteo 4:8]

Por esos medios,
muchas veces esa tierna sensación espiritual con la que el alma
(en la infancia de su experiencia religiosa) es bendecida,
se pierde en alguna medida, y el entendimiento se nubla.
La mente entonces, o se sumerge en un laberinto de pensamientos,
o se exalta por encima de ese manso estado de infancia,
en el que los humildes seguidores del Cordero se deleitan en permanecer,
porque en él pueden distinguir Su voz de la del extraño,
y recibir fuerza para seguirlo a través de varias
dispensaciones de prueba que a Él le complace asignarles.

Muchas veces, desde que vi sus rostros, he mirado hacia ustedes,
y desearía poder decir que los he visto a todos guardar
sus moradas en el Señor. Pero desgraciadamente,
en lugar de eso, ¿no ha habido un desvío,
y se ha edificado de nuevo eso de lo que ustedes
habían dado algunos buenos pasos hacia la abolición?,
de lo cual, dice el apóstol, que quienquiera que lo haga se convierte en transgresor.^
footnote:[Gálatas 2:18]
¿Acaso no puedo preguntar: '`¿Hasta cuándo claudicaréis entre dos pensamientos?^
footnote:[1 Reyes 18:21]
Creo que esta es una de las causas de la debilidad de ustedes, y me temo,
que si persisten en ello, resultará en la destrucción de ustedes.

Creo que fue el misericordioso designio del Todopoderoso,
redimirlos de la dependencia del hombre y llevarlos
a esperar las enseñanzas directas de Su Espíritu,
y a confiar en Su poder a partir de una consciencia viva de su suficiencia.
Si ustedes lo hubieran seguido con sencillez,
Su Omnipotente brazo se habría exaltado derribando
a sus enemigos y ensanchando sus entendimientos,
de modo que no sólo hubieran visto que existe la luz,
sino que la milagrosa cura de la ceguera de ustedes habría sido perfeccionada,
y en la luz habrían discernido claramente los objetos.
Allí habrían crecido en la experiencia cristiana, y habiendo recibido la unción santa,
y permanecido bajo ella,
habrían encontrado que no necesitaban que un hombre les enseñase,
porque dicha unción era suficiente para instruirlos en todas las cosas.
Allí habrían podido distinguir entre las palabras acompañadas
con el poder de Dios y las que no lo estaban,
por los diferentes efectos que cada una tenía en
el alma--que unas tendían a vivificar para Dios,
y las otras a traer muerte sobre la vida espiritual.

Según la naturaleza de las cosas,
un ministerio que no proviene de la vida del evangelio
sólo puede engendrar su propia semejanza.
Puede llenar la cabeza de conceptos, pero no puede llenar el alma de gracia.
Y como el negocio del enemigo es engañar el juicio con falsas apariencias,
se esforzará (hinchando la mente con ideas vanas) por hacer
una semejanza de los efectos o frutos de la Verdad.
Así, pues, cuando la cabeza esté atestada de conocimiento,
y el cristianismo sea parcialmente entendido en teoría por obra de la imaginación,
entonces, la pobre criatura engañada presumirá de visiones y placeres,
y elevándose sobre las alas del engaño, abundará en expresiones apasionadas.
Pero, aunque hable de Dios y de Cristo de la mañana a la noche,
no está más que '`calentándose en el fuego que ella misma ha encendido,`'^
footnote:[Isaías 50:11]
al estar desprovista de la verdadera eficacia de la gracia.

La Verdad tiene la tendencia natural de humillar todas las facultades del alma,
para hacerla '`alegrarse con temblor`'^
footnote:[Salmo 2:11]
y revestirla de mansedumbre,
rendición y contrición. En este estado busca reposar en el pecho del Amado,
o inclinarse delante de Su trono en silenciosa adoración,
o derramarse con ternura en oración mental o alabanzas;
y si se dirige a Él verbalmente en la congregación de Su pueblo,
es con la más grande reverencia y humildad,
sabiendo que es una presunción hacerlo separada del movimiento de Su Espíritu.
Y si el alma se ve largamente privada de Su presencia, Lo busca con dolor;
pero en la medida que avanza en experiencia,
es cautelosa al descubrir su condición (como en la noche) a los varios y supuestos vigilantes;
no sea que al develar sus conflictos a las mentes de los hombres no regenerados,
ellos (ya sea por falta de caridad o de habilidad) hieran en lugar de sanar;
o dirijan al alma a otros objetivos, en lugar de informarle dónde encontrar Al que busca.

Espero que estas observaciones que vienen a mi mente las reciban en el amor del evangelio,
en el que creo que son comunicadas.
Concluyo ahora,
con deseos de que si ha aparecido alguna inconsistencia en la conducta de ustedes,
se mantengan más cerca del Guía divino en el futuro,
y de esa manera sean revestidos con sabiduría y fuerza,
y experimenten la salvación y paz que las acompañan.

[.signed-section-closing]
Su sincera amiga,

[.signed-section-signature]
Catherine Payton.

[.signed-section-context-close]
Dudley, 16 del mes Tres, llamado Marzo, 1752.

--

[.asterism]
'''

+++[+++La siguiente epístola general, escrita por Catherine Payton en 1758,
fue dirigida a los Amigos en Irlanda,
cuando muchos en ese país habían caído en un triste estado de degeneración de la vida,
pureza y poder del Espíritu que tanto había caracterizado
a la temprana Sociedad de Amigos;
y en su lugar, se habían establecido en un formalismo sin vida, por un lado,
y en una libertad carnal, por otro.]

[.embedded-content-document.letter]
--

[.salutation]
Queridos hermanos,

Porque con un sentimiento de compasión evangélica puedo llamarlos así--¿han
considerado seriamente alguna vez que "`no tenemos aquí ciudad permanente`"?^
footnote:[Hebreos 13:14]
¿Han entendido, que dado que sus almas son inmortales,
el asunto _principal_ de sus vidas debería ser buscarles morada adecuada a su ser y naturaleza,
en la que puedan tener una residencia feliz para siempre, que sólo se halla en Dios,
quien es la fuente y la provisión de Su pueblo?

Ahora, para que sus almas se centren al final en Dios,
es necesario que se conviertan en moradas para Él,
a través de la operación santificadora del Espíritu de Su Hijo,
la única que puede hacernos (a quienes hemos sido contaminados con el pecado,
y por tanto, estamos incapacitados para residir con Él), objetos adecuados de Su favor.
Permítanme, por tanto, preguntarles,
y ojalá se pregunten a sí mismos--¿qué han conocido
verdaderamente de esta obra en sus experiencias?
¿Ha hecho el Espíritu de juicio y de fuego Su obra en sus corazones?
¿Han pasado por la primera parte de la obra de santificación--es decir,
la administración de condenación por el pecado?
¿Han sido doblegados bajo el testimonio del Testigo justo de Dios en sus consciencias?
¿O más bien han suprimido y despreciado a este mensajero celestial,
no permitiéndole declarar la Verdad, o tal vez,
no creyendo la doctrina que les predicaba porque no aprobaba algunos de sus actos?
En realidad,
¿no han llegado algunos al punto de pisotear a "`los dos testigos de Dios`"--la evidencia
interna de Su Espíritu y el testimonio externo de Sus siervos--y en este momento,
quizás, se están regocijando en su victoria y proclamándose "`paz, paz,`" cuando, ¡ay!,
el día de temor, asombro e indecible angustia los espera y está cerca?
Porque, ciertamente,
las cortinas de mortalidad pronto se descorrerán y todos deberán comparecer ante el Juez,
tremendo en majestad,
y ver a este Testigo justo (que durante sus vidas mataron) levantarse
en poder para testificar contra ellos por su rebelión,
y luego atestiguar la justicia de la exclusión de ellos de los reinos de luz y bendición.

No sé qué efecto pueda tener sobre la mente de los
impíos y de los que se olvidan de Dios,
esta débil descripción del día del juicio;
pero al sentir mi corazón impresionado con un terrible sentido de su certeza,
me siento provocada a intentar arrancar
a tantos como sea posible de tales consecuencias eternas,
persuadiéndolos de que se inclinen en el día de la
misericordiosa visita de Dios a sus almas,
y a que '`honren al Hijo, para que no se enoje, y perezcan en el camino,
cuando se encienda un poco su furor.`'^
footnote:[Salmo 2 :12]

No imaginen vana y orgullosamente que son capaces de soportar la fuerza del Omnipotente.
Él es y será el Rey, sea que estén dispuestos a concederle el derecho de soberanía o no;
y Sus sagradas leyes de inmutable verdad se manifiestan tanto en el castigo
de los transgresores como en la recompensa de los que hacen bien.
¡Oh, si fuera posible trasmitirles el sentido de esa dulce paz,
gloria y gozo que son y serán revelados a los que aman y sirven a Dios,
serían convencidos de que ningún castigo sería demasiado grande para los que
(por una conducta contraria) desprecian y desechan tan grande salvación y felicidad!
Pero como el ojo no puede ver,
ni el corazón concebir la extraordinaria gracia de Dios en Cristo Jesús,
excepto los que felizmente han experimentado sus operaciones santificadoras,
no puedo dejar de invitarlos a '`venir, probar y ver que el Señor es bueno,
y que Su misericordia permanece para siempre.`'

Es cierto, que en el camino hacia este logro deben pasar por el juicio,
porque "`Sion será rescatada con juicio, y los convertidos de ella con justicia,`"^
footnote:[Isaías 1:27]
y una porción de indignación e ira,
tribulación y angustia debe (de acuerdo con la ley de la
justicia divina) ser administrada a cada alma que peca.
Pero cuando este juicio es recibido en el día de la misericordiosa visitación de Dios,
es seguido por una paz tan indescriptible y una seguridad del favor divino,
que compensan abundantemente los dolores que pueda haber ocasionado.
Porque, ciertamente, '`el ojo carnal no ha visto, ni el oído escuchado,
ni el corazón concebido,`'^
footnote:[1 Corintios 2:9]
lo bueno que les espera a los que manifiestan su amor a Dios mediante su obediencia.
Créanme, mi amados amigos,
cuando les digo que mi corazón está fuertemente comprometido
con su bienestar mientras están en sus diversas condiciones.
Siento más por ustedes de lo que puedo escribir,
y les suplico por las misericordias de Dios, así como por Sus juicios,
que presenten todo el cuerpo de sus afectos ante Él, que no es más que su culto racional.

¿No les ha repartido Él generosamente a algunos de ustedes las cosas de esta vida?
¿Por qué creen que Él les ha confiado tal abundancia?
¿Es para gratificar los deseos de los ojos y la vanagloria de la vida?
¿Es para hacerlos altivos y que asuman una superioridad
sobre los que en ese sentido están debajo de ustedes,
y sin embargo, puede que algunos de ellos estén más alto en el favor divino?
¡De seguro que no! --sino para que incrementen este don para Su honra,
para el bien de los demás, y para el beneficio de ustedes; y también,
para que se sientan humillados ante el sentido de la desproporción de Sus misericordias,
comparadas con los méritos de ustedes.
¿No ha favorecido Él a algunos de ustedes con habilidades naturales superiores?
¿Y para qué fin, sino para que sean en mayor grado útiles en Su mano?
¿No les ha concedido a todos un día de misericordiosa visitación,
en el que (por varios medios) se ha esforzado por llevarlos a ese redil de reposo inmortal,
donde hace que Su rebaño se alimente y se recueste
junto a las corrientes claras de salvación? ¡Oh,
dice mi alma,
ojalá consideren Sus misericordias y hagan una retribución adecuada de ellas;
para que el Altísimo se deleite en esta presente generación
y habite entre Su pueblo como en los días pasados! ¡Oh,
ustedes de esta generación naciente,
abran las puertas de sus corazones a este divino Visitante,
que por mucho tiempo ha estado llamando a la puerta! ¡Dejen que Él prepare sus corazones,
y con seguridad extenderá Su mesa y los admitirá en Su feliz comunión!

No crean que es demasiado temprano en la vida para
mirar fijamente hacia un futuro estado de existencia;
sino consideren que el solemne mensaje para convocarlos de las obras a las recompensas,
puede ser enviado en una hora temprana e inesperada.
Por tanto, les conviene estar preparados para encontrarse con el gran Juez.
Mi corazón está particularmente comprometido con el bienestar de ustedes,
y se duele al considerar cuán ampliamente se han desviado algunos de ustedes
de esa senda de sencillez primitiva por la que caminaron sus dignos predecesores.
Déjenme, por tanto, suplicarles que busquen el '`buen camino antiguo`'^
footnote:[Jeremías 6:16]
de santidad y que caminen por él,
para que puedan conocer por experiencia al '`Dios de sus
padres y servirle con corazón perfecto y ánimo voluntario;`'^
footnote:[1 Crónicas 28:9]
así Su bendición eterna reposará sobre ustedes, la cual,
en verdad '`enriquece y no añade tristeza con ella.`'^
footnote:[Proverbios 10:22]

¡Qué la nube de testigos del poder e indescriptibles riquezas
de la religión pura y viva prevalezca en ustedes,
para someterlos a su santa influencia,
a fin de que puedan entender correctamente y perseguir diligentemente,
las cosas que pertenecen a la paz tanto aquí como en el más allá!
¡Qué los ejemplos de los justos en todas las generaciones;
qué sus vidas pacíficas y sus felices finales triunfando sobre la muerte,
el infierno y la tumba, en una viva y plena certeza de fe;
qué la solemne importancia del tiempo y de la eternidad
los estimule mientras todavía es de día,
y mientras la luz está sobre sus tabernáculos, a buscar un incremento de sus talentos,
para que de ese modo, sean contados entre los sabios,
quienes serán instrumentos para volver a muchos a la justicia,
y brillar como el resplandor del firmamento, como estrellas por los siglos de los siglos!

Los negligentes y descuidados, los de corazón duro y que están lejos de la justicia,
pueden recibir instrucción al ver el fin de los de similar parecer en todas las generaciones.
Estos no han escapado de los justos juicios del Todopoderoso,
quien ha sellado como una verdad cierta: "`Ciertamente hay galardón para el justo;
ciertamente hay Dios que juzga en la tierra.`"^
footnote:[Salmo 58:11]

Y ahora, queridos amigos,
así como me he esforzado por comunicarles con claridad lo que el Señor
me ha mostrado en relación con los diversos estados entre ustedes,
quisiera advertirles a todos que tengan cuidado de no poner
lejos de sí mismos la porción que les corresponde;
sino que cada uno se examine diciendo: "`¿Soy yo?
¿Soy yo?`"^
footnote:[Mateo 26:22]
Y si creen que las iniquidades reprobadas en esta
carta son de otros y no de ustedes mismos,
no se dejen fijar en un estado de seguridad propia; porque, ciertamente,
cada uno debe sufrir por su propia transgresión. Sé y estoy
agradecida de que el Señor tenga un remanente entre ustedes,
de todos los rangos, a quienes Él ha preservado cerca de Sí mismo.
Mi alma se siente unida a estos en las tribulaciones y alegrías del evangelio;
y a ellos se extiende una salutación que parece levantarse en mi corazón de esta manera:
Hermanos y hermanas, tengan buen ánimo,
"`sean pacientes y esperen hasta el fin,`" porque la mano
del Dios a quien sirven se alarga para ayudarlos;
y si permanecen fieles a Él, en Su tiempo coronará sus sufrimientos con gozo.

Por último, queridos hermanos, me despido; y que la gracia de nuestro Señor Jesucristo,
el amor de Dios y la comunión del Espíritu Santo estén con todos ustedes.
Amén.

[.signed-section-closing]
Su amiga y hermana en la Verdad,

[.signed-section-signature]
Catherine Payton

[.signed-section-context-close]
Dudley, 10 del mes Diez, 1758.

--

[.asterism]
'''

+++[+++Esta última carta está dirigida a su hermano mayor Henry,
quien era hijo de su padre de un matrimonio anterior, pero no de su madre.
Hablando de este hermano en otro lugar de su diario, Catherine dice: "`Cuando era joven,
se humillaba mucho bajo la visitación del amor divino,
pero cuando llegó a la edad madura,
se dejó arrastrar por vanas compañías. Y habiéndose aficionado
al placer y a la gratificación de sus apetitos naturales,
perdió la sencillez de su crianza;
y debido a que deseaba darse gusto en libertades que él
sabía que eran inconsistentes con la profesión de la Verdad,
la desechó; diciendo,
que él no quería retener el nombre (de Cuáquero) y ser un reproche para la gente.]

[.embedded-content-document.letter]
--

[.letter-heading]
A su hermano, Henry Payton.

[.salutation]
Querido hermano,

Hasta ahora, cuando he estado lejos de ti,
me he sentido tranquila con sólo recordarte con sinceros deseos de tu bienestar;
pero ahora, al hallar en mí el deseo de escribirte, no estoy dispuesta a reprimirlo,
aunque sólo sea para hacer todo lo que está en mi poder para fortalecer ese afecto
que debería subsistir entre personas tan cercanamente unidas por lazos naturales.

Pero ¡ay! --cuando considero la diferencia de nuestros apegos,
búsquedas y sentimientos con respecto a todo lo que concierne al bien y al mal,
me atemoriza poner la pluma en el papel,
porque quiero que me leas con sinceridad y entendimiento.
Sin embargo, me animo a mí misma con esta conclusión,
de que tú al menos recibirás esta carta como una muestra de mi consideración hacia ti.
¿Dije consideración? Cambiaré el término por afecto; el cual,
en verdad he sentido brotar tiernamente en mi alma hacia ti,
no sólo como una criatura formada por la misma Todopoderosa mano como yo,
y para el mismo noble fin--a saber, glorificar Al que nos dio existencia,
y nos ha colmado de multitud de favores que reclaman a gritos una respuesta agradecida--sino
también como un hermano que se ha desviado del camino de la paz y seguridad,
y está buscando satisfacción asiéndose de burbujas vacías,
que han tomado la forma (ante su vista) de algo con sustancia.
Pero tu propia experiencia te dirá, si eres imparcial,
que esas burbujas se han roto al tocarlas y que se han desvanecido en el aire,
no dejando nada real detrás de ellas,
sino un agudo sentido de remordimiento y un doloroso recuerdo de que se han perdido,
junto con todo el tiempo, dolor y ansiedad que se dedicaron a la consecución de ellas.
Sin embargo, en esta vana búsqueda (¡oh, triste,
pero una muy justa acusación!) has gastado una gran parte de tu vida;
atravesando apasionadamente los destructivos laberintos de engañoso placer,
y evitando laboriosamente al único Bien,
en Cuya posesión tu alma habría encontrado felicidad sustancial--la felicidad
que te habría concedido el verdadero contentamiento y la plenitud de gozo,
lo único que puede satisfacer la parte inmortal,
al ser ella misma inmortal en su naturaleza.

Tal vez digas que estas son mis opiniones.
Pero permíteme preguntarte, ¿por qué no son las tuyas?
¿Por qué diferimos en opinión y práctica,
sino porque el deseo y la búsqueda de gratificaciones
sensuales han cegado tu juicio y sesgado tus acciones?
Me aventuraré a afirmar que fue el reino o las posesiones de este mundo, sus amistades,
vanidades y placeres sensuales, extendidos ante la vista de tu mente,
lo que te sacó de tu temprano amor y lealtad a Aquel
que es verdaderamente digno de amor y obediencia.
La naturaleza se unió a tentaciones bien adaptadas
(al ser siempre aficionado al disfrute presente,
aunque sea un fruto prohibido),
y renunció a la sumisión a la ley pura de gracia escrita en el corazón; la cual,
si hubiera sido observada,
habría rectificado los apetitos impuros e irregulares de dicha naturaleza,
y te habría colocado en el verdadero estado de madurez,
como señor y no como esclavo de la creación de Dios.
Entonces serías gobernador de ti mismo en feliz sujeción a la voluntad divina;
una voluntad que invariablemente señala la felicidad eterna de la humanidad.
Pero a la naturaleza--rebelde a su propio interés,
cegada por el afecto falso y plagada de orgullo,
como nuestros primeros padres--no le gusta tener un superior que controle su perversidad,
y le señale leyes para dirigirla;
sino que prefiere tener las riendas del gobierno
en su propia mano y planear su propio camino.

Aquí la razón, la razón ciega y caída, entronada por el poder de Satanás,
usurpa el asiento soberano y se sienta en el templo de Dios, siendo honrada como Dios;
y se le adscriben poder, sabiduría y discreción para gobernar y dirigir.
Este falso rey llamado razón humana (quien,
si hubiera ocupado el lugar que le corresponde, habría sido un buen súbdito),
se une luego en estricta asociación a las pasiones
y prescribe reglas dirigidas por estas,
sus aliados.
"`¿Se restringirá el hombre (dice la razón) dentro de las
estrechas reglas de la virtud y la religión? ¡No,
yo proclamo libertad para él! ¡Qué se complazca en lo que es deseable;
qué satisfaga la vista de sus ojos y el orgullo de su corazón,
y se esfuerce por hacerse a sí mismo agradable y admirado por la humanidad! ¡Sí,
qué se una a los demás en plena sociedad y libre comunión,
entreteniendo y siendo entretenido! ¿Por qué no habría
de participar de los placeres de los sentidos,
viendo que tiene apetitos por tales cosas?
¿Por qué no habría de satisfacer su curiosidad conociendo el mal así como del bien?`"

Estas son las genuinas sugerencias de la facultad de razonamiento
cuando es guiada por las pasiones (aunque confieso,
que creo que el sutil engañador de la humanidad,
a veces le enseña a la razón a hablar en un lenguaje más disimulado que
el que he expuesto aquí). Pero creo que no será difícil de probar,
que esta presumida libertad es en realidad esclavitud,
y que esta adquisición de conocimiento no trae más que un sentido de culpa,
resultante de la pérdida de la inocencia que le daba al
hombre el valor de comparecer ante el rostro de la justicia y pureza del Todopoderoso,
libre de temores que lo distrajeran.

Si examinamos la extensión de la virtud y de la verdadera religión,
y luego tomamos nota de toda pasión implantada por
la Providencia en la naturaleza del hombre,
encontraremos que sólo en ellas +++[+++es decir, en la virtud y verdadera religión]
es posible que estos anhelos sean correctamente satisfechos,
y que cada vez que el hombre quebranta sus justos límites,
huye de la marca de su propia felicidad.

He considerado que el amor es la pasión que gobierna en el alma, la cual, según se mueve,
arrastra todo lo demás tras de sí;
y al estar fuertemente fijada en un objeto digno o indigno,
es la causa de nuestro gozo o de nuestra miseria.
Concedido esto, debemos considerar entonces, __qué__ objeto es digno de todo nuestro afecto;
y en esta consideración se debe recordar que esta semilla de amor, o deseo de disfrute,
está tan profundamente arraigada en el alma, que no puede ser sacada de ahí. Ahora bien,
cualquier objeto que merezca que nuestra alma gaste su fuerza en él,
o busque unirse a él sin limitación, no debe depender del tiempo,
porque la muerte pronto lo priva de este;
sino que debe ser tan duradero como la existencia misma del alma,
y tan perfecto como para satisfacer plenamente el deseo eterno de posesión. Evidentemente,
este no puede ser otra cosa más que la Excelencia eterna,
de quien proviene esta chispa de afecto o amor;
y si el orden divino no estuviera invertido,
se inclinaría tan naturalmente hacia su fuente como cae una piedra a la tierra,
el único lugar donde puede encontrar un feliz asentamiento.

En este amor de Dios está la virtud; esto es lo que la inspira.
Si nosotros amáramos verdaderamente a Dios, quien es infinito en pureza y sabiduría,
aborreceríamos naturalmente la impureza y la locura, y nos odiaríamos por causa de ellas;
porque todo lo que contamina el alma,
destruye su semejanza con el Ser divino y la hace inaceptable ante Su vista.
Por lo tanto,
como la naturaleza de un verdadero afecto es buscar el amor del objeto amado,
de aquí procede el ardiente deseo de purificación
y un temor semejante al de un niño de ofender a Dios;
un temor que está más racionalmente fundado en un profundo sentido de gratitud,
al considerarlo el Autor de todo el bien que poseemos o podemos justamente esperar.
Esto, unido al conocimiento de Su poder y justicia en el castigo de las transgresiones,
trae una aguda consciencia de que todo lo que entretenga nuestros
sentidos para alejar nuestro afecto de esta Fuente de bondad,
debería ser temido y rechazado como fruto prohibido.

En la verdadera religión^
footnote:[La vida y luz de Cristo reinando en el alma del hombre.]
el alma está ensanchada y puesta en libertad,
para que ejercite sus más nobles facultades,
en acciones o en objetos que sean dignos de la dignidad de su naturaleza.
De lo contrario, sin dicha religión, el alma permanece en esclavitud,
y se degrada en la búsqueda de lo que apenas merece el nombre de placer,
al no tener verdadero valor o duración perdurable.
En resumen,
la religión coloca al hombre en la esfera que el
sabio Autor de la naturaleza diseñó para él;
dirigiendo sus afectos primero a ascender hacia el Creador,
y luego a descender a la creación. Si el ascenso es suficiente, el descenso será justo.
Las cosas creadas serán amadas como obras y dones del Creador; y sin embargo,
serán poseídas con la debida precaución a partir de esta consideración,
que ellas nos son entregadas por un cierto tiempo, y que por tanto,
es de nuestro mayor interés entregarlas cuando sean
requeridas con el menor dolor o ansiedad posible.
En caso contrario,
el descenso inmoderado de los afectos a las cosas creadas
nos ata a la tierra y a las posesiones terrenales,
nos encadena en gratificaciones sensuales,
impide en gran medida que el alma ascienda a Dios,
y destruye su soberanía delegada sobre la creación, a la que se encuentra esclavizada.
Cuán cierta es la afirmación del apóstol,
de que mientras algunos se jactaban de su libertad, o se la prometían a otros,
ellos mismos eran esclavos de corrupción.^
footnote:[2 Pedro 2:19]

He considerado a veces cómo las excusas de estos
jactanciosos libertinos sólo manifiestan su esclavitud:
"`No podemos evitar tal y cual conducta,`" dicen.
O: "`No tenemos poder para resistir tales tentaciones.`"
Si esto fuera cierto,
sería un reconocimiento de que han perdido la invaluable
bendición que es la libertad de la voluntad,
y de que ahora están completamente desprovistos de poder para resistir el mal,
habiéndose convertido en cautivos del maligno.
Así están, en realidad, aunque no necesariamente, sino voluntariamente.
Porque la sabiduría y el poder, a través de la gracia de Dios,
le son dados al hombre para descubrir y resistir las tentaciones de su enemigo;
y si el hombre renuncia a dicho don,
su ceguera y sujeción al poder del engaño es procurado por él mismo,
junto con su miserable consecuencia, a saber,
la separación eterna de la Fuente de todo bien.

Fácilmente percibirás que la intención de las anteriores sugerencias es influenciar
tu mente a favor de un curso de virtud más estricto que el que has seguido hasta ahora.
¿Qué diré para persuadirte a volverte y a examinarte cuidadosa e imparcialmente?
¿Debo alegar tu avanzada edad?
Tú estás ya (creo) más bien en el ocaso de la vida,
apresurándote a la puerta del jardín. ¿Debo suplicarte, por la misericordia de Dios,
que regreses a Aquel de quien te has rebelado profundamente,
y que busques reconciliación por medio de un arrepentimiento no fingido,
si es que puedes encontrar lugar para hacerlo?
--lo cual yo vívidamente espero que puedas,
aunque te hayas alejado del redil de Cristo por mucho tiempo y de manera tan distante.

No alegaré ninguna excusa por la libertad con la que te he escrito, excepto,
que creo que la verdadera libertad de comunicación de nuestros sentimientos,
con el propósito del bienestar eterno de los demás,
es parte de ese amor que debe revestir los espíritus de los seguidores de Jesucristo.
Espero que la amplitud de mi tema disculpe la extensión de mi carta.
Al repasar lo que he escrito se observará fácilmente,
que las sugerencias dadas no son más que títulos de capítulos, que si fueran ampliados,
podrían llenar un volumen en lugar de una carta.
Que el eterno Ministro del santuario los amplíe a la vista de tu entendimiento,
para tu beneficio duradero, es el sincero y ardiente deseo de tu afectuosa hermana,

[.signed-section-signature]
Catherine Payton.

[.signed-section-context-close]
Escrito en el mar a bordo del Alexander,

[.signed-section-context-close]
6 del mes Diez, 1753.

--

[.asterism]
'''

__Como se mencionó anteriormente, Catherine Payton entró en la obra del ministerio en 1748,
a los 22 años,
y viajó casi incesantemente en la obra del evangelio
hasta su matrimonio con William Phillips en 1772.
Después de su matrimonio siguió trabajando activamente en la iglesia por muchos años,
pero tras sufrir muchas lesiones por caídas de su caballo,
y estar cada vez más afligida por rigidez en sus articulaciones que "`desconcertaba
todo tratamiento médico,`" fue lentamente reducida a una condición bastante débil,
y al final se vio largamente confinada a su casa en Cornwall.
Murió el 16 del mes Ocho, 1794, a los sesenta y ocho años,
y cuarenta y seis años de ministerio.__

__Es difícil trasmitir el verdadero valor de esta sierva del Señor,
la influencia de su ministerio,
o la estima que le tenían sus contemporáneos y compañeros de ministerio.
El siguiente pasaje está tomado del diario de Sarah R. Grubb,
escrito después de una visita a Catherine Payton cerca del final de su vida.
"`Ella ha sido una sierva fiel y laboriosa en la iglesia,
especialmente bajo el ejercicio de su don, el cual era notable por su pureza,
abundancia y claridad.
Su ministerio ha tenido la tendencia de levantar en dominio la vida pura,
y en la súplica,
a menudo ha sido maravillosamente favorecida con un acceso cercano al trono,
capacitada para arrojar toda corona, y atribuirle adoración y alabanza,
salvación y fuerza al Señor Dios y al Cordero.
Desde que mi mente ha sido misericordiosamente visitada con un sentido de la Verdad,
tales han sido mis sentimientos respecto a esta grande y buena mujer.
Pero hace unos dos años,
para mi humilde admiración en un tiempo de gran prueba de espíritu,
esta convicción fue profundamente renovada y sellada en mí;
pues sentí una persuasión interna muy fuerte y una incuestionable evidencia,
de que ella era una fiel seguidora del Cordero.
En efecto, oí un dulce lenguaje fluyendo a través de mi mente que decía:
Yo la he escogido y es Mía.`"__
